de_web.pro
rest_node_base.h

Reverted commit a86a620c2a121f080242bc0073955ce584c8d4f6 (see issue #17 )

add /usr/include to INCLUDES; revert commit a86a620

---

de_web_plugin.cpp
sensor.cpp
sensor.h

- Bug fix: lux computation from light level (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/20#issuecomment-320905040, item 5);
- Enhancement: support button events 4001, 4003, 5001, 5003 for Trådfri remote Previous and Next hold and long release (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/23#issuecomment-318907744);
- Bug fix: ubisys dimmer's manufacturer reported as Philips (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/97#issuecomment-321784033).

Trådfri remote enhancement; bug fixes

---

de_web_plugin.cpp
rest_sensors.cpp
sensor.cpp

Code already queues these events, but they were not handled.

Websocket events for changes to sensor config

---

de_web_plugin.cpp

Translate raw multistage input values into meaningful buttonevent values, see #138.

Cube magic

---

.gitignore
de_web_plugin.cpp
sensor.cpp

IKEA Trådfri dimmer

---

de_web.pro
group.cpp
rest_groups.cpp
rest_sensors.cpp

Implement group `state.all_on` and update API version to 1.0.5.
Fix inconsistency in websocket notifications.

Implement group state.all_on

---

de_web_plugin.cpp
sensor.cpp

Add support for Xiaomi Aqara flood (leak sensor).  See #263.

Xiaomi Aqara flood sensor

---

bindings.cpp
database.cpp
de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
reset_device.cpp
resource.cpp
resource.h
rest_lights.cpp
rest_sensors.cpp

Just a first take at supporting the Heiman sensors, most still as ZHAPresence, see also #404 and #407.
@manup can you please review the changes I've marked.

Heiman sensors and more

---

bindings.cpp
database.cpp
de_web_plugin.cpp

- Relax _Model Identifier_ checks for Heiman sensors, see #352.
- Xiaomi Mi smoke sensor, see #152.

More sensor stuff

---

de_web_plugin.cpp
de_web_plugin_private.h

- Heiman smart plug seems to report _Current Summation Delivered_ in 0.1 Wh, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/432#issuecomment-370077294;
- Xiaomi smart plug has (also?) vendor code 0x115f, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/432#issuecomment-369956538.

More smart plug stuff

---

database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
rest_lights.cpp
zcl_tasks.cpp

Add support for the Heiman Siren, see #404.

Heiman Siren, see #404

---

de_web_plugin.cpp

Only process event attributes for Electrical Measurement cluster

---

de_web_plugin.cpp

Similar to Xiaomi Aqara wall switch, see #356.

Combine ubisys switch endpoints into one ZHASwitch resource

---

de_web_plugin.cpp

- Update `state.water` for lumi.sensor_wleak.aq1;
- Update `state.pressure` for lumi.sensor_weather.

More Xiaomi magic

---

database.cpp
de_web_plugin.cpp
rest_rules.cpp

- Set `lasttriggered` in UTC instead of localtime;
- Fix firing rule with `in` condition on `/config/localtime`;
- Don't restore `timestriggered` from database on restart (so it resets to 0).

Bug fixes rules, see #413

---

de_web_plugin.cpp

Support atsmart Z6-3 switch

---

database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
general.xml
sensor.cpp
sensor.h

Xiaomi Aqara vibration sensor

---

description_in.xml
upnp.cpp

I accidentally introduced a difficult to find bug in that it announced uuid:xxx::upnp:rootdevice twice instead of announcing uuid:%1::urn:schemas-upnp-org:device:basic:1 causing some strange behaviour. Also I believe but am not completely sure you should acknowledge a search on the same socket so I changed that, plus some refactoring.
Furthermore, it seems Amazon Echo expects the manufacturer in description.xml to be Philips (#902).

Fixes to upnp

---

rest_lights.cpp

Amazon Echo control On/Off devices

---

general.xml

More information here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883

Update general.xml for Legrand switch support

---

database.cpp
de_web_plugin.cpp

- Suppress creating / loading ZHAPower sensor for OSRAM plug, as it doesn't actually report power, see #1010;
- Scale innr SP 120 consumption correctly (sensor reports in 0.01 kWh (10 Wh) instead of 0.001 kWh (1 Wh).  Thanks to Wim @wvuyk for pointing this out to me.

Smart plugs

---

de_web_plugin.cpp
de_web_plugin_private.h
thermostat.cpp

Fix polling and increased increased interval to more than 10 minutes.

Fix Thermostat Cluster polling interval

---

de_web_plugin_private.h

Add Samsung SmartThings manufacturer code
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/993
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/946

Add Samsung SmartThings manufacturer code

---

thermostat.cpp
window_covering.cpp

Fix writing 8-bit bitmap attributes to Thermostat Cluster.
Fix reading multiple attributes from Window Covering Cluster.

Fix read and write attributes on Thermostat and Window Covering Clusters

---

de_web_plugin.cpp

- Apply `config.offset` when updating `state.temperature` or `state.humidity`, see #1154;
- Also update etag and save to database when only `config.reachable`, `config.battery`, and/or `state.lastupdated` are updated;
- Issue event when `state.lastupdated` is updated to fire rules based on `state.lastupdated`.

Bug fixes Xiaomi special report

---

bindings.cpp
database.cpp
de_web_plugin.cpp
rest_sensors.cpp

_Model Identifier_ SML002 (vs SML001 for the regular motion sensor).  See #1201.

Hue outdoor motion sensor

---

general.xml

Shade Configuration cluster

---

de_web_plugin.cpp

Bug fix: wrong endpoints for ZHAPower and ZHAConsumption.  See #1249.

lumi.ctrl_ln1

---

rest_sensors.cpp

Eurotronic Spirit: When `heatsetpoint` is changed, set `mode` to `auto`.

---

de_web_plugin.cpp
light_node.cpp
zcl_tasks.cpp

Came across one of these commands in the sniffer and saw that the payload was too big.

Bug fix: _Effect Identifier_ is u8.

---

bindings.cpp
general.xml
thermostat.cpp

- Refactor attribute reporting configuration, see #1331;
- Setup attribute reporting for Eurotronic Spirit;
- Report Eurotronic Spirit as Off when valve position <= 3.  Sometimes it seems to report a small value, when the valve seems to be closed.

Configure attribute reporting

---

de_web_plugin.cpp
light_node.cpp

Support ZHA On/Off Light Switch device type / Sinope smart light switch 1800 W – SW2500ZB

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
rest_lights.cpp

Support iCasa in-wall switch, Hampton Bay fan controller

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
poll_manager.cpp

Develco (smoke sensor) improvements

---

bindings.cpp
de_web_plugin.cpp

Adds basic support for LifeControl SmartPlug MCLH-03

Add support for LifeControl smart plug

---

de_web_plugin.cpp
general.xml

IKEA FYRTUR and KADRILJ

---

bindings.cpp
de_web_plugin.cpp
general.xml
sensor.cpp

- Setup binding and attribute reporting for FYRTUR/KADRILJ, see #1121;
- Create group for TRADFRI open/close remote, see #1121;
- Buttonevents for TRADFRI open/close remote, see #1121;
- Create group for (new) TRADFRI motion sensor, see #1676.

FYRTUR/KADRILJ; TRADFRI open/close remote; TRADFRI motion sensor

---

de_web_plugin.cpp

Fixing Current and Power consumption convertion

Life control smart plug fix

---

general.xml

Include Power-On settings for LEDVANCE bulbs as well. https://github.com/dresden-elektronik/deconz-rest-plugin/pull/1837

LEDVANCE Power-On Defaults: Update general.xml

---

de_web_plugin.cpp
de_web_plugin_private.h
sensor.cpp

Support Sunricher (Luzense) switches

---

bindings.cpp
database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
sensor.cpp

Support IKEA SYMFONISK sound controller

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
window_covering.cpp

More information here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883
- Better integration for all devices and future one
- remove current and voltage
- Device id correction for shutter.

Better integration for Legrand netatmo gamme

---

rest_lights.cpp
window_covering.cpp

The previous modification have a bug, "on" and "bri" have opposed information (problem for stop position)
Now we have
Open : on = false / bri = 0
Close : on = true / bri = 254

Better correction for inverted direction for Legrand Window covering.

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp

As per #1998 
Based on code for other smart plugs as best I can tell. Works for on/off but doesn't create any sensors for power monitoring. Any suggestions on where to start with that?

Initial support for Netvox Z809A smart plug

---

bindings.cpp
database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
sensor.cpp

Trying to add support for the Aqara Opple switches. See #2061 
Although the switches already work, there are still multiply issues:
1. The switches share the same vendor group with `VENDOR_115F`. I suspect this might be causing some of the issues.
2. Adding a switch does not always work for some reason. Sometimes it works on first try but sometimes i have to try multiply times. I have no idea why.
3. I can only add a switch when i search for sensors. I can also search for switches but that never succeeds, even that the switch still gets paired but is behaving strange. Also no idea why...
4. When i add a switch then always a new group is created for every switch. I have already like 50 groups right now (because of multiply times removing and re-adding the switches). Can this be somehow …

Add support for Aqara Opple switches - WIP

---

bindings.cpp
database.cpp
de_web_plugin.cpp
de_web_plugin_private.h

- Added initial support for Tuyatec motion sensor (#2370, #2360, #2275)
- Added support for Salus SP600 smart plug (#812)
- Sensor cosmetics for SmartThings ZB-ONOFFPlug-D0005
- Update for Heiman HS1SA-N smoke sensor (#2323, #2373)
- Update for binding and attribute reporting of Develco EMIZB-132, measurement units amended (#2127)
- Added initial support for Xiaomi Mijia Zigbee 3.0 Smart Home Light Sensor (#2380)
- Removed code duplicate

Integration of various devices

---

bindings.cpp
de_web_plugin.cpp
general.xml

- Optimizations for lumi.plug country models
- Changed data type for Xiaomi smart plug consumption (Potential fix for #2094, #1592, #1513 ?)
- Update for Develco sensor battery reporting
- Typo correction and additions in general.xml
- Added initial support for SmartThings motion sensor (#2389)
- Re-added Develco window sensor to update battery
- Code cleanup in bindings.cpp

Several device updates

---

bindings.cpp
database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
resource.cpp
resource.h
rest_lights.cpp
sensor.cpp

Hue dimmer switch and Lutron Aurora Friends-of-Hue dimmer switch

---

de_web_plugin.cpp

Adds support for and closes #2633. Also fixes the manufacturer name detection for Tuya.

feat: adds support for Tuya gas sensor

---

bindings.cpp
de_web_plugin.cpp

This will introduce only a little extra traffic, but will help the routing changes effectiveness of firmware "26350500". See also: #1261

Re-enable some ApsTxAcknowledgement requests

---

README.md

Update README.md > Add deCONZ discord. 

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h

PST03-A sensor, a multisensor https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2753

Device integration

---

de_web_plugin.cpp

My attempt at fixing #2800 based on the commit listed in the issue. The plugin builds fine but I haven't yet figured out how to inject the plugin into the home assistant deconz add on to verify this.

Initial support for Quirky Tripper open close sensor made by SerComm

---

bindings.cpp
de_web_plugin.cpp

- Reverted previous change
- Update for battery reporting

Update for LifeControl Enviroment sensor

---

bindings.cpp
database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
general.xml
poll_manager.cpp
sensor.cpp

- Corrected selection of button map for RGBgenie ZB-5121
- Bugfixes for IMMAX Neo smart plug power sensor
- Added Appliances domain to general.xml
- Added support for Immax NEO ZB3.0 4 in 1 sensor (#2819)
- Added initial support for Embertec smart plug BQZ10-AU (#2823)
- Allow Heiman remote control HS1RC-M to act as regular remote (#2697)
- Correct Heiman remote control HS1RC-M battery value

Bugfixes and further devices

---

.github/stale.yml

Lets see how this work out. Closed after 1 month inactivity.

Updating the time before stale

---

bindings.cpp
sensor.cpp

Legrand Typo bug

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/device-request.md
.github/ISSUE_TEMPLATE/feature_request.md

First set of templates, please approve :)

Update issue templates

---

appliances.cpp
bindings.cpp
database.cpp
de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
general.xml
poll_manager.cpp
sensor.cpp

- Updated RGBgenie-5121 button map
- Added support for Heiman motion sensor HS1MS-E (#1974)
- Enable WAXMAN leakSMART to create water sensor (#2701)
- Added IAS ACE for client cluster search
- Added support for Sengled contact sensor E1D-G73 (#2870)
- Added initial support for ROBB Smarrt micro dimmer ROB_200-011-0 (#2829)
- Enable water detection for WAXMAN leakSMART water sensor v2 (#2701)
- Added initial support for Stelpro baseboard thermostat STZB402+ (#2945)
- Added initial support for Centralite 3315 water sensor (#2944)
- Prevent power sensor creation and added interlock attribute for lumi.relay.c2acn01 (#2909)

Updates for devices

---

.github/stale.yml

Just to make sure it doesn't get closed.

Adding "backlog" label to exemptLabels.

---

rest_lights.cpp
window_covering.cpp

Fix open/close logic for SR-ZG9080A

---

database.cpp
de_web_plugin_private.h

According to #2951 this function is no longer used
Fix: #2951

Remove DeRestPluginPrivate::clearDb()

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
light_node.cpp
rest_lights.cpp
zcl_tasks.cpp

Danalock support added
Conflicting files fixed :-)
Instead of reading the state in deCONZ GUI, I just added it to its own group in Phoncon. Removed one of the batteries and waited a few seconds. Then installed the battery again and turned the group in Phoscon on and off a few times

Danalock V3

---

de_web_plugin_private.h
general.xml
rest_sensors.cpp
thermostat.cpp

With help from @peterguy04
So not sure for recast (lot of type recast), but this code is needed for at leat one thermostat device.
The device work only if we write all attributes in one command, (so impossible to test the device using deconz).
For the moment I m using it only for minimum we need, but can be used later for all thermostat write attribute.

Thermostat improvement

---

.github/workflows/release-drafter.yml

Adding release drafter to create a automated release.

Setup of release drafter

---

bindings.cpp
de_web_plugin.cpp
general.xml

2 lines devices. Realy nothing special in code but realy nice device > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3040

Legrand Teleruptor and Xiaomi switch

---

rest_lights.cpp

Improvement for Profalux device > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2739
This device is a covering but still in light section, because It works realy like a bulb

Profalux Impovement

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h

Shade on batterie.
From https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3057

Axis Gear Zigbee Shade

---

rest_configuration.cpp

See https://github.com/ebaauw/homebridge-hue/issues/749.

Lastest Hue bridge firmware version.

---

.github/stale.yml

Updating Stale comments on closing and marking

---

database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
thermostat.cpp
time.cpp

- Poll _Time_ cluster every 6 hours (instead of every minute), in line with eCozy gateway.
- Don't reset `config.duration` for Aqara motion sensor on load.  See #1366, #1395, #1468.  All closed by the bot, but never resolved.  Issue popped up again on Discord, #restapi-issues channel.
- Sometimes ZHAThermostat attributes wouldn't be updated, see #technical-talk channel on Discord.

Various bug fixes and more eCozy

---

.github/stale.yml

Added Awaiting Merge to prevent closure of Awaiting merge device requests.

Add Awaiting merge

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h
linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh

Added vendor id to add support for axis shades in Rest API.

Added Vendor Axis and Vendor_mmb for axis shades

---

de_web_plugin.cpp

This is a pull request for issue [#2108](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2108)
I am new to C++ so feel free to make any code suggestions.

Add support for Illumra Dual Rocker Switch which uses the FOH PTM215ZE module

---

bindings.cpp
button_maps.json
de_web_plugin.cpp
read_files.cpp

- Hardcode Samjin motion sensor as such (#3375)
- Hive motion sensor now correctly exposed as such
- Expose battery value for Bosch motion sensor ISW-ZPR1-WP13 (#3393)
- Add button maps for ZGRC-KEY-007 and ZGRC-KEY-009 (#3396, #3397)

Enhancements

---

de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
general.xml
green_power.cpp
green_power.h
permitJoin.cpp

Based on @Smanar and @Koenkk code, this PR adds the ability to configure ZGP proxies to relay ZGP commands.
Note that new changes in core required as well.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/436

Support ZGP proxies

---

de_web_plugin.cpp

Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3285

Fix Ilumra FoH dual rocker switch vendor prefix check

---

de_web_plugin.cpp
sensor.cpp

Skip the check for empty buttonmap, as it doesn't work.  See #3425.

FIx lumi.sensor_86sw switches

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/user-question.md

Added a question to bug report and user question template.
- Is there any other USB or serial devices connected to the host system? If so: Which?

Changes to issue templates

---

de_web_plugin.cpp

This code is totally useless (was from me) and can cause issue for other device than tuya.
It s a rollback, will not change anything on original working mode.

Tuya rollback

---

bindings.cpp
database.cpp
de_web_plugin.cpp
general.xml
resource.cpp
resource.h
rest_sensors.cpp
thermostat.cpp
thermostat_ui_configuration.cpp

- Add initial support for Stelpro Orleans Fan (SORB) #3323 
- Introduce `RConfigCoolSetpoint` to REST API

Add initial support for Stelpro Orleans Fan (SORB) [01]

---

de_web_plugin.cpp

add initial support for TS0205 tuya smoke sensor

---

tuya.cpp

Also remove self assignment to fix compiler warning.

Fix missing break in Tuya switch statement

---

bindings.cpp
de_web_plugin.cpp

In reality was tuya stuff, but for the moment it's the hardware that respect "zigbee rules".

Initial support for Lidl motion sensor (TY0202)

---

button_maps.json
de_web_plugin.cpp
de_web_plugin_private.h

Add support for newer version of Trust ZYCT-202 (ZLL-NonColorController)

---

de_web_plugin.cpp

Added Schlage Connect Smart Deadbolt BE3468 to stricter door lock check. Addresses issue #3676

Restore support for Schlage Connect Smart Deadbolt B3468

---

de_web_plugin.cpp

Added support for LEDVANCE aka Sylvania BR30 and A19

Added support for LEDVANCE aka Sylvania BR30 and A19

---

de_web_plugin.cpp

Support Benexmart 3 gang switch variant (TS0043)

---

database.cpp
de_web_plugin.cpp
rest_sensors.cpp

Nothing special
cf https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3109

Saswell SEA801 - New variant for the device

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Samsung water leak sensor (moisturev4)

---

bindings.cpp
de_web_plugin.cpp

Nothing special 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3767

Initial support for Lidl/SilverCrest Smart Window or Door Sensor (TY0203)

---

de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
identify.cpp

By pressing the 'C' button on the back side the respective command is sent to enable correct mode of operation.

Fix setup for Aqara Opple when connected via coordinator

---

de_web_plugin.cpp
de_web_plugin_private.h
xmas.cpp

Minor enhancements and bug fixes, see #3716.

Merry Christmas 3

---

general.xml
rest_lights.cpp
window_covering.cpp

Tuya Cover, reverse Lift for a special device TS130F

---

database.cpp
de_web_plugin.cpp

Was Heiman or some weird Tuya string before.

Lidl motion (TY0202) and contact sensor (TY0203) change manufacturer to SILVERCREST

---

rest_groups.cpp

Simple change to support the additional class options from Hue api v1.30.

Add additonal room classes from api v1.30

---

database.cpp
de_web_plugin.cpp
ias_zone.cpp
light_node.cpp
resource.cpp
resource.h

- Add support for _Test_ bit in _Zone Status_, see #3871;
- FIx bug: some devices never enrolled, see #3872.

IAS Zone enhancement and bug fix

---

de_web_plugin.cpp

Add initial support for Orvibo Combustible Gas Sensor

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Keen home vent v2

---

bindings.cpp
de_web_plugin.cpp

Nothing special : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3667

Develco smart cable

---

bindings.cpp
de_web_plugin.cpp

Reverts dresden-elektronik/deconz-rest-plugin#3954

Revert "Develco smart cable"

---

de_web_plugin.cpp
xmas.cpp

See #3716: revert `bri_inc` support and trying to keep _Current Level_ up to date with actual brightness.

Merry Christmas #4.

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Feibit smoke sensor SSA01ZB (FNB56-SMF06FB1.6)

---

bindings.cpp
de_web_plugin.cpp

Add support for Develco Temperature and Humidity Sensor HMSZB-110

---

button_maps.json

The model id wasn't complete.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3969

Fix SYMFONISK Sound Controller

---

de_web_plugin.cpp

Regression from PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3703

Fix HTTP accept header parsing for proper application/vnd.ddel.* format

---

bindings.cpp
database.cpp
de_web_plugin.cpp
rest_sensors.cpp

- Enable/Add corresponding attribute reporting
- Additionally expose RStateValve, RConfigLocked and RConfigMode

Enhance support for Sinope TH1300ZB thermostat

---

resource.cpp

Product identifier addition for some tuya hardware.

---

button_maps.json
de_web_plugin.cpp
de_web_plugin_private.h

- Add Sengled E1E-G7F button map (#3308)

Enhancements for Sengled E1E-G7F

---

resource.cpp
rest_lights.cpp
window_covering.cpp

Product covering Update for some covering

---

database.cpp
de_web_plugin.cpp
de_web_plugin_private.h
rest_lights.cpp
rest_sensors.cpp
time.cpp
tuya.cpp
tuya.h

This cleans up code to align with remaining code base style.
Partly for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4087 and earlier Tuya code.

Tuya cleanup 4087

---

button_maps.json

Added button map for Elko ESH 316 Endevender RF

Add button map for Elko ESH 316 Endevender RF

---

button_maps.json
de_web_plugin.cpp

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3042#issuecomment-757118520

Add tuya switch _TZ3000_peszejy7/_TZ3000_qzjcsmar/TZ3000_owgcnkrh/_TZ3000_adkvzooy/_TZ3000_arfwfgoa

---

bindings.cpp
de_web_plugin.cpp

Add initial support for NYCE NCZ-3041-HA motion sensor

---

de_web_plugin.cpp
light_node.cpp

Add initial support for Climax smoke detector SD-8SCZBS

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Sercomm motion sensor SZ-PIR02

---

bindings.cpp
de_web_plugin.cpp
rest_sensors.cpp

Add initial support for OWON PCT502 Thermostat

---

bindings.cpp
de_web_plugin.cpp

Add support for Salus SPE600 smart plug

---

de_web_plugin.cpp

Add support for Sylvania/LEDVance RT 5/6 RBGW

---

de_web_plugin.cpp

Whitelist new version of ELKO Super TR thermostat

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Heiman remote controller RC-EF-3.0

---

bindings.cpp
de_web_plugin.cpp

Add initial support for GamaBit GMB-HAS-WD-B01

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Sercomm water sensor SZ-WTD02N_CAR

---

de_web_plugin.cpp

See #3133 for details.
Tested and working in my dev environment
Further references: #3500, #4099, https://github.com/dresden-elektronik/phoscon-app-beta/issues/339

Hotfix to prevent segfault while importing backups

---

bindings.cpp
database.cpp
de_web_plugin.cpp

Add initial support for Xiaomi Aqara T1 water leak sensor SJCGQ12LM

---

bindings.cpp
de_web_plugin.cpp

Add initial support for GamaBit GMB-HAS-WL-B01 water leak sensor

---

bindings.cpp
de_web_plugin.cpp

Add initial support for GamaBit GMB-HAS-VB-B01 vibration sensor

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Tuya remote controller TS0215

---

de_web_plugin.cpp
fan_control.cpp
read_files.cpp
thermostat.cpp
thermostat_ui_configuration.cpp

- Add missing handler for IAS ACE data indications
- Prevent loading of erroneous button map entries

Various bugfixes

---

poll_manager.cpp

Also let Xiaomi mains powered devices poll

---

button_maps.json

Provide better button descriptions in generated documentation.

Lutron Aurora describe buttons in button map

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Feibit FB56-DOS06HM1.3 door/window sensor

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Orvibo smoke sensor SF30

---

de_web_plugin.cpp
light_node.cpp
resource.cpp

This PR make the tuya extender visible in API.

Add initial support for Tuya extender.

---

de_web_plugin.cpp

Nothing special, just ading the device in whitelist : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4511

Add initial support for Tuya ZigBee Multi-Sensor 4 in 1

---

button_maps.json
de_web_plugin.cpp

Add Lonsonho Tuya Zigbee 3 gang switch (TS0043 / _TZ3000_a7ouggvs)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/device-request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/user-question.md

Added line to keep headers in the template on issue creation.

Update issue templates 

---

button_maps.json

As per @SwoopX suggestion here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4645

Updated button_maps.json with RGBgenie ZB-5004

---

de_web_plugin.cpp
de_web_plugin_private.h

See #4648
Tested and confirmed to be working.

Add support for Mi version of light detector (lumi.sen_ill.mgl01)

---

de_web_plugin.cpp

Allow Xiaomi Aqara Single Switch Module T1 to create sensor resources

---

.github/workflows/verify-button-maps.yml
button_maps.schema.json

This will run for each PR with changes to button maps.

 Add Github Action to validate button_maps.json for PRs

---

rest_lights.cpp
tuya.cpp

Nothing special https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4288#issuecomment-814036296

FIX, reverse 2 tuya covering direction.

---

bindings.cpp
de_web_plugin.cpp

Identical to Develco SPLZB-131

Add support for Aurora Smart16ARelay51AU smart plug

---

de_web_plugin.cpp

Fix Content-Length header in HTTP response

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Niko Smart Plug 552-80699

---

bindings.cpp
database.cpp
de_web_plugin.cpp

Add initial support for Alcantara 2 acova thermostat

---

bindings.cpp
de_web_plugin.cpp

Add initial support for D-Link DCH-B122 motion sensor

---

de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
electrical_measurement.cpp

Move any code related to electrical measurement cluster to a dedicated file. This shall ensure all relevant code is at one place for better overview and to reduce the size of `de_web_plugin.cpp`.

Move electrical measurement related code to dedicated file

---

de_web_plugin.cpp

Nothing special, another model
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4806

FIX : Create a battery sensor for Tuya Blind AM43

---

bindings.cpp
de_web_plugin.cpp

- Product name: Light sensor
- Manufacturer: _TYZB01_4mdqxxnn
- Model identifier: TS0222
Nothing special https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4348

Add initial support for Tuya TYZB01 light sensor

---

de_web_plugin.cpp
de_web_plugin_private.h
simple_metering.cpp

Move any code related to simple metering cluster to a dedicated file. This shall ensure all relevant code is at one place for better overview and to reduce the size of `de_web_plugin.cpp`.

Move simple metering related code to dedicated file

---

button_maps.json
de_web_plugin.cpp

Add initial support for Xiaomi Aqara D1 switches QBKG21LM & QBKG22LM

---

de_web_plugin.cpp
rest_lights.cpp

Model
>     {"_TYST11_d0yu2xgi", "0yu2xgi", "NEO/Tuya", "NAS-AB02B0 Siren"},
>     {"_TZE200_d0yu2xgi", "TS0601", "NEO/Tuya", "NAS-AB02B0 Siren"},
Have made something wrong on PR, and this part have skipped.

Fix : Tuya siren

---

button_maps.json

Add Namron modelId 4512729 to corresponding button map

---

rest_lights.cpp

This isn't used anymore, further this is the job of Poll Manager.

Remove dead light.state read code

---

de_web_plugin.cpp
de_web_plugin_private.h
tuya.cpp

Solve heatseatpoint missing on model _TZE200_fhn3negr

Add a new MAC adress range for Tuya TRV and FIX bad device reconisation.

---

button_maps.json
de_web_plugin.cpp

Manufacturer: _TZ3000_dfgbtub0
Model identifier: TS0042
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4890

Add another tuya battery switch

---

button_maps.json
de_web_plugin.cpp

Nothing special https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4810
- model _TZ3000_xabckq1v

Add another Tuya switch

---

de_web_plugin.cpp

* Allow multipart/form-data header to have additional content as come clients like curl use;
* Use faster `hdr.httpMethod()` to detect POST request;
* Improve extracting file content from the request;
* Return HTTP status 400 Bad Request if request couldn't be parsed.

Improve backup upload handling

---

bindings.cpp
de_web_plugin.cpp
firmware_update.cpp
light_node.cpp
light_node.h
poll_manager.cpp
rest_node_base.cpp
rest_node_base.h

* Use `DeviceEnumerator` singleton with cached enumeration;
* Only enumerate devices when not connected since this is rather expensive.

Don't periodically enumerate device list in firmware update handler

---

button_maps.json

Add missing button map for Immax Keyfob-ZB3.0

Add button map for Immax Keyfob-ZB3.0

---

rest_lights.cpp

Don't send _Off with Effect_ to KNYCKLAN receiver, see #4964.
Untested as I don't have this device.

Fix KNYCKLAN receiver doesn't turn off.

---

bindings.cpp
de_web_plugin.cpp

Add initial support for LK Wiser Temperature and Humidity Sensor CCT593011_AS

---

de_web_plugin_private.h

Increase length of rule name to 64.

---

button_maps.json

This should address #4450. However, I cannot tell if this might be already enough or not.

Add button map for LIDL doorbell

---

button_maps.json

See #4601. Assuming it is yet another identical Sunricher switch.

Add ROB_200-008 to Sunricher button map

---

bindings.cpp
database.cpp
de_web_plugin.cpp
rest_sensors.cpp

Add "offset" for pressure sensor too, like for temperature and humidity.

Improve : Add offset config for pressure sensor.

---

de_web.pro
de_web_plugin.cpp
de_web_plugin_private.h
occupancy_sensing.cpp

Move any code related to occupancy sensing cluster to a dedicated file. This shall ensure all relevant code is at one place for better overview and to reduce the size of `de_web_plugin.cpp`.

Move occupancy sensing related code to dedicated file

---

xiaomi.cpp

My bad, I forget the manufacture cluster for them.

FIX : enable offset for pressure for Xiaomi sensors

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Immax NEO ZB3.0 window/door sensor 07045L

---

bindings.cpp
de_web_plugin.cpp

Add initial support for Swann One Motion Sensor SWO-MOS1PA

---

electrical_measurement.cpp

Fix: Develco EMIZB-132 voltage calculation

---

de_web_plugin.cpp

* Always read SwBuildId
* Fall back to Date Code if SwBuildId isn't available
* Handle empty string attributes
* Remove related device specific code

Improve reading sensor basic cluster attributes

---

bindings.cpp
de_web_plugin.cpp
de_web_plugin_private.h

Just a presence sensor, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5097

Add new sensor, ADEO - Animal compatible motion sensor

---

general.xml

Adds recently discovered attributes.

Xiaomi specific attribute additions for given clusters

---

general.xml

Add some manufacturer specific attributes for Develco IO module.

Add Develco specific attributes to general.xml

---

database.cpp
de_web_plugin.cpp
product_match.cpp
tuya.cpp

Nothing special
> Product name: Woox R7049 Smoke Alarm
> Manufacturer: _TZE200_aycxwiau
> Model identifier: TS0601
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4693

Add support for Woox R7049 Smoke Alarm

---

devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json

Add DDF for Xiaomi Aqara MCCGQ14LM open/close sensor (lumi.magnet.acn001)

---

devices/generic/items/config_coolsetpoint_item.json
devices/generic/items/config_displayflipped_item.json
devices/generic/items/config_externalsensortemp_item.json
devices/generic/items/config_externalwindowopen_item.json
devices/generic/items/config_locked_item.json
devices/generic/items/config_mountingmode_item.json
devices/generic/items/config_schedule_on_item.json
devices/generic/items/state_angle_item.json
devices/generic/items/state_errorcode_item.json
devices/generic/items/state_fire_item.json
devices/generic/items/state_humidity_item.json
devices/generic/items/state_mountingmodeactive_item.json
devices/generic/items/state_pressure_item.json
devices/generic/items/state_tilt_item.json
devices/generic/items/state_valve_item.json
devices/generic/items/state_water_item.json
devices/generic/items/state_windowopen_item.json
devices/generic/items/state_windowsopen_item.json

Just some items I stumbled upon missing while working on my device DDFs.

Addition of DDF resource items

---

product_match.cpp
rest_lights.cpp
window_covering.cpp

Manufacture name : _TZ3000_kpve0q1p

FIX : Reverse Side for a new covering.

---

README.md
product_match.cpp

Used to reverse side
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3757#issuecomment-943616835

FIX : Add new manufacture name

---

devices/dresden_elektronik/fls_pp3.json

One of the rare devices with different model ids per endpoint.
Fixes the display in Phoscon App.

Improve FLS-PP3 DDF multi endpoint handling

---

devices/generic/subdevices/Range_extender.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5275
Not sure for "order"

Add generic json for Range Extender (DDF)

---

.gitignore
general.xml

GUI support for IKEA Starkvind Air Purifier

---

rest_sensors.cpp
tuya.cpp

Product ID
- Tuya_THD WZB-TRVL TRV
- Tuya_THD Smart radiator TRV
- Tuya_THD SEA801-ZIGBEE TRV
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5436

FIX : Re enable "auto" for some Tuya TRV

---

general.xml

As per  [Issue 5334](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5334#issuecomment-967268681) adds Power on state config change to Tuya TS011F - TZ3000 Plugs.

Add Power On State Change For Tuya TS011F

---

product_match.cpp

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5495

FIX: Add a Tuya TRV clone

---

device_access_fn.cpp
devices/xiaomi/xiaomi_airmonitor_acn01.json
xiaomi.cpp

- Fix parsing Xiaomi special report to support 0x0000 and 0xfcc0 cluster id.
- Bail out early in old Xiaomi  special report handler for managed devices.

Add Aqara TVOC DDF

---

database.cpp

Single quotes are accepted by the REST API but aren't stored and potentially cause a security risk.
This change escapes single quotes by using two ' quotes, in the SQLite way. They are read back as single quote.
Affects lights, sensors, groups, scenes and all DDF ResourceItems.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4599

Fix single quotes in names, prevent SQL errors

---

rest_lights.cpp

Another place required to be able to handle covering resource items.

Another place to whitelist Aqara E1 roller shade driver

---

de_web_plugin.cpp
device_descriptions.cpp

Prior reachable was only set for sub resources which received specific incoming commands. This PR considers all sub resources reachable if anything is received, like the legacy code does.

DDF set reachable for managed sub resources

---

devices/xiaomi/xiaomi_airmonitor_acn01.json

Mine just reportet ~9000 ppb, so clearly not out of scale.

DDF Aqara air quality TVOC raise unhealthy max value to 10000

---

button_maps.json
de_web_plugin.cpp
devices/wiser/fuga_4button_battery_switch.json
devices/wiser/fuga_double_relay_switch.json

The PR adds the the switch which is also supported in Phoscon App.
(code was from December was forgotten in a GIT stash)

DDF Wiser LK FUGA 4 button battery switch

---

tuya.cpp

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4693
Model id : _TZE200_aycxwiau

Fix working mode for the Tuya sensor from Woox

---

devices/sengled/e1c-nb7.json

Add sengled e1c-nb7

---

general.xml

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5459
Description is in french, but I think this device is only used by them.

Fix some Clusters descriptions, Add LiXee Cluster

---

devices/wiser/socket-outlet-double-16A-connected

Add support to Power and consumption report

Add support to Wiser socket-outlet-double-16A-connected

---

general.xml

- 0x0102 - Motion cool off time:
Time in seconds when RTCGQ13LM sets motion to false if no further motion has been detected
- 0x0114 - TVOC unit configuration:
0 -> mg/m³ + °C, 1 -> mg/m³ + °F, 16 -> ppb + °C, 17 -> ppb + °F

Add further Xiaomi specific attributes to general.xml

---

de_web_plugin.cpp

If a long press a side button is aborted too early, this could have locked up top/bottom buttons ON/OFF commands until pressing a second time. The PR checks the timestamp to verify that previous command id 0x09 is part of a long press sequence.

Ikea Styrbar improve top/side buttons detection

---

button_maps.json
devices/ubisys/s2r_5602.json

Based on https://forum.phoscon.de/t/ubisyd1-s2-c4-button-problems/1246/11

DDF add ubisys S2-R (5602)

---

database.cpp
de_web_plugin.cpp
devices/generic/items/state_pressure_item.json
devices/xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json

Adds the respective DDF and removes legacy code.

Add DDF for Xiaomi Aqara temp/hum/press sensor WSDCGQ11LM

---

bindings.cpp
de_web_plugin.cpp
devices/develco/heszb-120_heat_detector.json
devices/frient/heszb-120_heat_detector.json
light_node.cpp
power_configuration.cpp

Adds the respective DDF and removes legacy code.

Add DDF for Develco/frient heat detector HESZB-120

---

rest_schedules.cpp

This should fix #5787. Feel free to edit or let me know if I should change something. I haven't been programming C++ for 20 years. Thanks.

Fixed REST response when setting a schedule's localtime attribute

---

devices/wiser/smart-plug-single-16A.json

fixes #5297
Done with the GUI, had to setup X11 forwarding for it. Gonna test it around by using/monitoring first, i only had plug turn itself off once for some reason.

DDF file for Shneider Electric Wiser Plug 16A

---

devices/danfoss/ally_temp_hum_sensor.json

It's in fact a Tuya device, draw your conclusions.
```
"142": {
"config": {
"battery": null,
"offset": 0,
"on": true,
},
"etag": "794bc9c5a961d9c3d212209de6a12027",
"lastseen": "2022-03-11T21:20Z",
"manufacturername": "_TZ3000_mxzo5rhf",
"modelid": "TS0201",
"name": "Temperature 142",
"state": {
"lastupdated": "2022-03-11T21:20:35.101",
"temperature": 2015
},
"type": "ZHATemperature",
"uniqueid": "a4:c1:38:1a:ca:6e:f2:14-01-0402"
},
"143": {
"config": {
"battery": null,
"offset": 0,
"on": true,
},
"etag": "4019b9e043d7b867ee107a5725e147b4",
"lastseen": "2022-03-11T21:20Z",
"manufacturername": "_TZ3000_mxzo5rhf",
"modelid": "TS0201",
"name": "Humidity 143",
"state": {
"humidity": 2690,
"lastupdated": …
```

Add DDF for Danfoss Ally temp./hum. sensor

---

air_quality.cpp
bindings.cpp
de_web_plugin.cpp
devices/develco/hmszb-110_temp_hum_sensor.json
devices/frient/hmszb-110_temp_hum_sensor.json
electrical_measurement.cpp
power_configuration.cpp

Adds DDF and removes develco/frient related legacy code.

Add DDF for Develco/frient temp/hum sensor HMSZB-110

---

devices/frient/kepzb-110_keypad.json
devices/generic/items/state_action_item.json
devices/generic/items/state_charging_item.json
devices/generic/items/state_panel_item.json

No functional change only fixes the documentation generation.

DDF cleanup Develco/frient KEPZB-110, add missing items for docs

---

devices/generic/constants.json
devices/generic/items/config_lock_item.json
devices/generic/items/state_lockstate.json
devices/generic/subdevices/door_lock.json

Just to be sure don't forget missing files in a future merge.
With the help of @ZeppDK will be probably a future PR for DDF for doorlock, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870

Add missing files for DDF and doorlock

---

devices/tuya/_TZ3000_d16y6col_water_sensor.json

Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5911

DDF : Tuya water sensor _TZ3000_d16y6col

---

de_web_plugin.cpp
devices/xiaomi/xiaomi_wsdcgq01lm_temp_hum_sensor.json

Device not new but now ported from C++ to DDF.

DDF add Xiaomi temperature/humidity sensor (WSDCGQ01LM)

---

devices/blitzwolf/bw_shp13_smart_plug.json

There are a few occurrences of TS0121 in the C++ code, not removing them yet since they might be used by other Tuya based devices.

DDF add Blitzwolf BW-SHP13 (_TZ3000_g5xawfcq)

---

rest_devices.cpp

Filter button events for existing endpoints with references in the button map.
Needed for switches where the button map contains entries for multiple models with different amount of buttons (e.g. sunricher 2/4/8 button switches).

Button event introspection return only availale buttons

---

de_web_plugin.cpp

If a device only contains one sensor like ZHASwitch, skip modelid and manufacturer
name checks to find a better sensor.
The button_maps.json contain a mode field which may or may not be set properly in
a sensor. The default was ModeTwoGroups and now is ModeScenes due another PR.
During initial button map fetch check if the complete button map only uses one mode
and correct it in the sensor.mode if needed.

Button handler skip some modelid checks; improve sensor.mode

---

button_maps.json
devices/wiser/fuga_dimmer_switch.json
devices/wiser/fuga_double_relay_switch.json

Add DDFs describing button events and bindings for LK FUGA Wiser Double Relay and Dimmer Switches.

Extend functionality of LK FUGA Wiser Switch devices

---

devices/develco/moszb-140_motion_sensor.json
devices/frient/moszb-140_motion_sensor.json
rest_sensors.cpp

Enable setting `config/delay` on IAS presence sensor for MOSZB-140

---

devices/blitzwolf/bw_shp15_smart_plug.json

Also correct BW-SHP13 consumption calculation.

DDF add Blitzwolf BW-SHP15 smart plug

---

devices/tuya/rh3040_motion_sensor.json

Support versions:
- TUYATEC-zn9wyqtr
- TUYATEC-lakq7nse
- TUYATEC-53o41joc

DDF correct Tuya RH3040 motion sensor

---

devices/sinope/sp2610zb_smart_switch.json
devices/sinope/th1124zb.json

Using eval function to get right values

Add DDF for Sinope sp2610zb smart plug and TH1124ZB Thermostat

---

devices/xiaomi/xiaomi_gzcgq01lm_light_sensor.json
devices/xiaomi/xiaomi_wsdcgq01lm_temp_hum_sensor.json
devices/xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json

Cleanup various smaller issues, like proper swversion, reporting and awake handling.

DDF improve Xiaomi GZCGQ01LM, WSDCGQ01LM and WSDCGQ11LM

---

device_access_fn.cpp

The `attr.setNumericValue()` doesn't play well with `attr.toVariant()` yet.

Fix DA Tuya handler exposing received values to JS

---

devices/woox/woox_r7060_ts0101.json

DDF for WOOX R7060 (TS0101) smart garden irrigation control device with working battery readings.

Add DDF: WOOX R7060 smart garden irrigation control

---

devices/sambit/AV201021C_door_sensor.json

Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5992

Add DDF for SMaBiT Door sensor AV2010/21C

---

devices/generic/illuminance_cluster/lux_to_lightlevel.js
devices/generic/items/state_dark_item.json
devices/generic/items/state_daylight_item.json
devices/generic/items/state_lightlevel_item.json
devices/generic/items/state_lux_item.json
devices/generic/items/state_presence_item.json
devices/xiaomi/xiaomi_rtcgqq11lm_presence_sensor.json

Adds respective DDF, no legacy code to remove.

Add DDF for Xiaomi presence sensor lumi.sensor_motion.aq2 (RTCGQ11LM)

---

devices/tuya/_TZ3000_ksw8qtmt_plug_nous_a1z.json

Nothing special, just one more https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5917

Add DDF for Nous A1Z plug

---

devices/sonoff/zbmini-l_relay.json
devices/wiser/fuga_socket_outlet.json

With the @ads1230 help.
Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5763
Edit:
Switch  the LK wiser Outlet from Bronze to gold (another test ok here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6093)

Add DDF for ZBMINI-L Relay

---

devices/ikea/tredansen_block-out_cellul_blind.json

DDF for IKEA TREDANSEN

---

devices/ikea/tredansen_block-out_cellul_blind.json

Took the liberty to do some finetuning:
- Removed the binding for SW Build ID on basic cluster
- Removed the binding for on/off on on/off cluster (non-existent)
- Prevent some unnecessary reads and code iterations

Optimize Ikea Tredansen DDF

---

devices/generic/items/config_resetpresence_item.json
devices/xiaomi/xiaomi_rtczcgq11lm_fp1_presence_sensor.json

Adds the missing file and amends refresh interval for `swversion` of Aqara FP1 presence sensor.

Add missing json file for resource item `config/resetpresence`

---

database.cpp
de_web_plugin.cpp
devices/xiaomi/xiaomi_ws-euk01_h1_switch.json
devices/xiaomi/xiaomi_ws-euk02_h1_switch.json

- Adds the respective DDFs and removes the associated legacy code
- Prevent ghost button events for Aqara H1 switch series

Add DDF for Aqara H1 switches w/o neutral WS-EUK01/WS-EUK02

---

devices/sengled/e1c-nb7.json

Fixed consumption reporting for Sengled E1C-NB7

---

device_js/device_js.cpp
device_js/device_js_wrappers.cpp
device_js/device_js_wrappers.h

Needed on older Qt versions which don't provide these functions.

Javascript add Math.log10 and String.padStart polyfills

---

devices/generic/constants.json
devices/generic/subdevices/waterleak_sensor.json
devices/linkind/001082_water_leak_sensor.json

Add DDF for Zigbee Water Leak Sensor A001082

---

devices/_TZE200_2wg5qrjy_valve.json

DDF, add support for Royal Gardineer - ZX-7155-675

---

bindings.cpp
database.cpp
de_web_plugin.cpp
devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
devices/xiaomi/xiaomi_zncz12lm_smart_plug.json
electrical_measurement.cpp

Adds the DDFs for Aqara SP-EUC01 and ZNCZ12LM smart plug while removing the respective legacy code

Add DDFs for Aqara SP-EUC01 and ZNCZ12LM smart plug

---

bindings.cpp
database.cpp
de_web_plugin.cpp
devices/immax/07046L_keyfob.json
devices/immax/07048L_smart_plug.json

Add DDF and remove respective legacy code.

Add DDF for Immax Neo Keyfob 07046L

---

bindings.cpp
de_web_plugin.cpp
devices/xiaomi/xiaomi_gzcgq01lm_light_sensor.json
power_configuration.cpp

- Updates the FW version string
- Removes legacy device code

Update FW version string for Mijia Light Sensor GZCGQ01LM

---

rest_sensors.cpp

`sensor` was dereferenced without checking for null.

Fix SEGV in PUT sensor/<id>/config

---

de_web_plugin.cpp

While Permit Join is enabled, always wait until manufacturer name and modelid are queried by the Device code. This happens also for non DDF devices.
For lights and sensors which have a DDF, skip legacy code for creating resources, when the DDF status is enabled. This fixes creation of invalid lights.
Note: This change is a bit bold and may show a few missing parts in DDFs but, beside the mentioned fix also speeds up DDF pairing.

Skip legacy code when pairing via DDF

---

button_maps.json
devices/ubisys/j1r_5602.json

Copy paste from J1 (5502), treat as separate DDFs for now.

Add DDF for ubisys J1-R (5602)

---

devices/3A-Nue/lxn59-1s7lx1.0.json

Add DDF file for smart socket based on Nue/3A LXN59-1S7LX1.0

DDF : Create lxn59-1s7lx1.0.json for Smart Socket based on this hardware

---

devices/tuya/_TZ3000_typdpbpg_smart_plug_eu

Add support for [Tuya smart plug EU ](https://zigbee.blakadder.com/Tuya_TS011F.html) with ID  _TZ3000_typdpbpg.

Add DDF _TZ3000_typdpbpg_smart_plug_eu

---

rest_groups.cpp

This is a naiv workaround for gledopto extended color lights, as described in #2364 
Gledopto extended color lights support setting color either as temperature `ct` or as `xy`.
Only if colors are set via `ct` will white leds be used in devices that support them. Otherwise, RGB leds are used.
This is problematic with scenes that (are supposed to) recall colors as temperatures.
Tested with a gledopto lightstrip, `GL-MC-001`, `Extended color light`

workaround for gledopto lights to recall scenes with ct

---

devices/frient/kepzb-110_keypad.json
devices/gledopto/gl-sd-002_switch.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5849
This device is a "light" device but an End Device.

DDF : Add support for GLEDOPTO Zigbee Mini Switch Modul

---

devices/linkind/ZBT-CCTLight-M3500107.json

DDF: Linkind 4.8W GU10 Bulb Dimmable & Tunable

---

device.cpp

The error counter is `16` to not jump to conclusions too quickly. Prior to this PR DDF based devices could be stuck in the reachable: true state for a long time and needless APS requests were made.

Mark devices as not reachable after repeated APS confirm errors

---

devices/sinope/th1124zb.json

Adding Pi Heating demand and unoccupyheatingsetpoint like on Stelpro's thermostat. Adjusting some reports timer.

Update th1124zb.json to add item already used on other thermostats

---

devices/aubess/aubess_muti_sensor_TZ3000_bguser20

DDF for Aubess Multi Sensor TS0201 _TZ3000_bguser2

---

devices/generic/constants.json
devices/generic/subdevices/alarm_sensor.json

DDF add generic ZHAAlarm sub device json

---

devices/3A-Nue/LXT56-LS27LX1.7.json

Aka "3A Smart Home DE  - LXT56-LS27LX1.7" https://forum.phoscon.de/t/ddf-for-zemismart-3a125-15-led-strip-controller/2554

Add DDF for Zemismart 3A12S-15 led strip controller

---

devices/3A-Nue/LXT56-LS27LX1.7.json

Deleting $TYPE_ON_OFF_LIGHT part with same uuid that was here by mistake. Thanks to @Smanar for pointing this.

Fix DDF of Zemismart 3A12S-15 led strip controller

---

devices/wiser/fuga_socket_outlet.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6440
- Product name: MEG2380-0325
- Manufacturer: Schneider Electric
- Model identifier: SOCKET/OUTLET/1

DDF for Merten Wiser socket outlet SOCKET/OUTLET/1

---

button_maps.json
devices/xiaomi/xiaomi_qbkg03lm_switch.json
devices/xiaomi/xiaomi_qbkg04lm_switch.json

Adds the DDF for single and dual rocker switch as well as the respective button map.

Add DDFs for Aqara switches QBKG03LM and QBKG04LM

---

devices/innr/sp_234.json

Fixes #5256 
DDF for Innr SP-234 
This supercedes #5260 which can be closed

Add Innr SP-234 based on sp120

---

devices/dresden_elektronik/hive.json

The light is a battery powered `rxOnWhenIdle=true` end device.
https://phoscon.de/hive

DDF for Phoscon Hive

---

devices/owon/PIR313-E_sensor_multi.json

With the @Idaho947 help, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5929

DDF add support for Owon PIR313-E

---

devices/aubess/aubess_multi_sensor_TZ3000_bguser20.json

Update and rename aubess_multi_sensor_TZ3000_bguser20

---

devices/xiaomi/xiaomi_gzcgq11lm_light_sensor.json

Adds the respective DDF, already confirmed working by the requestor of the device support request.

Add DDF for Aqara T1 Light Sensor GZCGQ11LM

---

devices/_TZE200_TS0601_humidity_temp.json

This device ([link](https://www.aliexpress.com/item/1005004116638127.html)) and another clone. See discussion here (#6535)

Add DDF: Tuya Multi Sensor Temp./Humidity (_TZE200_znbl8dj5, _TZE200_qoy0ekbd)

---

devices/philips/rom001_smart_button.json

Hue smart button revisited... again.

---

devices/tuya/_TZ3000_cehuw1lw_smartplug_EU.json

DDF for Tuya smart plug (_TZ3000_cehuw1lw)

---

devices/tuya/_TZE200_dq1mfjug_smoke_sensor.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6515
It use tuya cluster)

DDF add support for tuya smoke sensor

---

devices/lixee/zlinky_tic_histo_tri_hphc.json

The DDF status is "Draft" and need to be enabled according the user contract.

DDF, add the mode historique+HPHC+triphase for the Zlinky

---

general.xml

Inspired by [this](https://github.com/YuhangZho/EmberZNet5.3.0-GA/blob/ce8eb024f2ea536832a0d849c3808c6f21131155/em35x/tool/appbuilder/sengled_cluster.xml) 0xFC01 to 0XFC04
Replace conflicting #6450

Adding some SENGLED specific cluster definitions

---

devices/Jasco-GE/GE45856_wall_switch.json

From request https://forum.phoscon.de/t/ge-alias-jasco-45856-wall-switch/2650

Add DDF for GE 45856

---

devices/sengled/e1d-g73.json

Works ok now for my Sengled sensors.

DDF for Senged e1d g73 door and window sensor

---

devices/tuya/ts0202_presence_sensor.json

Added manufacturer name of another clone ("_TZ3040_6ygjfyll")

DDF add variant to Tuya TS0202 presence sensor (_TZ3040_6ygjfyll)

---

devices/frient/splzb-131_smart_plug.json

Nothing speciel, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6628

DDF add clone for frient plug

---

devices/ouellet/OTH4000-ZB

Add support for Ouellet  OTH4000-ZB thermostat, based on Sinope TH1124ZB

Add DDF for OTH4000-ZB thermostat

---

general.xml

Completing some Sinope specific thermostat attributes in ZCLDB

---

devices/tuya/_TZE200_3towulqd_motion_lux_sensor.json

- Product name: Tuya Luminance Motion Sensor Model ZG-204ZL
- Manufacturer: _TZE200_3towulqd
The convertion are probably wrong, but values are here, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6158

DDF for Tuya Luminance Motion Sensor Model ZG-204ZL

---

devices/ikea/fyrtur_block-out_roller_blind.json

As I don't own the device, it should ideally be tested before getting merged.

DDF for Ikea Fyrtur roller blind

---

devices/nedis/nedis_zbsm10wt_motion_sensor.json

Another tuya clone, but this brand have its own folder, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6495
- Product name: Nedis Zigbee motion sensor ZBSM10WT
- Manufacturer: _TZ3000_nss8amz9
- Model identifier: TS0202

DDF for Nedis Zigbee motion sensor ZBSM10WT

---

devices/wiser/fuga_socket_outlet.json
general.xml

Add attributes for manufacturer specific cluster, containing LED indication configuration and update the DDF:
- Correct refresh intervalls
- Add consumption reporting
- Amend power reporting

Update DDF for Schneider connected socket outlet devices

---

devices/tuya/_TZ3000_n2egfsli_door_sensor.json

Merging #6598 request to existing DDF

Update _TZ3000_n2egfsli_door_sensor.json to add another sensor

---

devices/sonoff/snzb-02-multisensor.json

Add support forSNZB-02D SonOff multisensor. See PR #6697

Add support for SNZB-02D SonOff multisensor

---

devices/bosch/plug_compact.json

Add DDF for Bosch Plug compact EU BSP-FZ2

---

devices/robb_smarrt/rob_200-017-0_plug.json

Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6676

DDf add support for Robb Smarrt On/Off ROB_200-017-0

---

devices/sengled/E21-N1EA

Add DDF for Sengled Smart Light Bulb E21-N1EA

---

devices/tuya/ZY-M100_human_breathing_presence.json

Adding precision on Far detection sensitivity configuration and fixing conversion on errorcode reporting (see #6517 )

Update ZY-M100 DDF (fix & adding precision - breaking change for triggerdistance)

---

devices/third_reality/3RSP02028BZ_smart_plug.json

- Product name: Smart Plug Gen2
- Manufacturer: Third Reality, Inc
- Model identifier: 3RSP02028BZ
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6747

DDF for Third Reality Smart Plug Gen2

---

devices/tuya/_TZ3000_txpirhfq_1gang_module.json

- Product name: TMZ-02 Mini / Tmz02L-16A-W
- Manufacturer: _TZ3000_txpirhfq
- Model identifier: TS0011
Have added 2 clone, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6762

DDf, add support for TMZ-02 Mini a.k.a Tmz02L-16A-W

---

devices/tuya/_TZE200_TS0601_mmWave_Radar.json

Including  Aubess Human Presence Sensor mmWave _TZE200_v6ossqfy #6742

Add DDF for some 2.4GHz mmWave radar

---

devices/tuya/_TZE200_m9skfctm_smoke_detector.json

Create DDF for Tuya Photoelectric Smoke Detector _TZE200_m9skfctm Description is in #6734

Add DDF for Tuya Photoelectric Smoke Detector _TZE200_m9skfctm

---

devices/moes/Moes_TZ3000_TS0201_temp_hum_with_LCD.json

Add support for MOES _TZ3000_itnrsufe temp&hum sensor, see #6645

Update DDF to add support for MOES _TZ3000_itnrsufe

---

device_access_fn.cpp
devices/ikea/vindstyrka_air_quality_sensor.json
general.xml

IKEA Vindstyrka

---

devices/tuya/TS0043_3gang_remote.json

Fix TS0043_3gang_remote

---

devices/tuya/_TZ3000_n2egfsli_door_sensor.json

Fix DDF _TZ3000_au1rjicn manufacturer name typo

---

button_maps.json

Fixed Buttonevents 1001 and 1003 for Dresden Elektronik Scene Switch

Fix Dresden Elektronik Scene Switch long press button events

---

devices/xiaomi/xiaomi_lumi.relay.c2acn01.json
devices/xiaomi/xiaomi_lumi.switch.n0agl1_switch.json

Long story, it seem this device have issues
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6512
https://forum.phoscon.de/t/device-appear-in-deconz-but-not-in-phoscon/3298
Solved by this DDF

DDF, improve support for Xiaomi Aqara relay controller lumi.relay.c2acn01

---

button_maps.json

Bug fix: support for SYMFONISK controller broken.

---

devices/dresden_elektronik/hive.json

Update hive.json attr/powerup instead of config/powerup

---

read_files.cpp

Note it was not actually triggered with the shipped DDFs.

Fix potential SEGV in debug print

---

general.xml

Needed for some vibration sensors.

ZCLDB add IAS zone sensitivity levels attributes

---

devices/moes/Moes_TZ3000_TS0012_Battery_2_gang_switches.json

DDF for Moes 2-gang push button switch (_TZ3000_18ejxno0 / TS0012)

---

devices/xiaomi/xiaomi_rtcgq13lm_presence_sensor.json

Add DDF for Aqara high precision motion sensor RTCGQ13LM

---

devices/ikea/starkvind_air_purifier.json

- Add OTAU cluster to ZHAAirPurifier fingerprint;
- Change `uniqueid` and fingerprint for ZHAAirQuality resource, see #6848.
- Reformat.

Change DDF for STARKVIND

---

devices/xiaomi/xiaomi_mccgq11lm_openclose_sensor.json

Add DDF for Aqara open/close sensor MCCGQ11LM

---

devices/generic/items/config_tuya_unlock_item.json
resource.cpp
resource.h

To make easier the integration for device that need the tuya unlock sequence.

Add support for Tuya unlock item.

---

devices/generic/items/config_configured_item.json

Used by alarm systems and daylight sensor.

Add DDF generic item config/configured

---

CONTRIBUTING.md

A few thoughts on how to streamline PR titles and use tags.

Add initial contribution guidelines for PR titles

---

button_maps.json
devices/xiaomi/xiaomi_wxkg20lm_mini_switch.json

Support for Aqara mini switch WXKG20LM
Fixes #6818

DDF for Aqara mini switch WXKG20LM

---

devices/generic/constants.json
devices/generic/items/state_moisture_item.json
devices/generic/subdevices/moisture_sensor.json
devices/tuya/_TZE200_myd45weu_soil_sensor.json

Adding BTW some generic json fles for moisture as suggested in #6731 
Thus this close #6731 
Thanks to everybody involved in this process ;-)

DDF for Tuya soil sensor (_TZE200_myd45weu / TS0601)

---

devices/xfinity/THK1_keypad.json

Fix #5714 
BTW add DDF for legacy supported XHK1-UE Xfinity keypad

DDF for Technicolor XHK1-TC Keypad

---

devices/sonoff/zbmini-l_relay.json

Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6671

DDF for Sonoff ZBMINIL2

---

devices/blitzwolf/bw_is4_multisensor.json

https://zigbee.blakadder.com/BlitzWolf_BW-IS4.html

DDF for Blitzwolf BW-IS4 multisensor (_TYZB01_hjsgdkfl)

---

devices/tuya/_TZE200_myd45weu_soil_sensor.json

Change reused "config/configured" item by new "config/tuya_unlock" and add "lowbattery" forgotten in previous PR #6842 
Definitely close #6731

Update Tuya Soil Sensor DDF

---

devices/tuya/_TZE200_m9skfctm_smoke_detector.json

Add Qaynn _TZE200_vzekyi4c Tuya clone

Add Qaynn smoke detector to existing DDF

---

devices/tuya/_TZ3000__TS0207_range_extender.json

@Smanar opened the door with PR #6793 ;-)

DDF for various Tuya based range extenders

---

devices/tuya/_TZ3000_TS0207_water_leak_sensor.json

DDF for various TS0207 Tuya based water leak sensors

---

devices/neo/NAS-WR01B_TS011F.json

Device: TZ3000
add device manufacturname: fgwhjm9j

DDF for further NEO NAS-WR01B smart plugs

---

general.xml

Update to R8 Zigbee specification

Update ZCLDB <cluster id="0x0000" name="Basic">

---

devices/tuya/ts0202_presence_sensor.json

DDF update for various ts0202 presence sensors.
Guess will close #6912

DDF update for various ts0202 presence sensors

---

devices/moes/Moes_MS-104BZ_wired_switch_2_gangs.json

DDF add support for Moes MS-104BZ

---

devices/ikea/tradfri_bulb_e14_ws_opal_600lm.json

DDF for Tradfri bulb E14 WS Opal 600 lm

DDF for Tradfri bulb E14 WS Opal 600 lm

---

devices/ikea/tradfri_bulb_e27_ws_opal_1000lm.json

New DDF for Ikea E27 WS Opal 1000lm

DDF for Tradfri bulb e27 ws opal 1000lm

---

devices/ikea/tradfri_bulb_e27_w_opal_1000lm.json

New DDF file for Ikea E27 W Opal 100lm. Different from WS Opal 1000lm.
#6709

DDF for Tradfri bulb e27 w opal 1000lm

---

devices/generic/items/config_volume_item.json

Create .json for already existing item

Create missing config_volume_item.json

---

devices/generic/items/config_melody_item.json

Create ,json for already existing item

Create missing config_melody_item.json

---

general.xml

Update 0xff01 Sinopé specific cluster

Update Sinopé specific cluster in ZCLDB

---

devices/3A-Nue/lxt56-ls27lx1.7.json
devices/Jasco-GE/GE45856_wall_switch.json
devices/computime-salus/ss909zb_temp_sensor.json
devices/heiman/hs2wd-e_smart_siren.json
devices/ouellet/OTH4000-ZB
devices/sengled/e1c-nb7.json
devices/sengled/e1d-g73.json
devices/sinope/th1124zb.json
devices/tuya/ZY-M100_human_breathing_presence.json
devices/tuya/_TZE200_m9skfctm_smoke_detector.json

Pass various DDF that I used for a while from Silver state to Gold

Change various DDF that exists for a while from Silver level to Gold

---

devices/ikea/gu10_ws_400lm_light.json

Adapted version "Bri move with on/off" and "on/off with effect" included.
#6709

DDF update for Tradfri gu10 ws 400lm

---

devices/tuya/_TZE200_TS0601_humidity_temp.json

DDF add ZTH01 & ZTH02 temp and humidity sensor

---

devices/dresden_elektronik/hive.json

Fix DDF for Hive - take 2

---

devices/tesla/TSL-SEN-TAH_multi_sensor.json

DDF for Tesla TSL-SEN-TAH multi sensor

---

devices/xiaomi/xiaomi_rtcgq13lm_presence_sensor.json

"None" -> "none"
Reported by the validator.

Fix typo in Xiaomi RTCGQ13LM DDF

---

devices/konke/3AFE280100510001_battery_switch.json

-    Product name: Kit Pro Multi Function Button IC 23777-KPKEY
-    Manufacturer: Konke.
-    Model identifier: 3AFE280100510001
-    Device type : - Switch
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3339

DDF for Konke Kit Pro Multi Function Button IC 23777-KPKEY

---

devices/ikea/tradfri_bulb_e27_ww_806lm.json
devices/tradfri_bulb_e27_ww_806lm.json

New DDF for Ikea E27 WW 806lm
#6709

DDF for Tradfri bulb e27 ww 806lm

---

devices/ikea/tradfribulbe27wsglobeopal1055lm.json

Added capabilities Move with onoff and Off with effect

DDF update for Tradfri bulb e27 ws globe opal 1055lm

---

devices/tuya/_TZ3000_TS0011_1gang_switch_module.json

Fix #6940 6940 and close #4896

DDF - Add Teekar Zigbee light switch support

---

general.xml

Complete general.xml to add Concentration Measurement clusters as Zigbee Cluster Library Specification Revision 8 and other measurement updates.

Update ZCLDB to add/update some Measurement clusters

---

general.xml

Completion of some Tuya specific clusters or attributes

Update Tuya specific definitions in ZCLDB

---

devices/tuya/ZY-M100_human_breathing_presence.json

DDF Add clones to ZY-M100 existing DDF

DDF add clones of Tuya  ZY-M100 presence sensor

---

devices/lidl/hg08673.json

DDF HG08673 LIDL SilverCrest smart plug with monitoring

---

general.xml

Updated attribute names, descriptions and values.

Schneider specific cluster/attribute updates in general.xml

---

devices/ikea/tradfribulbe14wscandleopal470lm.json

Add DDF for Tradfri bulb e14 ws candle opal 470lm

Add DDF for Tradfri bulb e14 ws candle opal 470lm

---

button_maps.json
devices/lds/ZBT-DIMSwitch-D0000_remote.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6939
-  "manufacturername": "LDS"
-  "modelid": "ZBT-DIMSwitch-D0000"
-  "product": "LDS battery switch"

DDF, add support for LDS battery switch

---

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json

Rename file because it's not only for _TZ3000_yd2e749y

DDF Rename _TZ3000_yd2e749y_temp_hum_sensor.json

---

devices/_TYZB01_SM0201_temp_hum_sensor.json

Fix Tuya SM0201 config.battery refresh.interval

---

devices/xiaomi/xiaomi_lumi.light.aqcn02_TunableWhite_Bulb.json

Fix Xiaomi tunable white bulb (aqcn02) use cap/color/ct/[min | max]

---

devices/ubisys/ld6.json

Fix ubisys LD6 use cap/color/ct/[min | max]

---

devices/mli/tint_gu10_spot_zbt-colortemperature.json

Fix Tint GU10 spot use cap/color/*

---

devices/ubisys/ld6.json

Fix ubisys LD6 use cap/color/*

---

devices/dresden_elektronik/fls_pp3.json

Fix dresden elektronik FLS-PP lp use cap/color/*

---

devices/siglis/zigfred_uno_wired_switch.json

Fix Zigfred Uno use cap/color/* and poll intervals

---

devices/linkind/ZBT-CCTLight-M3500107.json

Fix Linkind ZBT-CCTLight-M3500107 use cap/color/* and fix poll interval

---

devices/linkind/ZBT-CCTLight-D0106.json

Fix Linkind ZBT-CCTLight-D0106 use cap/color/* and fix poll interval

---

devices/ikea/e27_cws_opal_600lm_light.json

Reported by validator.
The DDF status is still Bronze should be tested again and promoted to Gold.

Fix Ikea E27 CWS Opal 600lm use cap/color/* and code cleanup

---

devices/sengled/E12-N1E.json

Fix Sengled E12-N1 use cap/color/*

---

devices/siglis/zigfred_plus_wired_switch.json

Fix Zigfred Plus use cap/color/*

---

CMakeLists.txt
crypto/scrypt.cpp

Needed for Install Codes and alarm systems.

CMake support locating OpenSSL

---

devices/tuya/_TZ3000_TS011F_PowerStrip.json

DDF add support for TZ3000_air9m6af and _TZ3000_bppxj3sf from LELLKI

---

devices/osram/cla60_tw.json

Osram CLA60_TW bulb. Tested and works on my side.

DDF for Osram CLA60 TW OSRAM

---

devices/osram/classic_a60_tw.json

Osram Classic A60_TW bulb. Tested and works on my side.

DDF for Osram Classic A60 TW

---

devices/osram/classic_a60_rgbw.json

Osram Classic A60_RGBW bulb. Tested and works on my side.

DDF for Osram Classic A60 RGBW

---

devices/osram/classic_b40_tw.json

Osram Classic B40_TW bulb. Tested and works on my side.

DDF for Osram Classic B40 TW

---

devices/tuya/_TZE204_sxm7l9xa_mmwave_radar.json

DDF add support for _TZE204_sxm7l9xa mmWave radar sensor

---

button_maps.json
de_web_plugin.cpp
devices/adeo/ldsenk09_keyfob.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6973
- Product name: smart remote control Lexman Leroy Merlin
- Manufacturer: Adeo
- Model identifier: LDSENK09

DDF add support for the Adeo LDSENK09 Key FOB 4 buttons

---

devices/generic/constants.json
devices/generic/subdevices/carbondioxide_sensor.json
devices/generic/subdevices/formaldehyde_sensor.json
devices/generic/subdevices/particulatematter_sensor.json
devices/tuya/_TZE200_dwcarsat_air_sensor.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673
Create 6 sensors :
- ZHAHumidity
- ZHAtemperature
- ZHAAirquality
- ZHAFormaldehyde
- ZHACarbonDioxide
- ZHAParticulateMatter

DDF update the Tuya air quality sensor _TZE200_dwcarsat with "state/measured_value"

---

devices/tuya/_TZE204_sxm7l9xa_mmwave_radar.json

change dpid for writing to triggerdistance to 107 (same as parsing/reading dpid)

Enable changing trigger distance of Tuya presence sensor (_TZE204_sxm7l9xa)

---

devices/ubisys/s1_5501_s1r_5601.json

Identical to S1 (5501) so include in respective DDF.

DDF for ubisys S1-R (5601)

---

devices/ubisys/d1_5503_d1r_5603.json

Identical to D1 (5503) so include in respective DDF.

DDF for ubisys D1-R (5603)

---

de_web_plugin.cpp
poll_manager.cpp

Returned data type will be `int64_t` instead of `time_t`.

Prepare for deconz-lib deCONZ::Attribute::lastRead() change

---

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json

Support the "0s1izerx" variant of the TS0201 temperature/humidity sensor

DDF for Tuya temperature / humidity sensor (_TZ3000_0s1izerx) (#7113)

---

devices/danfoss/etrv0100_thermostat.json
devices/generic/constants.json
devices/generic/subdevices/time.json

[subdevice] Add ZHATime type

---

devices/generic/constants.json
devices/generic/subdevices/level_control_switch.json
devices/legrand/cable_outlet.json

[subdevice] Add type Level control switch

---

devices/generic/subdevices/alarm_sensor.json
devices/heiman/hs2wd-e_smart_siren.json
devices/lixee/zlinky_tic_histo_tri_hphc.json
devices/lixee/zlinky_tic_historique_mono_base.json
devices/lixee/zlinky_tic_historique_mono_hphc.json
devices/lixee/zlinky_tic_standard_mono_base.json
devices/lixee/zlinky_tic_standard_tri_hphc.json

[subdevice] items_optional for ZHAAlarm

---

devices/generic/subdevices/onoff_light.json

Part 14 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for $TYPE_ON_OFF_LIGHT

---

devices/generic/subdevices/power_sensor.json

Part 16 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for ZHAPower

---

devices/neo/NAS-WR01B_TS011F.json

Device: TZ3000
add device manufacturname: waho4jtj

DDF for further NEO NAS-WR01B smart plugs (_TZ3000_waho4jtj)

---

devices/tuya/_TZ3000_hkkkuk7k_mini_switch.json

DDF add support for ROVF (TMZ02L-16A-B2) Mini Switch

---

button_maps.json
devices/ikea/rodret_remote_control.json

Added DDF for Ikea RODRET Remote Control as sugested in Issue #7147

DDF for Ikea RODRET Remote Control

---

crypto/scrypt.cpp

When OpenSSL 1.x library is used, the wrapper code worked only partially.
Beside missing functions also EVP_PKEY_OP_DERIVE value has changed between versions.
Reported in forum: https://forum.phoscon.de/t/alarm-systems-not-working-anymore/3872/4

Fix alarm systems set code

---

devices/frient/kepzb-110_keypad.json
devices/generic/constants.json
devices/generic/subdevices/ancillary_control.json
devices/xfinity/THK1_keypad.json

[subdevice] Add type ZHAAncillaryControl

---

air_quality.cpp

Also don't need to include `de_web_plugin.h` header.

Fix air quality printf format warning

---

devices/generic/subdevices/extended_color_light.json

Part 13 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for Extended color light

---

devices/generic/subdevices/dimmable_light.json

Part 10 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for Dimmable light

---

devices/generic/subdevices/color_temperature_light.json

Part 9 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for Color temperature light

---

devices/generic/subdevices/color_light.json

Part 8 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] for Color light

---

devices/generic/subdevices/airquality_sensor.json

[subdevice] items_optional for ZHAAirQuality

---

devices/generic/subdevices/airpurifier.json

[subdevice] items_optional for ZHAAirPurifier

---

devices/generic/subdevices/thermostat.json

Part 18 of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7155

[subdevice] items_optional for ZHAThermostat

---

rest_configuration.cpp

Did not test it because compile stuff but should be working fine

Update etag when removing user fix #7216

---

devices/frient/moszb-154_motion_sensor.json

So far, similar to the MOSZB-144

Add DDF for frient MOSZB-154 motion sensor pro

---

.github/ISSUE_TEMPLATE/bug_report.yml

Some changes to be a bit more precise

Small adjustments on the bug report issue template

---

devices/philips/light_zb3_C.json
devices/philips/light_zb3_C_festavia.json
devices/philips/light_zb3_C_gradient.json
devices/philips/light_zb3_white.json
devices/philips/light_zb3_white_ambiance.json

Newly detected in DDF validator v2.19.0.

Hue lights: Fix validator errors

---

devices/lidl/hg08673.json

Add support for Lidl HG08673-DK Smart plug _TZ3000_nkcobies in existing hg08673.json DDF

DDF for Lidl Smart Plug HG08673-DK (_TZ3000_nkcobies)

---

devices/namron/5401395_heater.json

DDF for black variant 5401399 of Namron heater

---

devices/tuya/_TZ3000_gzvniqjb_din_rail_switch.json

change to status Gold, for Phoscon App

DDF Gold status for TONGOU TO-Q-SY1-ZT

---

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json

Adding new model id for TS0201 temperature and humidity sensor.
Must solve issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7370

DDF clone for Tuya temperature and humidy sensor (_TZ3000_saiqcn0y)

---

devices/tuya/_TZ3000_ja5osu5g_smart_button.json

DDF Add tuya_unlock to _TZ3000_ja5osu5g moes (tuya) smart button

---

devices/danalock/danalock_v3.json
devices/legrand/cable_outlet.json
devices/tuya/_TZE200_dwcarsat_air_sensor.json
devices/xiaomi/xiaomi_mccgq12lm_t1_openclose_sensor.json
devices/xiaomi/xiaomi_mccgq14lm_e1_openclose_sensor.json

Just added the missing mandatory items.

Fix validation errors

---

devices/tuya/_TZ3210_dse8ogfy_fingerbot.json

DDF, solve DDF validation for the Tuya fingerbot

---

devices/woox/Woox_R7049_Smart_Smoke_Alarm.json

Tuya device, see discussion [here](https://forum.phoscon.de/t/woox-r7049-smoke-detector/4186/3). It works well for me after a few weeks testing, including low battery indication.

DDF for Woox R7049 Smart Smoke Alarm

---

devices/lidl/hg08673.json

Fix LIDL smart plug consumption value multiplier

---

devices/namron/4512765_hum_temp.json

DDF to support Namron S903TH-ZG multisensor

---

devices/sonoff/snzb-02-multisensor.json

Sonoff have aded further variations of the same temp/humidity sensor.
The existing DDF works well with them.

Add the SNZB-02P variant of the sensor to the DDF

---

devices/sonoff/snzb-04_open_close_sensor.json

DDF for Sonoff/zbeacon DS01 open/close sensor

---

devices/ikea/tradfri_bulb_e14_ww_clear_250lm.json

DDF for TRÅDFRI LED bulb E14 250lm warm white clear chandelier

---

de_web_plugin.cpp

Fix generated scene names

---

devices/greeble/jz-rgbw-z01.json

Initial version with polling. The legacy code doesn't seem to like the light much.

DDF for Greeble JZ-RGBW-Z01 light

---

devices/ubisys/s1_5501_s1r_5601.json

Type ON_OFF_PLUGIN_UNIT is wrong and should be ON_OFF_OUTPUT like in other ubisys switches S2, S2r

Use correct type for ubisys S1/S1-R

---

devices/danfoss/etrv0100_thermostat.json

DDF for Popp Smart Thermostat

---

devices/danfoss/etrv0100_thermostat.json

DDF for Hive Radiator Valve

---

devices/danfoss/danfoss_windowopen_state.js
devices/danfoss/etrv0100_thermostat.json

- Use manufacturer specific command via DDF to set temperature
- Use javascript file for generating error strings
- Use lower case for window open states

DDF internal optimizations for Danfoss Ally and derivatives

---

bindings.cpp
devices/develco/hmszb_temp_hum_sensor.json
devices/frient/hmszb_temp_hum_sensor.json

New and identical version of the already supported sensor.

DDF for Develco/frient temperature/humidity sensor HMSZB-120

---

button_maps.json
devices/sonoff/snzb-01p_switch_wireless.json

Product name : Sonoff Button
Manufacturer : Sonoff
Model identifier : SNZB-01P
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7423

DDF for Sonoff SNZB-01P

---

devices/ikea/ormanas_led_strip.json

add basic ddf for ormanas led strip
please reject if this is not the right way

DDF for IKEA Ormanas led strip

---

devices/tuya/_TZB000_42ha4rsc_window_blinds.json

Product name: LIVARNO home Automatik-Verdunkelungsrollo
Manufacturer: _TZB000_42ha4rsc
Model identifier: TS030F
Device type : Please remove all unrelated device types.
Other: Blinds
Discussion: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7197

DDF for LIDL Livarno window blinds (Tuya)

---

devices/osram/plug_01.json

DDF for Osram Plug 01

---

devices/ikea/tradfri_bulb_e14_w_opal_400lm.json

add DDF for IKEA TRADFRI bulb E14 W opal 400lm

DDF for IKEA bulb E14 W opal 400lm

---

devices/xiaomi/xiaomi_mho-c401n_temp_hum_sensor.json

As proposed in #7526. Has been tested working for several days and seems to be good.

DDF for Xiaomi MHO-C401N temperature and humidity sensor

---

devices/tuya/_TZE200_TS0601_humidity_temp.json

Another clone of the TS0601 temperature and humidy sensor. Temperature / humidity and battery are working
[Aliexpress](https://de.aliexpress.com/item/1005005872954258.html)

DDF add clone of Tuya temperature and humidy sensor (TZE200_locansqn)

---

devices/philips/fc03_state.js
devices/philips/light_zll_white_ambiance.json

Bug fix: Hue white ambiance wrong state

---

devices/generic/items/state_hue_item.json

Add default refresh.interval of 5 secs to state/hue item

---

device.cpp

- Make sure items have an actual value by testing via `item->lastSet().isValid()`.
- Skip setting the value if not needed. This under the hood prevents calls to `QDateTime::currentDateTime()`. Which can be expensive than the state machine is cycled through a lot.

Improve ResourceItem::setValue() usage in Device class

---

de_web_plugin.cpp

With the extended logging output it's easier to add new ZGP devices. The FoH detection is relaxed to perhaps detect more variants of the Friends of Hue Outdoor Switch.

More detailed ZGP logging, relax Friends of Hue switch detection

---

devices/xiaomi/xiaomi_sjcgq13lm_e1_wleak_sensor.json

Should be fairly straight forward. Closes #5725

DDF for Aqara E1 Water Leak Sensor SJCGQ13LM

---

devices/xiaomi/xiaomi_wxkg11lm_mini_switch

Xiaomi Aqara wireless switch WXKG11LM:
Log:

DDF for Xiaomi Aqara wireless switch WXKG11LM

---

devices/namron/4512762_open_close_sensor.json

DDF for Namron 4512762 open/close sensor

---

devices/tuya/_TZ3000_TS0011_1gang_switch_module.json
general.xml

Product name : Moes Switch 1 Gang / MOES ZS-SR-EU1-WH-MS ZIGBEE
Manufacturer : _TZ3000_hhiodade
Model identifier : TS0011
Device type to add : Light
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7659

DDF Tuya clone _TZ3000_hhiodade and update general.xml

---

devices/xiaomi/xiaomi_ssm-u01_t1_switch.json

Aqara Single Switch Module T1 (With Neutral):

Fix temperature reporting for Aqara Single Switch Module T1 (With Neutral) SSM-U01

---

devices/sunricher/SR-ZG9030A-MW.json
general.xml

Intersting device I'd love to have here for testing. I'm not too sure if it would make sense to add a ZHASwitch resource. The device has quite some client clusters... Anyway, it should run with the given state.
Closes #7648

DDF for Sunricher Ceiling Mount Microwave Occupancy Sensor SR-ZG9030A-MW

---

devices/tuya/_TZ3000_TS0210_vibration_sensor.json

This merges PR #7705 and PR  #7701

DDF clones for Tuya TS0210 vibration sensors and renamed DDF

---

devices/icasa/ICZB-IW11D.json

Same hardware as Kobold, but different firmware features.

Add DDF for icasa AC Dimmer ICZB-IW11D

---

database.cpp
de_web_plugin_private.h

These don't belong in the plugin class.

Make various database function local to database.cpp

---

devices/namron/4512737_thermostat.json

New Namron Zigbee Touch Thermostat 16A and new model id

DDF clone for Namron Touch thermostat 16A (4512752)

---

rest_configuration.cpp

Update API responses for time config

---

rest_devices.cpp

I know that this API is not implemented but at least return a valid JSON ;)

Fix introspect response

---

devices/moes/Moes_MS-105-M_1_gang_dimmer_module.json
devices/moes/Moes_ZM-105-M_1_gang_dimmer.json
devices/sunricher/SR-ZG9030A-MW.json

The validator does not yet validate script path, I found 3 that was invalid

Fix script paths for DDF files

---

.github/workflows/ci-ddf-store.yml

Add write permission for issues, it's seems needed
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#setting-the-github_token-permissions-for-a-specific-job

Add permissions

---

.github/workflows/ci-ddf-store.yml

Add write all permissions

---

devices/innr/sp_240.json

The older innr plugs already do this, see their files.

Fix consumption value for Innr SP 240

---

devices/adeo/ldsenk02f_plug.json

Product name : Adeo plug 16 A
Manufacturer : Adeo
Model identifier : LDSENK02F
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7834
Nothing special

DDF for ADEO 16 A plug LDSENK02F

---

devices/icasa/ICZB-IW21SW.json

DDF for icasa Zigbee On/Off Switch PRO  ICZB-IW21SW.json

---

devices/icasa/ICZB-IW21D.json

DDF for icasa Zigbee Dimmer Pro ICZB-IW21D

---

general.xml

Updated Ubisys H1 Manufacturer-specific attributes from https://www.ubisys.de/wp-content/uploads/ubisys-h1-technical-reference.pdf

Ubisys H1 Manufacturer-specific attributes

---

devices/blitzwolf/bw_shp13_smart_plug.json

https://forum.phoscon.de/t/how-to-add-another-version-of-the-blitzwolf-bw-shp13/4991

DDF clone for Blitzwolf BW-SHP13 (_TZ3000_3ooaz3ng)

---

devices/third_reality/3RSPE01044BZ_smart_plug.json

Product name : Third Reality 3RSPE01044BZ
Manufacturer : Third Reality
Model identifier : 3RSPE01044BZ
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7852

DDF for Third Reality smart plug 3RSPE01044BZ

---

devices/tuya/_TZ3000_2channel_module.json

This is yet another Tuya based switch, add relevant ID to the existing file.

DDF for Nous B3Z 2 gang switch module (_TZ3000_aaifmpuq)

---

device_access_fn.cpp
resource.cpp

Add guards in ResourceItem and Device Access

---

devices/neo/NAS-WR01B_TS011F.json

Device: TZ3000
Added device manufacturname xzhnra8x

DDF for further NEO NAS-WR01B smart plug (_TZ3000_xzhnra8x)

---

devices/osram/lightify_indoor_flex_rgbw.json

DDF for Osram LIGHTIFY Indoor Flex RGBW

DDF for Osram LIGHTIFY Indoor Flex RGBW

---

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json

As discussed in issue #7848 adding NAS-TH07BH as clone of tuya/_TZ3000_TS0201

DDF for NAS-TH07BH temperature sensor (_TZ3000_TS0201)

---

devices/heiman/cosensor-em.json

DDF for Heiman COSensor-EM

---

devices/ledvance/ledvance_cla60_rgbw_z3.json

DDF for Ledvance CLA60 RGBW Z3

DDF for Ledvance CLA60 RGBW Z3

---

devices/ledvance/b40_dim_z3.json

DDF for Ledvance B40 DIM Z3

---

devices/tuya/_TZ3210_ncw88jfq_temp-hum-sensor.json
devices/tuya/ts0202_presence_sensor.json

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7918

Fix missing battery status for various Tuya sensors 

---

devices/ikea/tretakt_smart_plug.json

DDF for IKEA TRETAKT Smart plug (E2204)

---

devices/ikea/somrig_shortcut_button.json

See official [manual (page 5)](https://www.ikea.com/de/de/manuals/somrig-shortcut-button-weiss-smart__AA-2411208-2-2.pdf#page=5)

Fix IKEA Somrig product type code

---

general.xml

Added ValveDrivePosition0 and ValveDrivePosition100 (used for H1 calibration values)
ValveDrivePosition0: valve closed
ValveDrivePosition100: valve opened

Ubisys Manufacturer-specific attributes in general.xml

---

rest_configuration.cpp

This is already handled by the app quite handler.

Remove database save from API restartapp method

---

devices/tuya/ZY-M100_human_breathing_presence.json

Product name : Smart Human Presence Motion Sensor With Luminance
Manufacturer : _TZE204_laokfqwu
Model identifier : TSO601
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8059#issuecomment-2613934289

DDF clone for Human Presence Detector WY-M100-S (_TZE204_laokfqwu)

---

devices/tuya/_TZ3000_TS011F_smart_plug.json

I've been using this configuration since one week.

DDF clone for Tuya Smart plug with power monitor (_TZ3000_wzmuk9ai)

---

devices/sonoff/snzb-03.json

Manufacturer : eWelink
Model identifier : SNZB-03
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7911

DDF for Sonoff/eWelink waterleakage sensor (SNZB-03)

---

devices/namron/4512763_motion_sensor.json

Product name : Namron Zigbee Motion Sensor
Manufacturer : Namron AS
Model identifier : 4512763
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8045

DDF for Namrom motion sensor (4512763)

---

devices/tuya/ZY-M100_human_breathing_presence.json
devices/tuya/_TZE204_laokfqwu_radar.json

So in fact this device use other dpid than other, so one more tuya radar ....

DDF for Tuya radar sensor (_TZE204_laokfqwu)

---

devices/ikea/tradfri_bulb_e14_ws_opal_400lm.json
devices/ikea/tradfri_bulb_e14_ww_clear_250lm.json
devices/ikea/tradfri_bulb_e27_ws_opal_980lm.json
devices/ikea/tradfri_bulb_e27_ww_clear_250lm.json
devices/ikea/tradfri_bulb_gu10_w_400lm.json
devices/ikea/tradfri_bulb_gu10_ws_400lm.json

Change:
- tradfri_bulb_e14_ws_opal_400lm
- tradfri_bulb_e14_ww_clear_250lm
- tradfri_bulb_e27_ws_opal_980lm
- tradfri_bulb_gu10_w_400lm
- tradfri_bulb_gu10_ws_400lm
- tradfri_bulb_gu10_ww_400lm
Add DDF:
-  tradfri_bulb_e27_ww_clear_250lm [@manup Please close the old PR #7480]

IKEA light bulbs intervals adjusted

---

devices/ikea/tradfri_bulb_e27_ws_clear_806lm.json

DDF for IKEA bulb E27 WS clear 806lm

---

devices/tuya/_TZE204_ex3rcdha_motion_luminosity.json

Product name : ZY-ZHPS01-5.8G
Manufacturer : _TZE204_ex3rcdha
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8102#issuecomment-2727606659

DDF for Tuya Zigbee mmwave Radar Detektor Luminanz (_TZE204_ex3rcdha)

---

devices/tuya/_TZ3218_ya5d6wth_relay_temperature.json

Product name : Mumibiz TYZGTH4CH
Manufacturer : _TZ3218_ya5d6wth
Model identifier : TS000F
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7874#issuecomment-2739507491

DDF for Mumibiz TYZGTH4CH relay with temperature (_TZ3218_ya5d6wth)

---

bindings.cpp
change_channel.cpp
de_web_plugin.cpp
green_power.cpp
ias_zone.cpp
rest_sensors.cpp
tuya.cpp
websocket_server.cpp

In ias_zone.cpp was also a missing argument for CIE address.

Fix printf format warnings

---

devices/innr/sp_120.json
devices/innr/sp_234.json
devices/namron/4512770-4in1-MultiSensor.json
devices/nedis/nedis_zbrc10wt.json
devices/owon/ac201.json
devices/sonoff/snzb-05p.json
devices/wiser/fuga_dimmer_switch.json
devices/wiser/fuga_double_relay_switch.json

Removing the file paths from some DDFs

Removing the file paths from DDFs

---

devices/ledvance/ledvance_plug_eu_em_t.json

The structure seems to be exactly the same as the `INSPELNING`, only this device still shows the frequency. [#8082/#8119]

DDF for LEDVANCE PLUG (COMPACT) EU EM T

---

devices/ledvance/plug_z3.json

DDF for LEDVANCE Plug Z3

---

database.cpp

Usually these were skipped and shown as only hex number nodes. If the node was reachable the Basic cluster attributes were queried, but if it is a Zombie the node remained a "hex node".

Fix loading DDF devices from database which weren't fully setup

---

device_descriptions.cpp

Every item has a load counter, when get item is called it must be checked against the handle, not the global counter.

Fix hot reload and events not emitted after joining a device

---

devices/tuya/_TZE200_TS0601_humidity_temp.json

new manufactuername _TZE200_vs0skpuc added

DDF clone for temperature and humidity sensor (_TZE200_vs0skpuc)

---

rest_groups.cpp
rest_lights.cpp

Pretty sure they were there in the past?!

Fix missing lights and groups Websocket deleted events

---

devices/shelly/shelly_1_gen4.json

Nothing extraordinary, just another DDF :)

DDF for Shelly 1 gen4

---

devices/shelly/shelly_1pm_gen4.json

Nothing extraordinary, just another DDF :)

DDF for Shelly 1PM gen4

---

devices/ubisys/r0_5501.json

Product name : Router R0
Manufacturer : Ubisys
Model identifier : R0 (5501)
See #8129 (comment)

DDF for Ubisys Router R0

---

devices/shelly/shelly_1pm_mini_gen4.json

Nothing extraordinary, just another DDF :)

DDF for Shelly 1PM mini gen4

---

devices/tuya/_TZ3000_TS0203_door_sensor.json

New Door Window Sensor from AliExpress
Manufactor _TZ3000_bpkijo14

DDF clone for Tuya door/window sensor (_TZ3000_bpkijo14)

---

button_maps.json
devices/tuya/_TZ3000_TS0046_6gang_remote.json

Add full support for Tuya TS0046 6-gang switch with model `_TZ3000_nrfkrgf4`.
Closes #8269

DDF for Tuya TS0046 6-gang switch

---

CMakeLists.txt
rest_rules.cpp
rule.cpp
ui/ddf_editor.cpp
ui/ddf_itemeditor.cpp

Still dozens of QVariant deprecated type checks warning, but so far it works.

Support build with Qt6 (alpha)

---

devices/tuya/_TZE200_bh3n6gk8_motion_sensor.json

Product name: Tuya Motion Sensor
Manufacturer: _TZE200_bh3n6gk8/_TZE200_1ibpyhdc
Model identifier: TS0601
See #8304
https://zigbee.blakadder.com/Tuya_ZG-204ZL.html

DDF for Tuya Motion Sensor TS0601 (_TZE200_bh3n6gk8/_TZE200_1ibpyhdc)

---

devices/tuya/_TZE200_npj9bug3_temp_hum_moist_sensor.json

Add additional manufacturer and model IDs
