dresden-elektronik/deconz-rest-plugin

rest_configuration.cpp
Add some REST config properties to match the properties of Hue bridge
NOTE: "UTC" is upper case on Hue, should be on deCONZ too as property names might get deserialized incorrectly on some frameworks if the case is incorrect
=> Add some REST config properties to match Hue

rest_groups.cpp
- returns complete group information on group collections ( /api/xxx/groups and /api/xxx )
- refactored duplicated code
The method getGroupAttributes and groupToMap shared huge amount of duplicated code in different order but functional almost equivalent. I combined the two methods and used groupToMap
=> Return complete group information on collection

.gitignore, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, discovery.cpp, rest_configuration.cpp, upnp.cpp
See issues #19, #41.
Versions:
- Bumped gateway version to 2.04.43;
- Bumped API version to 1.0.1;
- API version in `de_web.pro` instead of hard coded.
Bridge ID:
- Added variable `gwBridgeId` for consistent use in `config.bridgeid`, UPnP discovery, appspot discovery, and `description.xml`.
-  `gwBridgeId` is set to the gateway device’s ZIgBee address, after this device has been discovered.
UPnP discovery:
- Fixed issue #19 (space after `GWID.phoscon.de:` and `upnp:rootdevice`);
- Don’t respond to M-SEARCH and don’t announce before `gwBridgeId` has been set.
appspot discovery:
- Don’t announce before `gwBridgeId` has been set;
- Note that deCONZ only sends `mac` to appspot, which exposes this value as both `macaddress` and `id`.  I think `macaddress` should be dropped (the meethue portal …
=> Gateway Discovery

database.cpp, de_web_plugin.cpp, discovery.cpp, rest_configuration.cpp, upnp.cpp
Follow-up for #44.
> Preventing the internet announcement when gwBridgeId is not set is tricky, because the software update mechanism in the Web App depends on it (new versions are notified in the response). A missing gwBridgeId could happen for various reasons like: RaspBee firmware broken, no RaspBee or ConBee attached or a misconfigured UART. The update and discovery should not be blocked in these cases, therefore something like an fallback mechanism should be added. Maybe setting the gwBridgeId to the Raspberry mac address or the last known RaspBee or ConBee address.
`gwBridgeId` is now persisted in the database when the gateway device has been discovered.  It's initialised to `0000000000000000` on startup, but it should be restored before the REST API advertises itself or responds to …
=> Gateway DIscovery (2)

de_web_plugin.cpp, sensor.cpp
Suppress superfluous 4003 and 5003 buttonevents for the new Trådfri remote firmware (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/96#issuecomment-321982500)
=> Fix for new Trådfri remote firmware

database.cpp, de_web_plugin.cpp, rest_lights.cpp, rest_sensors.cpp
Implement `config.alert` for sensors:
- Hue motion sensor;
- TRÅDFRI motion sensor;
- TRÅDFRI remote.
Remove `config.alert` from Hue dimmer switch, as it doesn’t support _Identify_ (even though it has a 0x0003 server cluster).
Change timings for light `state.alert` to match Hue bridge:
- `select`: 2s (Hue lights don’t respond when set to 1s);
- `lselect`: 15s.
=> Implement config.alert for sensors

bindings.cpp, bindings.h, de_web_plugin.cpp, de_web_plugin_private.h
Still trying to get `config.sensitivity`, `config.senstivitymax`, `config.usertest` and `config.ledindication` to work.  This is as far as I got this weekend.
- Added the attributes to `updateSensorNode()`;
- Read them in `delayedFastEnddeviceProbe()` - not sure if this is a good idea: they're read multiple times (as in many) on device discovery;
- Added the _Basic_ cluster to `checkSensorBindingsForAttributeReporting()`, but somehow the binding isn't configured.  Don't know why not;
- Refactored `sendConfigureReportingRequest` to allow for:
- Reporting config for multiple attributes per cluster;
- a reportableChange of 0 (as issued by the Hue bridge);
- manufacturer-specific attributes;
- Double-checked the used parameters against what Philips Hue bridge uses, notably _Battery …
=> Attribute reporting for Hue motion sensor config

database.cpp, rest_sensors.cpp, sensor.cpp
I've been playing around a bit more with web socket notifications, changing the code from 8308384da6f49aa8f958e2fda569002f8f60d0fc to include only the attributes that have actually changed in the web socket notification, just for the feel of it.  For now, I have commented out the code for this change in this PR.  Basically it's just changing the checks for the attributes to be included in the notification from
```c++
if (item->lastSet().isValid())
```
to
```c++
if (item->lastSet().isValid() && item->lastChanged().isValid() && item->lastChanged() >= sensor->lastStatePush)
```
and
```c++
if (item->lastSet().isValid() && item->lastChanged().isValid() && item->lastChanged() >= sensor->lastConfigPush)
```
The change does what I expected, but I found some funny behaviour after restarting …
=> Fix sensor event timestamps

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, resource.cpp, resource.h, rest_sensors.cpp
Added `config.duration` attribute for Hue motion sensor.  It's value is just a bitmap - the array is only created when GETting the sensor resource;
When changing `config.duration`, `config.ledindication`, `config.sensitivity`, or `config.usertest` from the API, the following happens:
- The cached attribute is updated immediately, and a websocket notification is issued accordingly;
- The attribute name is added to `config.pending`;
- A `mustRead()` flag is set for the attribute;
- On the next communication with the sensor, the attribute is written, the attribute name is deleted from `config.pending` and the `mustRead()` flag is cleared - no websocket notification is issued at this time.
I disabled the old `config.duration` logic for the Hue motion sensor.  It prevented setting duration …
=> Update Hue motion sensor config attributes through config.duration

bindings.cpp, database.cpp, de_web_plugin.cpp
Add Basic cluster to Hue motion sensor fingerprint, so attribute reporting for ledindication and usertest will be setup.
Once attribute reporting has been setup, `config.ledindication` and `config.usertest` are indeed updated in all three resources (as I hoped).
For the Hue motion sensor, check attribute reporting for Occupancy Sensing cluster on sensitivity instead of occupied state (in the hope that attribute reporting for sensitivity is more likely to be setup).
=> Hue motion sensor config - continued

bindings.cpp, database.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp, rest_sensors.cpp, sensor.cpp
Added new configuration setting, `/config/websocketnotifyall`, which defaults to `true`.  When set, all `state` or `config` attributes are included in the web socket notification; when set to `false` only the changed attributes are included.  See issue #194.
Updated API version to 1.0.4.
This PR also fixes that `state.lastupdated` was updated when `config.duration`, `config.ledindication`, `config.sensitivity`, `config.sensitivitymax`, or `config.usertest` was updated.  However, no event was issued for `state.lastupdated`, so the updated `state.lastupdate` wasn't reflected in the REST API.  I don't think this solves the duplicate web socket events from issue #194.
=> web socket notification enhancements

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_sensors.cpp, sensor.cpp, sensor.h
Fix automatic resetting of `state.presence` to `false`:
- Now the reset of `state.presence` to `false` takes place `config.duration` seconds (+/- 1 for rounding errors) after `state.presence` was last set to `true`;
- To disable automatic resetting, set `config.duration` to 0;
- Don’t reset `state.presence` automatically for motion sensors that do attribute reporting on the Occupancy Sensing cluster (like the Hue motion sensor), under the assumption that they’ll issue a message when motion is no longer detected;
- Also reset `state.presence` automatically for CLIPPresence sensors (when `config.duration` > 0);
- `config.duration` initialised to `0` instead of `60`.
Refactored the logic:
- Loop over all sensor resources in `checkSensorStateTimerFired()` instead of just checking one sensor …
=> Fix automatic resetting of `state.presence` to `false`

de_web_plugin.cpp
If the sensor does not report manufacturer code, 'manufacturer' wont be set to "LUMI" which means that the cluster report struct that Xiaomi uses won't be parsed as such (being conditioned on manufacturer == "LUMI").
modelId starting with "lumi." is enough to identify the sensor as "LUMI".
See also issue #204
=> Support Xiaomi devices that do not report manufacturers.

de_web_plugin.cpp
This PR adds support for Heiman (http://www.heimantech.com/) door/window, Carbonmonoxide and smoke detectors. The door/window is added as `ZHAOpenClose`. The CO and smokedetectors are added as `ZHAPresence`, as discussed in #152.
Although it is possible with the Heiman devices to use the `modelid` to see what kind of 'presence' is detected, it would be nice to have the `IAS Zone Type` added to the API output.
=> Add support for Heiman door/window, CO and fire sensors

de_web_plugin.cpp, sensor.cpp
- Xiaomi smart button, non-Aqara version (`lumi.sensor_switch`): fix swap 1000 and 1002 values for `state.buttonevent`.  1000 should be press, 1002 release;
- ubisys C4 control unit: don't create ZHASwitch resources for the _Windows Covering Control_ endpoints, only for the four _Level Control Switch_ endpoints.
=> More button fixes

rest_groups.cpp
This allows to change a group from on to off ja vice versa with the same button event.
Works for me with Xioami (lumi.sensor_switch.aq2) switches to use the same button event to toggle the light state.
=> Add toggle support for groups

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, resource.cpp, resource.h, rest_sensors.cpp
Added support for CLIPConsumption and CLIPPower sensors.
Introduced `config.delay`, as discussed in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/404#issuecomment-369028276.  Tested on Hue motion, Heiman motion, IKEA Trådfri motion, and CLIPPresence sensors.
- I didn't dare touching the FLS-NB sensors, so they still have `config.duration`;
- Also I didn't touch the logic to reset presence to false when no reports are received;
- The API allows setting `config.delay` for the Trådfri, but this doesn't do anything - the value is overwritten on the next motion is detection.
- I didn't implement the part where a presence is false report is ignored when `config.duration` > 0.  I feel it would mess up the code too much.
Also busy trying to add support for the Bitron smart plug, …
=> CLIPConsumption, CLIPPower, and config.delay

bindings.cpp, bindings.h
@manup, hope you can still include this one in v2.05.14.
Somehow the binding request isn't sent unless `setMgmtBindSupported(false)` is issued.  Instead of checking for `receiverOnWhenIdle()`, I just whitelisted the plugs as `endDeviceSupported`.  I suppose if needed, the management binding will be created from the light node anyways.
I verified in WireShark that the right _Configure Reporting_ commands are generated for the u48 and s24 attributes of the _Simple Metering_ cluster and that the Heiman plug accepts these.  Apparently the Heiman has only room for 5 reporting configurations, where there's 6 attributes to be reported:
- _On/Off_ (0x0006/0x0000);
- _Current Summation Delivered_ (0x0702/0x0000);
- _Instantaneous Demand_ (0x0702/0x0400);
- _RMS Voltage_ (0x0B04/0x0505);
- _RMS …
=> Fix binding for attribute reporting for mains-powered sensors.

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp, poll_manager.cpp
- Also poll _Instantaneous Demand_;
- Don’t poll Daylight sensor;
- Check sensor type for polling `state.power`;
- Additional debug messages.
=> Sensor Polling and Keen Home Vent

bindings.cpp
One more change, @manup.  I hope you can still include it.
=> Whitelist Keen Home vent for attribute reporting

database.cpp, de_web_plugin.cpp, sensor.cpp
Xiaomi wall switches, #356:
- Don't create `config.battery` for Xiaomi wall switches;
- Don't create light resources for `On/Off Switch` endpoints for lumi.ctrl_neutral1, lumi.ctrl_neutral2;
- Fix Xiaomi magic for lumi.ctrl_ln2.aq1, so now `config.temperature` is updated.
Climax Siren, #404:
- Whitelist Climax Siren as end-device light;
- Whitelist Climax Siren as sensor.
TODO:
- Suppress light resource for endpoint 03 for lumi.ctrl_neutral1;
- Update light states on Xiaomi magic;
- Check Xiaomi magic for lumi.ctrl_ln1.aq1, lumi.ctrl_neutral1, lumi.ctrl_neutral2;
- Check whether lumi.ctrl_neutral1 and lumi.ctrl_neutral2 switches actually report consumption on endpoint 08.
=> Xiaomi wall switches, Climax Siren

bindings.cpp
Changed whitelist for Keen Smart Vents to match more models to fix #592.
=> Improve Keen Smart Vent whitelist

README.md
deCONZ GUI is started as a systemd service not an X11 autostart script
=> Updated instructions for disabling deCONZ GUI

bindings.cpp, database.cpp, de_web_plugin.cpp, rest_rules.cpp
Support innr SP 120 smart plug, see #432.
@manup, the ZCLDB file general.xml needs to be updated as well, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/432#issuecomment-395757777.  I'm still not entirely sure if the setup of the binding for attribute reporting works.  The (light) _OnOff_ and _Level_ clusters work, but the (sensor) _Electrical Measurement_ and _Metering_ clusters seem more challenging.
Bug fix `gt` and `lt` operators in rule conditions.
=> innr SP 120 smart plug

bindings.cpp, de_web_plugin.cpp, rest_groups.cpp, sensor.h
Newly discovered action for the Xiaomi cube: drop, see #138.
Fix scaling of current for Heiman smart plug.
@manup, sorry, I had to comment out a line in the handling of the C4 setup, see #631.
@manup could you please also add some more attributes to clusters 0x0702 and 0x0B04 to general.xml?  (Still waiting for general.xml to be part of this respository ;-)  Most plugs don't support these, but the Heiman does.
[general.xml.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2086889/general.xml.zip)
=> Xiaomi cube drop action, see #138

bindings.cpp, database.cpp, de_web_plugin.cpp
- Only handle _Binary Input_ for SmartThings Arrival sensor, see #655;
- Fix attribute reporting for SmartThings Arrival sensor, see #427;
- Consistently use `modelId.startsWith(QLatin1String("tagv4"))` to recognise the sensor.
=> SmartThings Arrival sensor, take 2

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, ias_zone.cpp, permitJoin.cpp, rest_configuration.cpp, rest_lights.cpp, rest_sensors.cpp
This implements searching for new lights through "GET /api/<apikey>/lights/new" and reporting them in a way that works with the Hue app. Hopefully this fixes ~~#29~~ #28. Also see #663.
I've basically copied the code for searching for new sensors. However, the sensors code seems to be quite a bit more involved. In order to track what is going on, and for consistency I renamed the sensor code from "find" to "search". Then I left out what didn't seem to apply to light nodes. It would be good for someone more knowledgeable to double check this though. One more change is that I moved the resendPermitJoinTimer to where the permitJoinTimer code is, that seemed more sensible.
Obviously this works for me, but some more testing is probably a good idea. Hope this helps.
=> Implement searching for new lights based on the searching for sensors code.

zcl_tasks.cpp
Recent light/firmware combos have a different MAC prefix (`0x90fd9f`) compared
to the hardcoded `ikeaMacPrefix` (`0x000b57`), so use the manufacturer code
as an additional criteria to detect IKEA lights.
---
Background:
I'm using this PR to start a conversation/brainsorm. I have a number of recently-purchased IKEA lights (E27, E14, GU10) which were shipped with the latest available firmware from the factory. I control them via the REST plugin and the `deconz`component of Home Assistant. I noticed that the IKEA E27 colored lights do not support setting `ct`, only `xy`, and I was exploring the possibility of emulating that feature by internally converting any incoming commands containing `ct` into `xy` and sending that to the lamp instead.
By examining the source code I realized that by …
=> Detect IKEA light by manufacturer code in additon to MAC prefix

de_web_plugin.cpp, de_web_plugin_private.h, window_covering.cpp
Adding ubisys J1 to the supportedDevices array in de_web_plugin.cpp and WINDOW_COVERING_CLUSTER_ID to de_web_plugin_private.h. Also creating window_covering.cpp to later handle cluster attributes and commands.
=> Add initial support for ubisys J1 Window covering device

de_web_plugin.cpp, light_node.cpp, rest_lights.cpp
Add window_covering cluster updating `bri` value with lift percentage during moving. The update happens in realtime. This requires that reporting has been configured. The updateLightNode will map WINDOW_COVERING cluster attributes lift/tilt percentage to bri/sat on lightnode. 
Add move to tilt percentage for PUT `{ "sat" : value }`. 
Add modelId `lumi.curtain` in rest_lights.cpp setLightState, see issue #593.
The ubisys J1 now shows up in `/lights` with:
```
"state": {
"bri": 165,
"on": true,
"reachable": true,
"sat": 0
},
```
This PR is a follow up on PR #727 and issue #534 
@ebaauw the `dc_eventlog` is now showing output while moving.
Summary: These commands are implemented.
ubisys J1 command | put command
-------- | -----------------------
move down/up | `{"on" : …
=> window_covering updating bri and adding sat for move to tilt

time.cpp
Every ZCL read request on Time cluster 0x000A will generate a valid response for every attribute.
The daylight savings attributes DstStart, DstEnd, DstShift are calculated based on `QTimeZone::systemTimeZone()`.
@ebaauw  I have enhanced your existing `time.cpp` because I want to also support Bitron Thermostat 902010/32 which needs daylight saving time.
=> Add full implementation of Time cluster server.

time.cpp
- Fix random values for _Last Set Time_ and _Valid Until Time_ attributes, see #774;
- Don't overwrite timezone to Berlin when set to GMT;
- Remove DBG_INFO messages (the `lumi.ctrl_neutral2` switches poll this cluster every minute or so!).
=> Time server bug fixes

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, resource.cpp, resource.h, rest_sensors.cpp, window_covering.cpp
Sending  PUT /sensors/xx/config `{"windowcoveringtype" : 0}` starts calibration. 
Sending PUT /sensors/xx/config `{"mode":"momentary"}` or `{"mode":"rocker"}` to be used with two push-buttons (momentary switches, one stable position) or two rocker switches (two stable positions).
A sensor ZHASwitch has been created to implement the new functionality.
Calibration:
---
First binding and reporting is configured. Binding is created from device endpoint 0x01 and cluster 0x0102 window covering to deCONZ coordinator. Reporting is configured on attributes 0x0008 LiftPct, 0x0009 TiltPct, 0x000A OperationalStatus.
Then calibration steps 1-9 are started. The shutter/shade moves down and up during calibration. Details in ubisys J1 technical reference page 18-20.
The windowcoveringtype has values from …
=> Add ubisys J1 calibration and switch configuration.

de_web_plugin_private.h, rest_configuration.cpp
Commit https://github.com/dresden-elektronik/deconz-rest-plugin/commit/59a7811a7c3d9fd6dcdb447e5e2ffe61402eb77b automatically allows localhost. However, with the pass-through server that I set up for the Hue app (https://github.com/KodeCR/hue-pass) this automatically allows all users. This makes it optional with a comment-line parameter (default is still to allow).
=> Make allowing localhost to create an api key optional

bindings.cpp, de_web_plugin.cpp, sensor.cpp
This PR adds basic support for the Trådfri on/off switch (bundled with the IKEA plug, see #779).
With these changes the button emits 1001/1002/1003, 2001/2002/2003 button events.
@manup My remote has a different mac address then `ikeaMacPrefix` (it starts with 0xd0cf5e), maybe something needs to change there as well?
=> Add support for Trådfri on/off switch

de_web_plugin.cpp, rest_lights.cpp, window_covering.cpp
- Invert _CurrentPositionLiftPercentage_ so that 0% is _Open_ and 100% is _Closed_, in line with ZCL spec, see #746;
- Ignore _OnOff_ cluster;
- Suppress creating non-operational ZHASwitch and ZHAPresence sensors.
- Handle Xiaomi special attribute for `lumi.curtain` - update `state.bri` and `state.on` of the `/lights` resource;
- Handle Xiaomi special attribute for `lumi.ctrl_neutral` and `lumi.ctrl_ln` - update `state.on` of the `/lights` resource.
- Set node's `rx()` on receiving Xiaomi special attribute - this solves the `lumi.ctrl_neutral` being unavailable after restart, see #798.
=> lumi.curtain and lumi.ctrl_neutral

database.cpp, de_web_plugin.cpp, general.xml, rest_groups.cpp
- Another Xiaomi special attribute.
On the _Analog Output_ cluster of the `lumi.curtain`.  It cannot be read, but is included in the attribute report for this cluster.
Not sure what it means, yet; it always seems to hold the same value.
- Initialise `state.lastupdated` of CLIPGenericFlag and CLIPGenericStatus to startup time on startup.
- Bring back `devicemembership` attribute of `/groups` resources, see #856.
- Report ZHAPower sensor `state.current` in mA (instead of 0.1A), see #820.
- Suppress creation of ZHAConsumption sensor for `lumi.ctrl_neutral` switches.  The switch doesn't report consumption, to the value of `state.consumption` remains `0`.
=> Various smaller enhancements

de_web_plugin.cpp
This makes the newer Aqara single button switches work with normal press, long press and double press.
=> Fix for newer Aqara single button switches (lumi.remote.b1acn01)

de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp, upnp.cpp
This refactors some of the code to remove code duplication in configToMap and basicConfigToMap by splitting out the network info code. It looks like description.xml wasn't updated with a found ip-adress before. The downside could be the config doesn't update the ip-address if it changes after initialisation, but I'm not sure if that really worked before? Probably best to look at 7c2cf2 for the changes because the line endings messed thing up for me.
=> Split out network info and refactor/clean config map generation 

rest_groups.cpp, rest_lights.cpp
This adds an option to make the brightness wrap around when you send bri_inc, when it either reaches the maximum brightness (254), or 0 - depending on if bri_inc is negative or positive. I suppose it would be better if the deCONZ daemon could handle this instead, but since it's not possible for most people to change that I thought I would add the functionality to rest instead.
I don't know how useful this would be to people, but it is something I use myself - I have several aqara switches that only have the single-press and double-press actions, so I made the double-press dim down the lights by a fixed amount, but since there's no way of increasing it again, I added this option to make it wrap around back to the brightest again.
Do let me know if you want any changes done to it, or if …
=> Add wrap option when sending bri_inc

de_web_plugin_private.h, resource.cpp, resource.h, rest_sensors.cpp, window_covering.cpp
I have basically included all ubisys J1 attributes that can be written. Especially important are `LiftToTiltTransitionSteps` and `LiftToTiltTransitionSteps2`, as these need to be set manually for lift and tilt blinds and cannot be automatically detected by running a calibration cycle.
Please feel free to suggest changes or enhancements to the coding style - my cpp skills have been neglected in recent years, so they're fare from state of the art...
=> Windows Covering: Allow Configuration of ubisys J1 Specific Attributes

de_web_plugin.cpp
See https://github.com/ebaauw/homebridge-hue/issues/397.
=> Don't create ZHASwitch resource for endpoint 01 of the Xiaomi cube.

database.cpp, de_web_plugin.cpp
See #692.
Removed _Commissioning_ cluster and added _On/Off_ cluster.
Changed the order to match creating the sensor:
- _Occupancy Sensing_,
- _IAS Zone_,
- _Binary Input_,
- _On/Off_.
=> Fix cluster when loading ZHAPresence sensor

authentification.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, rest_capabilities.cpp, rest_configuration.cpp, rest_gateways.cpp, rest_groups.cpp, rest_info.cpp, rest_lights.cpp, rest_resourcelinks.cpp, rest_rules.cpp, rest_scenes.cpp, rest_schedules.cpp, rest_sensors.cpp, rest_touchlink.cpp, rest_userparameter.cpp, time.cpp
This PR adds the scenes, info, and capabilities nodes to the api. Furthermore it:
- adds the timezones of the system to the info and capabilities nodes, the rest of the capabilities node and the scenes node is empty for now
- centralise the apikey check so it isn't missed anywhere, e.g. schedules
- update the error messages and handle everything under /api
The aim is still to slowly work towards better support for the hue-api/Hue app (#663)
=> Api handling

de_web_plugin.cpp, de_web_plugin_private.h
Use reports for _Analog Output_ cluster to set `state.bri` and `state.on` as a backup in case _Window Covering_ reports fails.
=> lumi.curtain

authentification.cpp, authorisation.cpp, database.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp, rest_groups.cpp, rest_lights.cpp, rest_resourcelinks.cpp, rest_rules.cpp, rest_scenes.cpp, rest_schedules.cpp, rest_sensors.cpp, rest_touchlink.cpp
Extend strict api mode to: normal, strict, amazon echo, philips hue app
Whitelist supported sensors for the Hue app (some such as ZHAAlarm crash the app), this fixes #663, nr 1
Only rooms can have classes (LightGroups with a class breaks Hue app)
Some consistency changes and warning fixes
Update Hue version and add software date
Mimic hue dimmer switches for some compatible other switches
Terminology
=> Extend strict API mode

de_web_plugin.cpp
Add Bitron smoke detector 902010/24
```
{
"config": {
"on": true,
},
"ep": 1,
"etag": "90f0140d0c8eaa982b3e7675ec28ab14",
"manufacturername": "Bitron Home",
"modelid": "902010/24",
"name": "Alarm 18",
"state": {
"alarm": false,
"lastupdated": "none",
"lowbattery": false,
"tampered": false
},
"type": "ZHAAlarm",
"uniqueid": "00:12:4b:00:07:7f:13:44-01-0500"
},
```
=> Add support for Bitron smoke detector 902010/24

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, sensor.cpp
- ubisys S1, S1-R (untested), see #919;
- iCasa keypads, see #1124;
- iCasa dimmer, see #1124.
@manup there's still two loose ends:
- I cannot get deCONZ to create the binding and attribute reporting for the iCasa dimmer.  Don't know what's going on; I reset and re-paired my Trådfri colour bulb, but no bindings for that either.  deCONZ happily polls the lights.  Even after creating the binding manually, the report configuration isn't set.  After setting that manually as well, deCONZ stops polling the lights.  This is my test network (2.05.54, self compiled plugin from latest commits), with only two lights (the iCasa dimmer and the Trådfri).
- The iCasa keypads don't support attribute reporting for the battery, so deCONZ needs to poll them.  The good news: they seem to poll their parent at …
=> Support more switches

rest_sensors.cpp
When updating a sensor resource an extra colon in returned. This is not in line with the rest of the API (for example /lights). This fixes #1135.
=> Remove extra colon in API response when updating a sensor

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_sensors.cpp
Multiple MAC prefixes have been seen in the wild for IKEA devices.
Because of this, existing checks looking for specific MAC prefixes are fragile.
Therefore, this PR changes existing MAC checks to invoke a new `checkMacVendor()` function that supports multiple prefixes per vendor. In addition, IKEA check has been amended to support the 4 different prefixes seen in the wild.
---
As discussed in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/700
=> Refactor MAC checks, add new IKEA prefixes

de_web_plugin.cpp, de_web_plugin_private.h, general.xml, rest_lights.cpp, rest_sensors.cpp
Poll battery percentage remaining (0x0001/0x0021) for `/sensors` resources  The change is for the iCasa Pulse keypads, which don't offer attribute reporting, see #1124.
@manup, please review.  This is working fine in my test network, but I worry about the potential performance implications, and battery usage implications for other devices, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1124#issuecomment-456207910.
=> Poll battery percentage remaining for sensors.

light_node.cpp
See #1204, #1205.
- Set default `ctmax` value to 65535 instead of 0.
- Don't expose `state.colormode` for GL-C-009 _Dimmable Light_ endpoint, even though it advertises a non-functional _Color Control_ cluster.
=> Fix GLEDOPTO bugs

de_web_plugin.cpp
ZHAVibration: Report `state.orientation` as normalised angles instead of raw values.  See #748.
=> ZHAVibration: report orientation as angles

de_web_plugin.cpp
I’ve bought a new Heiman HC1CG-E gas sensor. They use a new manufacturer code and model ID: `GASSensor-EM`.
I followed 059af72001a13eb1afc2bf238fa071e5e4bd7f8d and added the new prefix. (I haven’t compiled nor tested this change.)
=> Whitelist newer model Heiman gas sensor

de_web_plugin.cpp, de_web_plugin_private.h
Don't create ZHASwitch for lumi.vibration when creating ZHAVibration, to prevent two sensor resources with the same `uniqueid`.  See #748.
Fix scaling of `state.consumption` and `state.power` for Climax power switch, see #1409.
Whitelist Third Reality smart light switch, see #1413.
=> Don't create ZHASwitch for lumi.vibration

de_web_plugin.cpp, de_web_plugin_private.h, general.xml, light_node.cpp, resource.cpp, resource.h
general.xml:
- Add Xiaomi manufacturer specific attributes to connect/disconnect the buttons of a wired switch to/from the relay. See #1420.
- Add _Fan Control_ cluster 0x0202, see #932
REST API plugin:
- Don't expose `state.bri` for innr SP120 plug.
- Initial (experimental, untested) support for Hampton Bay fan module, see #932.
=> Various enhancements

de_web_plugin_private.h, rest_capabilities.cpp, rest_info.cpp
This implements the rest of the capabilities api. The hue app uses this to check before creating schedules and rules for e.g. the dimmer switch.
=> Implement the rest of the capabilities api

de_web_plugin.cpp, de_web_plugin_private.h
It appears these keypads report battery percentage periodically after all, slightly under every four hours. see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1509#issuecomment-493671362 and https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1124.
=> Don't poll iCasa Pulse keypads for battery percentage

de_web_plugin.cpp, de_web_plugin_private.h
Fix GLEDOPTO lights not reporting the correct value for _Enhanced Color Mode_, see #1526.
I no longer have the old RGB+CCT model, so I cannot test whether it actually has the same issue, but I don't think the change will do any harm (as long as _Color Mode_ is supported). They use manufacturer code 0x0000, so I whitelist the manufacturer name instead.
=> Fix GLEDOPTO lights not reporting the correct value for Enhanced Color Mode

rest_resourcelinks.cpp, rest_rules.cpp, rest_schedules.cpp, rest_sensors.cpp
- allow "type" as a resourcelink attribute on creation (even though there is only one option)
- allow schedules and scenes actions in rules
- a schedule is also valid if providing localtime instead of time as a required attribute
- also allow a sensor config as a json dictionary
Together this enables me to set up a Hue dimmer switch and a Hue motion sensor from the Hue app.
=> Several small api fixes

de_web_plugin.cpp
All informations here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1551
I m agree, this patch is a little "hacky", it will be better using for exemple something like 
`if (sensor->durationDue.isValid())`
To check if there is an active timer, but I don't see an utility to do that yet. The Vibration sensor for exemple don't need it in reality.
=> Periodic report, set presence sensor state to false.

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp, rest_groups.cpp
This is mostly the first commit from #1471 so it can be reviewed and merged in stages. This:
- creates a (regular Zigbee) group with all the lights in it and translates api "group 0" to this Zigbee group
-- just using Zigbee group id 0 did not work for all lights nor 65535, so it finds a free group from 65520 going downwards
-- removes all "group0" special cases
This should cause not change in behavior. On the Zigbee side each light will now have an extra group, and turning off or on all lights via group 0 on the api side is now achieved on the Zigbee side with a groupcast to this zigbee group instead of a broadcast.
=> Implement "group 0" as a regular zigbee group

de_web_plugin.cpp
This addresses #1612 by always deleting the old group 0 if that has not happened yet.
=> Fix old group0 delete

linux/deCONZ/usr/bin/deCONZ-ikea-ota-download.sh
Ikea OTA download script with curl and jq. No Python needed.
Script is also tested in the [Deconz Docker image](https://hub.docker.com/r/marthoc/deconz/)
See [1606](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1606)
=> Add Ikea OTA download with curl and jq

de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp, rest_lights.cpp
Add siren support to Bitron Smoke Detector with siren.
Add Develco smoke sensor to supported devices list, issue #1534.
Add siren support to Develco smoke detector.
A smoke detector has device id 0x0402 `WD Zone`. Therefore, the smoke detector was not added to type `Warning device` (device id 0x0403). But the smoke detector does have the clusters `IAS Zone (0x0500)` and `IAS WD (0x0502)`. This PR adds device type `Warning device` whenever a `IAD WD` cluster is found. 
The following REST API calls are now supported on Bitron smoke sensors and on (untested) Develco smoke sensors in order to start or stop the siren.
```
/api/<apikey>/lights/<id>/state -X PUT -d '{ "alert": "select" }'
```
```
/api/<apikey>/lights/<id>/state -X PUT -d '{ "alert": "lselect" }'
```
``` …
```
=> Add siren support to smoke sensors

bindings.cpp, de_web_plugin.cpp
It does work partially on my system, somehow the `IAS_CIE_ADDRESS` doesn't
get set automatically. After manually setting that, at least my door/window sensor works.
=> Add basic support for Konke sensors (see #1607)

bindings.cpp, de_web_plugin.cpp, light_node.cpp
This adds support for ORVIBO in-wall switch, in-wall dimmer and motion sensor. Closes #794, #1686 and #1747.
=> Support for ORVIBO switch, dimmer and motion sensor

light_node.cpp
disables state.bri for innr 2xx series plug devices, originally fixed for the sp 120 in #1444 commit 364ce0d0d86cbb5a34ffe15d277eed8502af383f
=> disable state.bri for innr zigbee 3.0 devices

bindings.cpp, de_web_plugin.cpp
Adds support for the ORVIBO SF21 smoke sensor. Closes #1875.
=> ORVIBO SF21 Smoke Sensor support

de_web_plugin.cpp, de_web_plugin_private.h
Add the following thermostats to supported devices list.
- Centralite Thermostat, issue #1601 .
- Zen thermostat, issue #1702 .
- Sinope thermostat TH1300ZB, issue #1289 .
In order to also add Elko thermostat, the node info is required, i.e. mac prefix and manufacturer code, issue #1291 .
=> Add support for serveral thermostats.

de_web_plugin.cpp
SF21 vendor and MAC prefix differs from SF20.
=> Fix for ORVIBO SF21 smoke sensor support

rest_lights.cpp
Some GLEDOPTO devices do not turn on/off in some cases. Namely if a "Move to Level (with on/off)" command is sent to them. They do not honor the "with on/off".
The provided fix sends an extra "On/Off" command to make these devices work as expected.
=> Workaround to make GLEDOPTO led driver turning lights on/off as expected.

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, rest_lights.cpp, rest_sensors.cpp, sensor.cpp, thermostat.cpp
Long version here :
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883
Short version:
- Bug correction on window covering switch (not working if bri = 1)
- Adding basic support for cable outlet, working with 2 working mode, on/off and "fil pilote", for the second one, creation of a sensor with "mode" field, mode supported confort/confort-1/confort-2/eco/hors gel/off. This support is realy basic (no attributes reporting) but I think it's used only in France. And I have "vampirized" the  thermostat.cpp file, to add my function, but it's a kind of thermostat too.
- Adding support for wireless switch.
For the wireless switch, it create a group but with uniqueid, so I have some question about it > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2123
This device …
=> Update for Legrand device

light_node.cpp
This resolve the inclusion of eWeLink SA-003-Zigbee reported as "type": "Unknown" and now as "On/Off plug-in unit"
=> Fixed inclusion of eWeLink SmartPlug model SA-003-Zigbee

de_web_plugin.cpp
I’ve bought a new Heiman HS1DS-E door/window sensor. They use a new model ID: `DoorSensor-EM` (I haven’t compiled nor tested this change).
Cluster Info screenshot:
Node Info screenshot:
Thanks for your work!
=> Add support for newer Heiman HS1DS-E door/window sensor

rest_lights.cpp, rest_rules.cpp, sensor.cpp, window_covering.cpp
Various bug fixes:
- Trådfri remote: don't issue 1001 button events without corresponding 1003s.  See #2201.  I'm not sure every-one would agree to this change; please see the discussion in the issue;
- Sometimes `ddx` rules are triggered twice, see #2148;
- Illegal `state.bri` and `state.sat` value of 255 for window covering devices, see #2257.
=> Various bug fixes

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, light_node.cpp, rest_sensors.cpp
- Add support for Samsung SmartThings plug (IM6001-OTP, modelId "outletv4")
- Add support for Samsung SmartThings plug (7A-PL-Z-J3, modelId "ZB-ONOFFPlug-D0005", #2121)
- Update for TRADFRI remote with different Silabs MAC than before (#2243)
- Added cluster "Device Temperature Configuration"
- Amended Develco temperature reporting interval
- Initial support for Xiaomi smart plug (lumi.plug.maeu01, untested #2267)
- Attribute Set Identifier correction in electrical measurement cluster
- Added support for Lupus small zigbee temperature sensor (untested #2281, #1961)
- Added support for Aurora AOne Double Socket UK (untested, #2292)
- Added support for Bosch RFDL-ZB-MS (untested, #2289)
- Fix to allow Samsung SmartThings plug sensors to be created (7A-PL-Z-J3, modelId ZB-ONOFFPlug-D0005, …
=> Various updates

de_web_plugin.cpp, de_web_plugin_private.h, rest_rules.cpp
I found a [new source](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-zbee.h) for ZigBee manufacturer codes, which contains the missing codes that we couldn't find earlier.  There are some mismatches between this list from WireShark and our current list, which I've highlighted in this PR.  I haven't marked any literal differences, like names with or without "Technology" in them, or "DDEL" vs "Dresden".  I think the mismatches I marked are mostly OEM vs commercial names, like "Shenzhen" vs "Sunricher", or "Jiuzhou" vs "Paulman".
I also sorted the list, once again, on manufacturer code.
Main reason I've created this PR is to start/continue the discussion how we want to deal with these definitions.  Should we continue to maintain them ourselves, or should we …
=> Vendor codes

basic.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, poll_manager.cpp
Long story here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2369
- Solve some issue with missing feature on devices.
- Improve pairing.
I know lines 52/54 in basic.cpp aren't fantastic, but I haven't found a way to make this part manufacture specific (the device is not in the database so I can't use it for test, and I don't see a way to use zclFrame).
I haven't find declaration for deCONZ::ApsDataIndication, perhaps this class have something to retreive the manufacture code (the read attribute request have it)
I can remove the 0x0000 attribute, it is here just for tests (or future use).
=> Improve pairing for Legrand

de_web_plugin.cpp, rest_lights.cpp
Support `state.ontime` in combination with setting `state.alert` to `lselect` or (for Warning Devices) to `blink`.  The default duration of the warning (300s) or identification (15s) can be overwritten using `state.ontime` (in seconds).
See https://github.com/ebaauw/homebridge-hue/issues/614.
=> Support state.ontime in combination with state.alert

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml
- Added initial support for eCozy Smart Heating Thermostat (#2393)
- Added initial support for Stelpro ST218 thermostat (#2307)
- Updated general.xml (Thermostat User Interface Configuration)
- Whitelisting additional sensors for attribute reporting
- Enable Bosch RFDL-ZB-MS battery updates
=> Device integration and updates

bindings.cpp, de_web_plugin.cpp, general.xml, sensor.cpp
New PR !
This code adds support LEGRAND wireless shutter switch / REF 067646
https://www.legrand.fr/pro/catalogue/42569-version-celiane-with-netatmo/commande-sans-fil-pour-interrupteur-filaire-de-volet-roulant-connecte-celiane-with-netatmo-blanc
=> Add support for LEGRAND wireless shutter switch (synced with master)

de_web_plugin_private.h, light_node.cpp
Don't expose state.bri for 3A Smart Home
=> disable state.bri for 3A zigbee 3.0 devices

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, poll_manager.cpp
- Removed config item "battery" for Xiaomi smart plugs
- Optimize consumption polling for smart plugs 
- Added support for Samsung/Centralite smart outlet (#819)
- Added initial support for Sercomm / Telstra SZ-ESW01-AU smart plug (#2496)
- Amended report configuration for GS SKHMP30-I1 smart plug
- Corrected power value for Samsung/Centralite smart outlet
- Updated measurement units for Sercomm / Telstra SZ-ESW01-AU smart plug
- Added reporting values for for Sercomm / Telstra SZ-ESW01-AU smart plug
=> Further enhancements and device integration

bindings.cpp, database.cpp, de_web_plugin.cpp, light_node.cpp, sensor.cpp
- Add support for Bitron Remote, see #2392;
- Add support (untested!) for Hue smart button, see #2077.
- Create group for Trådfri remote control and Trådfri wireless dimmer with new ZB3 firmware, see #2485.
@manup, @YKO-de, the wireless dimmer now supports group bindings, so the unicast binding to the coordinator is no longer needed.  Nor is turning the dimmer to trigger the creation of these bindings.  You might want to adapt the Phoscon wizzard for pairing the dimmer.
=> Bitron remote, Hue smart button

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_lights.cpp, rest_sensors.cpp, sensor.cpp
Improve handling of:
- Hue dimmer switch,
- Hue smart button (#2077),
- Lutron Aurora FoH dimmer switch (#2305),
- innr RC 110 (#635),
- icasa Remote (#1978),
- Xiaomi B1 curtain motor (#1654).
Details:
- Changed configuration of attribute reporting for the battery to match the Hue bridge.
- No longer get the group identifiers from the _ZLL Commissioning_ cluster.  Bluntly creating a group and binding the client clusters to it (as for ZigBee 3.0 devices) seems to work just fine for the Hue dimmer switch and the Hue button.  The Aurora doesn't support the _get group identifiers_ command.
- Expose innr RC 110 and icasa Remote as single ZHASwitch `/sensors` resource, with multiple (7 and 4) group IDs in `config.group`, see #2541.
- Added the switch endpoint to the `uniqueid` of the …
=> Hue dimmer, Hue smart button, Lutron Aurora, innr RC 110, icasa Remote, Xiaomi B1 curtain motor

de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp
This adds support for Sunricher window covering controller SR-ZG9080A cf.
https://sunricher.en.alibaba.com/product/62134471426-811954196/Zigbee_3_0_Zigbee_Curtain_Motor_Controller_Zigbee_Curtain_Controller_Smarthome.html
https://en.robbshop.nl/rollershutter-control-400w-zigbee-robb-smart?sqr=rollershutter%20controller&
=> Add generic support for Device ID 0x0203 "Window Covering Controller" (e.g. Sunricher SR-ZG9080A)

bindings.cpp
Fix a bug: ZCL specification requires to send a ZclDefaultResponse when this is requested by setting bit DisableDefaultResponse to False.
Part of issue #1261
=> Send ZclDefaultResponse when requested in ConfigureReportingResponse

bindings.cpp, database.cpp, de_web_plugin.cpp, general.xml, resource.cpp, resource.h, rest_groups.cpp, rest_lights.cpp, rest_node_base.cpp, rest_sensors.cpp, sensor.cpp, zcl_tasks.cpp
See #2475.
- Implement `state.on` / `state.bri` logic more like the Hue bridge, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1111#issuecomment-456464872.  Try setting something fun, like `{"on": true, "ontime": 100, "bri": 254, "transitiontime": 100}`;
- Implement parameter validation (both keys and values, as well as combinations) for body.  All parameters are checked before any action is taken, and validation continues after one error;
- Also adds support for setting `state.speed` for _Fan_ devices, like the Hampton Bay (see #932).
I've tested this on a Hue bulb and on a GLEDOPTO controller.  The latter doesn't turn on on _Move to Level (with On/Off)_, but it does set the level (even while the light is off).  The subsequent _On_ then turns the light on at level 2, …
=> Refactor logic for setting light state.

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, poll_manager.cpp
- Added support for Klik Aan Klik Uit ZTHS-100 (#2657)
- Added initial support for Sengled PAR38 bulbs (#2667, #2155)
- Updated Centralite thermostat model ID (#2630). Some versions do not contain the previously set "-E" at the end of the model ID
- Identified purpose of further Xiaomi specific attributes
- Expose voltage and current for Xiaomi smart plug lumi.plug.mmeu01 (#2583)
- Added initial support for Tuya smart plug (TS0121) (#2677)
- Added support for innr SP 220 smart plug (#2678)
- Added IAS ACE cluster to general.xml
- Added initial support for Heiman remote control HS1RC-M (#2697)
- Added support for Immax NEO ZB3.0 smart plug 07048L (#2688)
- Enable light bindings for additional manufacturers 
- Whitelist Xiaomi smart plugs with Xiaomi MAC address (#2583)
- Enable IAS warning …
=> Enhancements and addition of various devices

ikea-ota-download.py
Running the script inside a docker container with python 3.5 throws an "TypeError: the JSON object must be str, not 'bytes'".
Fixed it by decoding downloaded json to utf-8
=> Update json.loads line for python 3.5

bindings.cpp, database.cpp, de_web_plugin.cpp, general.xml, rest_sensors.cpp, zcl_tasks.cpp
See #1848, #1264
See SmartThings [groovy](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/smartsense-multi-sensor.src/smartsense-multi-sensor.groovy) file.
- Update `general.xml` with additional attributed for 0xFC02 (Samjin) cluster and add cluster for SmartThings (Physical) and Centralite manufacturer codes;
- Sensor actually exposes _Active_ attribute (0x0010) for `state.vibration`, so use that to reset vibration.  Remove `config.duration` and automatic reset by REST API plugin;
- Adjust attribute reporting;
- Add support for 2016 model `multiv4` by `SmartThings` (untested);
- Add support for vibration for Centralite variant (untested).
Additional bug fixes:
- Don't expose `state.ct` for Feibit color light. It exposes color temperature, but …
=> Samsung multi sensor

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, ias_zone.cpp, sensor.cpp
- Added initial support for Sercomm open/close sensor SZ-DWS04 (#2722)
- Prevent lumi.plug.mmeu01 creating wrong sensors in rare cases (#2583)
- Update for LifeControl MCLH-08 environmental sensor
- Refactor IAS zone enrollment
- Added initial support for RGBgenie ZB-5121 (#2732)
- Enhancements for RGBgenie ZB-5001 (#1256)
- Added initial support for Centralite 3323-G contact sensor (#2783)
- Allow binding for Xiaomi Mijia Smart Light Sensor lumi.sen_ill.mgl01 (#2300)
According to Zigbee spec (07-5123-06-zigbee-cluster-library-specification.pdf, 8.2.2.2.3 Implementation Guidelines), writing the IAS CIE address is mandatory to be done first in the enrollment process. Apparently, not much end devices seem to adhere to that, as an enrollment request is fired very early from those devices. …
=> Refactor IAS zone enrollment and further device integration

rest_lights.cpp
Re-enable setting `ct` for IKEA CWS light, even though the light doesn't support it.  See #2798 and discussion with @manup in #general on Discord.
Note that it would also be possible once again, to set `ct` on IKEA dimmable lights.  Not sure how the code would react to this.
=> Re-enable setting `ct` for IKEA CWS light.

rest_lights.cpp
Workaround for broken `deCONZ::ZclAttribute`: doesn't support `Zcl8BitEnum` either, see #932.
=> Hampton Bay fan module

de_web_plugin.cpp
Fix button handling for platforms with signed char:
- x003 for Xiaomi Aqara Opple (see #2061);
- 7002, 8002, 9002 for innr remote RC 110 (see #635);
- 1002 (sharp right turn) for IKEA dimmer (see #2787).
Not yet tested on x86 or other platform with signed `char`.
=> Fix button handling

bindings.cpp, de_web_plugin.cpp, sensor.cpp
Added support for the [Osram Switch Mini+](https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-zigbee-technology/smart-home-components/smart-switch-mini/index.jsp) and [Osram 4x Button](https://www.amazon.com/Osram-Lightify-Intelligent-Flexible-Operation/dp/B00YSXBROI) in collaboration with @Smanar 
* Up short / long press
* Middle (0) short / long press
* Down short / long press
* Battery reporting
* Upper-left short / long press
* Upper-right short / long press
* Lower-left short / long press
* Lower-right short / long press
* Battery reporting
resolves https://github.com/dresden-elektronik/deconz-rest-plugin/issues/294
resolves https://github.com/dresden-elektronik/deconz-rest-plugin/issues/374
resolves …
=> Add support for OSRAM Lightify 'Switch Mini' and 'Switch 4x' remotes

rest_groups.cpp, rest_lights.cpp
This PR adds support for `{"open": true}` and `{"open": false}` to a PUT to a group `action`, to generate _Window Covering_ cluster commands _Open_ and _Close_ to the group.  No checks whatsoever, that the group actually contains a _Windows Covering_ device.  Also, `open` is not exposed in the `action` object.
Works brilliantly with my `lumi.curtain` - haven't had a failed attempt yet (where unicast commands fails regularly due to routing issues).  Doesn't seem to work for my FYRTUR - not sure why the open/close controller works just fine.  Both FYRTUR and the controller have the same parent, though: a Hue light.
=> Quick & dirty support of Window Covering groups

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, resource.cpp, resource.h, rest_sensors.cpp, thermostat.cpp
- Expose system mode for Zen-01 thermostat
- Added additional mac prefix
- Appropriately round Xiaomi power values
- Adjusted Niko 170-33505 power reporting interval
- Appropriately round all power, voltage and consumption values
- Set manufacturer name to Namron AS for all devices starting with 451270
- Enable light bindings for Niko devices
- Corrected Niko specific attribute name in general.xml
- Added initial support for Sonoff SNZB-03 (MS01) (#2991)
- Added initial support for Sonoff SNZB-02 (TH01) (#3037)
- Added initial support for Sonoff SNZB-04 (DS01) (#3036)
- Updates to prevent exposure of power for consumption sensors
- Added initial support for Danfoss Ally (eTRV0100) (#2983)
=> Bugfixes and enhancements

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp
Using the Danalock v3 code update as base, updated to support Schlage Connect Smart Deadbolt B3468.
Tested and working with my lock.
=> Schlage Connect Smart Deadbolt B3468 Support

bindings.cpp, database.cpp, de_web_plugin.cpp, general.xml, light_node.cpp, rest_lights.cpp, sensor.cpp, sensor.h
- Amended battery reporting for EcoDim switches
- Correct button map for EcoDim switches
- Prevent Danfoss Ally to be queried unnecessarily for heating state
- Fixed some reportable change values for thermostats
- Add additional group bindings for RGBgenie ZB-5001
- Whitelist Hive MOT003 as presence sensor
- Restore RStateConsumption for analog input cluster on DB load
- Corrected "SW error code" attribute in general.xml
- Also consider Namron 4512721 ZB3.0 switch as supported device
- Added initial support for Xiaomi Aqara ZB3.0 Smart Wall Switch Single Rocker (lumi.switch.b1naus01) (#3083)
- Expose EcoDim and Namron switches as single ZHASwitch resource
- Added initial support for Bitron outdoor siren 902010/29 (#3092)
- Update to properly recognize Tuya/Blitzwolf BW-IS2 door/window …
=> Enhancements and fixes

.github/stale.yml, bindings.cpp, de_web_plugin.cpp, sensor.cpp, sensor.h
For https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2340
A hack is used for button 4, not a real button, but a scene memory in reality.
=> Switch from LDS

database.cpp
As discussed in dev channels, i figured we could remove the message:  don't close database yet, keep open for 900 seconds
=> Remove the don't close DB yet message

de_web_plugin.cpp, de_web_plugin_private.h
* Fix crash in case of large networks with over 300 light or 150 sensor nodes.
=> Fix SEGV in poll nodes container

bindings.cpp, de_web_plugin.cpp, de_web_plugin.h, de_web_widget.cpp, de_web_widget.h, de_web_widget.ui
* Don't list bridge and docker network interfaces
* Rename WebApp to Phoscon App
* Add keyboard shortcut Ctrl+B to read the binding table of the selected node
=> REST-API plugin dialog: Cleanup network entries and read binding table keyboard shortcut

poll_manager.cpp
When cluster to be polled is found, extend the check to also determine if an attribute is available. If not, they get discarded (mainly applicable for instantaneous demand attribute on simple metering cluster). Also, freshness of values is only checked on available attributes now.
=> Optimize poll manager to consider only avaliable attributes

database.cpp
This could happen when permit join value > 0 was stored in the database and
restored after application startup. In my setup this caused invalid light nodes created from devices which where actually sensors and switches.
This PR removes database store/restore of the permit join value which must be set
to 0 on each startup and can only be set by REST-API.
=> Fix network permit join set after deCONZ start

de_web_plugin.cpp, de_web_plugin_private.h, discovery.cpp, rest_configuration.cpp
* Replace Google App Engine endpoint by https://phoscon.de/discover.
* Raise default announce interval from 10 to 45 minutes.
* Don't use link local IPv4 addresses (169.254.x.x) as internal IP address.
* Duplicated and too old entries are now fixed in the server (not this PR).
=> Discovery service improvements

de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, firmware_update.cpp, rest_configuration.cpp
* Fix detection of ARM and AARCH64 platform.
* Don't disable update on headless desktop Linux based on DISPLAY environment variable.
* Don't use sudo when EUID is 0 (root user).
* Enable firmware update via Phoscon App again.
* GCFFlasher 3.14 now checks that after flashing the application firmware is up and running, and if not will retry the update process.
=> Firmware update improvements

bindings.cpp, de_web_plugin.cpp, sensor.cpp
Apparently, this is a different version of the remote. As it has different manufacturer name and modelID, it will be recognized during pairing, but would not issue any button events (#1256).
=> Added initial support for different version of RGBgenie ZB-5001

de_web_plugin.cpp
This PR adds the Tuya/Lupus mini temperature sensor with a changed MAC vendor ID and resolves #3263.
=> Add Lupus temperature sensor

de_web_plugin.cpp, rest_configuration.cpp
If `$HOME/.local/share/dresden-elektronik/deCONZ/devices/button_maps.json` exists, it will be used instead of the version installed with the deCONZ package.
=> Support user provided JSON button maps as well as default package installed version

bindings.cpp, de_web_plugin.cpp
Including this PR, the following modelIDs are known: "MS01", "MSO1" and "ms01".
=> Add support Sonoff SNZB-03 with different ModelIDs

README.md
@manup as per now: .78 is latest stable. Can we make .80 stable in the next release of the beta 81?
Just so we have a even roster?
=> Adding release schedule.

general.xml
Related to deCONZ core fix to load manufacturer specific attributes.
=> ZCLDB streamline hex value format, fix some attribute sets 

de_web_plugin.cpp
Some of the checks for Node Descriptor and manufacturer code weren't strict enough.
=> Prevent creating unwanted LightNodes (Danalock/Tuya)

de_web_plugin.cpp
The former PR detects Hut Tab as PTM215ZE due the same payload size of 27.
The sourceID hopefully detects PTM215ZE, but isn't tested yet.
=> Check PTM215ZE Ilumra via sourceID prefix

de_web_plugin.cpp
This supersed battery state icons used via ZDP PowerDescriptor, which most often don't work.
=> Show battery icons in deCONZ GUI based on ResourceItem battery state

button_maps.json
For the Opple switches (and presumably also the wireless dimmer), any button event x0003 was missing due to an incorrect value conversion. Additionally, the dedicated Opple model IDs have been added.
=> Fix for Aqara Opple switches and Ikea wireless dimmer

poll_manager.cpp
lightNode pointer wasn't guarded to check for nullptr in RStateOn handler.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3427
=> Fix SEGV in poll manager

bindings.cpp, rest_rules.cpp
IKEA lights add a implicit bindings of Basic Cluster for each group they are in including default group 0xfff0. For some lights there are up to 4 Basic Cluster bindings (perhaps even more). deCONZ additionally adds a unicast binding. The group bindings can't be removed as the result status asserts "No Entry".
The attribute was configured to report every 30 minutes, resulting in multiple group casts which is quite heavy and might cause negative side effects. As a side note Xiaomi mains powered switches also have the default group 0xfff0, it's not clear yet if they are related.
This PR disabled reporting of attribute 0x4000 and falls back to simple ZCL read attribute command.
=> Disable reporting of SwBuildId for IKEA lights

general.xml
The Door Lock cluster attributes aren't using manufacturer specific code.
Since a stricter check is used for these in 2.5.86 they didn't trigger attribute events.
Issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3455
=> Fix Xiaomi vibration sensor

de_web_plugin.cpp
In some cases a Add Scene command was never sent, causing a scene not to be created after 3 times trying to read the scene.
Story behind this: My 4x IKEA GU10 color temperature lights corrupted 4 scenes after an OTA update. The scenes were still there but the colorY field was no longer part of the scene, only on, bri and colorX.
To fix the scenes:
1) Execute Remove All Scenes for the group
2) Executed Get Scene Membership for the group
After that the plugin started to recreate the scenes via Add Scene command, but on two lights only 3 out of 4 scenes were created. This commit fixed the remaining ones and all scenes work again.
=> Handle case when view scene returns no entry status

poll_manager.cpp
Due OTA updates the version attribute may change.
=> Periodically poll SwBuildId for IKEA, OSRAM and Philips

de_web_plugin.cpp, general.xml, rest_lights.cpp
- Add 0x8000 attribute to _On/Off_ cluster for `lumi.sensor_switch.aq2`, see #3480;
- Whitelist `Zigbee CCT Downlight` _Color Dimmable Light_ by ETI to expose `ct`, see #3493;
- Whitelist `Halo_RL5601` _Color Dimmable Light_ by Eaton to expose `ct`, see #3509.
- Expose `colorcapabilities` as an array, instead of raw bitmap value, see Discord #technical-talk channel.
```json
{
"colorcapabilities": [
"ct",
"effect",
"hs",
"xy"
],
"ctmax": 500,
"ctmin": 153,
"etag": "7d7845fe999a26bf7a034b110a424393",
"hascolor": true,
"lastseen": "2020-10-25T19:36Z",
"manufacturername": "Philips",
"modelid": "LCT015",
"name": "Hue",
"state": {
"bri": 254,
"colormode": "hs",
"ct": 447,
"effect": "none",
"hue": 0,
"on": false,
"reachable": true,
"sat": 100,
"xy": [ …
```
=> Various small bug fixes and enhancements

de_web_plugin.cpp, rest_sensors.cpp
* The RStateButtonEvent should only be set by the button map handler;
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3480
* Disable bogus debug output for coordinator events in sensor search.
=> Fix Xiaomi round button WXKG01LM long press event

resource.cpp, resource.h
* Fix memory leak in ResourceItem copy assignment, previous string wasn't deleted;
* Add move constructor and move assignment operators for performance;
* Replace ResourceItemDescriptor for each item by const pointer to original;
* Add asserts to enforce valid state;
* Move invalid string out of string vector, since only one item was used anyway.
=> Resource and ResourceItem ctor and assignment improvements

bindings.cpp, database.cpp, de_web_plugin.cpp, rest_sensors.cpp
- Add "mode" command to bitron thermostat.
- Corrective for a konke temperature sensor.
- Guard against empty simple descriptors.
Nothing special
=> Add "mode" command to bitron thermostat

de_web_plugin.cpp, de_web_plugin_private.h
No need to create that largish object for each indication if it isn't used anyway.
=> Remove unused TaskItem from cluster indication handlers

bindings.cpp, database.cpp, de_web_plugin.cpp, general.xml, rest_sensors.cpp, thermostat.cpp
- Enable group creation for Sonoff SNZB-01 (#3490)
- Unify debug output for button presses
- Remove MFC check for Elko Super TR attribute reports (#3123)
- Expose RConfigMode and correct attribute for Elko Super TR (#3123)
- Fix typo to create only 1 switch resource for Namron switches
- Make RConfigMode usable for Elko Super TR to turn device on/off (#3123)
- Remove thermostat mode binding for Elko Super TR (#3123)
- Enable battery attribute reporting for SZ-DWS04 (#3576)
- Added missing "windowopen" value for Danfoss TRV (#3591)
- Guard against empty simple descriptors
=> Small enhancements

rest_sensors.cpp
This pull request fixes issue # 1098. 
In short: some newer versions of the Eurotronic Spirit Zigbee thermostats do not accept updating the manufacturer specific attribute 0x4003 when changing the current heating setpoint. These models only accept the standard 0x0012 attribute, Occupied Heating Setpoint. 
For backward compatibility sake a check is added to compare the current software version. If this is lesser than 22190903 the old attribute (0x4003) is written to, otherwise the value is written to 0x0012 (without a specific vendor code).
=> Fix updating heatpoint for newer Eurotronic Spirit Zigbee thermostats

de_web_plugin.cpp
The problem was that periodic polling of the attribute was triggered endlessly because the last query time stamp was never updated.
lightNode->setSwBuildId(str) was removed because item->setValue(str) does the same and faster since item is already known.
=> Fix refreshing SwBuildId last set time stamps

bindings.cpp
The initial approach to use the settings from the IKEA gateway results in a huge amount of rapid reports during state transitions. The lights are sending reports for every tiny change especially for Level and Color  Control clusters.
This commit ensures that there are at least 5 seconds between two reports for an attribute. For color temperature lights reporting of ColorXY attributes is disabled (these need more logic to be handled properly).
=> Relax IKEA lights reporting configuration

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_sensors.cpp
```checkMacVendor(sc->address, VENDOR_X)``` is not exclusive, and while it evaluates as true for VENDOR_X, it might evaluate as true for VENDOR_Y as well.
This creates a problem in ```void DeRestPluginPrivate::delayedFastEnddeviceProbe(const deCONZ::NodeEvent *event)``` when deciding whether to skip getting additional attributes (such as modelId and manufacturer).
Since getting additional attributes is skipped, adding a node fails later on, and it is not exposed to the API. Note that this only happens when adding a new node, but not if a node is already paired.
I suspect this might also be relevant for issue #3482 and maybe other issues related to pairing new devices.
Finally, I'm not sure whether ```checkMacVendor``` in general is expected to evaluate as true for multiple vendors for the …
=> Fix too broad mac check that prevents from pairing

de_web_plugin.cpp
A stricter check to only apply filter for the Trust remote.
In addition to PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3525
=> More specific detection of Trust remote (ZYCT-202)

rest_lights.cpp
It's a breaking change which needs to be in beta version.
Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3496
=> Revert colorcapabilities change, needs to be in beta v2.6.x

bindings.cpp, database.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, fan_control.cpp, general.xml, resource.cpp, resource.h, rest_sensors.cpp, thermostat.cpp
- Add initial support for Owon AC201 Thermostat
- Introduce `fan_control.cpp` to accomodate AC fan control for thermostats
- Introduce `RConfigFanMode` to set AC fan mode
- Introduce `RConfigSwingMode` to set AC louvers position
=> Add initial support for Owon AC201 Thermostat [02]

README.md, bindings.cpp, button_maps.json, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, light_node.cpp, resource.cpp, resource.h, rest_lights.cpp, rest_sensors.cpp, sensor.cpp, tuya.cpp
- Remove my try to filter VENDOR_EMBER device, solve https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3424
- Correction for Moes HY368 and Tuya TS0601 thermostat (30 degree bug), solve https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3440
- Add Tuya Essentials Premium thermostat https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3381
- Add Tuya BTH-002 thermostat https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3304
- Add Saswell SEA801-Zigbee TRV https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3109
- Add Revolt NX-4911-675 thermostat https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3588
- Re adding Tuya / Zemismart switches TS0041, TS0042, TS0043, TS0043, TS0044 removed by error from another PR …
=> Tuya thermostat and switch improvements, Kwikset 914 smart lock

bindings.cpp, rest_lights.cpp, window_covering.cpp
- Improve support of Legrand Bticino Living Light L4027C (Shutter SW with level control)
Handle inverted lift values.
- Improve Legrand covering support  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2812
Some device have different firmware support.
=>  Legrand Bticino Living Light L4027C

bindings.cpp, database.cpp, de_web_plugin.cpp, fan_control.cpp, rest_sensors.cpp
Improve support for Centralite pearl thermostat (3157100) (#3240)
- Enable and add attribute reporting
- Expose `RConfigCoolSetpoint`, `RConfigLocked`, `RConfigMode` and `RConfigFanMode`
=> Improve support for Centralite pearl thermostat (3157100)

button_maps.json
- Swap button maps for Sunricher switches ZGRC-KEY-007 and ZGRC-KEY-009 (#3397)
=> Swap button maps for Sunricher switches ZGRC-KEY-007 and ZGRC-KEY-009

database.cpp, de_web_plugin.cpp, fan_control.cpp, rest_sensors.cpp
Improve Zen thermostat support to enable cooling control (#3382)
- Rely on attribute reporting
- Expose `RConfigCoolSetpoint`, `RConfigMode` and `RConfigFanMode` via API
=> Improve Zen thermostat support to enable cooling control

air_quality.cpp, bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, general.xml, resource.cpp, resource.h
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3538
This also adds the numeric air quality value in (ppb) to Develco air quality sensor.
Loudness sensor not yet included, will be added later.
The battery state doesn't seem to carry a valid value not does the cluster support reporting.
```
{
"config": {
"on": true,
},
"ep": 2,
"etag": "2e340ae4cd2a88ef53c1cb38cc9f224f",
"lastseen": "2020-11-15T19:23Z",
"manufacturername": "BOSCH",
"modelid": "AIR",
"name": "Air quality sensor",
"state": {
"airquality": "moderate",
"airqualityppb": 484,
"lastupdated": "2020-11-15T19:23:03.296"
},
"swversion": "20200402",
"type": "ZHAAirQuality",
"uniqueid": "00:12:4b:00:14:4d:eb:87-02-fdef"
}
```
Other standard sensor resources which are exposed are: ZHATemperature, …
=> Initial support BOSCH Air quality sensor

general.xml
* Use proper hex values;
* Add IKEA specific scene attribute in groups cluster.
=> ZCLDB Level Control cluster fixes, IKEA scene attribute

de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp, rest_groups.cpp, rest_lights.cpp
- Always pick the largest supported version;
- Support headers with multiple versions;
- To add more versions simply extend the array.
The `getAcceptHeaderApiVersion()` is a pure function for easier testing later on.
For clients which support `vnd.ddel.v1` or don't provide an API version this won't be a breaking change and `colorcapabilities` still returns a number. Clients which support `vnd.ddel.v1.1` need to support `colorcapabilities` as array.
Related PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3642
=> Improve HTTP accept header parsing of API versions; Reintroduce colorcapabilities in API version v1.1

database.cpp, de_web_plugin.cpp, resource.h, rest_sensors.cpp
This PR ensures the magic attribute to enable button events is written in the hourly report, and at least once per deCONZ start.
After startup writing the attribute can be enforced by pressing the 'C' button on the back of the switch.
There was also another issue when the switch is paired a simple descriptor request loop could happen, this is fixed in deCONZ core now.
Issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3670
=> Improve setup of Aqara Opple switches

de_web_plugin.cpp, event_queue.cpp, reset_device.cpp
- Enable APS ACKs for ACtive Endpoints and Simple Descriptor requests;
- When a device was paired previously it could have happen that during pairing it was forced to leave the network;
- Add INFO_L2 debug print to trace emitted events.
=> Improve end-device pairing

de_web_plugin.cpp, rest_lights.cpp, tuya.cpp
This code is used to make fake device for wired switches.
Need to be skipped for light device.
=> Avoid fake device creation for TUYA light 

air_quality.cpp, bindings.cpp, de_web_plugin.cpp, general.xml, ias_zone.cpp, light_node.cpp, rest_lights.cpp, rest_rules.cpp, rest_sensors.cpp
- Whitelist yet another Sonoff SNZB-02/SNZB-03 modelID (#3713)
- Restrict rule name length during rule creation (#3727)
- Reenable polling for Bitron 902010/32 thermostat
- Correction in air quality scale
- Update for Develco SPLZB-131 power values
- Allow clearing the alarm bit for Develco devices (#3272)
- Ease Develco modelID checks to include newer models
- Add Opple switch mode attribute to LUMI cluster (#3670)
- Suspend RConfigCoolSetpoint type check (#3382)
=> Enhacements and improvements

de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp, resource.cpp, rest_lights.cpp, tuya.cpp, xmas.cpp
This PR adds REST API support for the LIDL Melinera Smart LED strip, a.k.a. the Xmas light strip, see #3716.
I've implemented the following changes:
- Created `xmas.cpp` with exposes the following public methods:
- `DeRestPluginPrivate::isXmasLightStrip()` to check whether a `LightNode` is, in fact the Xmas light strip;
- `DeRestPluginPrivate::setXmasLightStripState()` to handle a PUT to the state of the Xmas light strip;
- `DeRestPluginPrivate::addTaskXmasLightStrip...()` to queue tasks for _Tuya_ cluster of the Xmas light strip;
- Created the following public enums:
- `XmasLightStripMode`;
- `XmasLightStripEffect`;
- Changed `RStateEffect` back to `DataTypeString`;
- Added a hook in `DeRestPluginPrivate::setLightNodeCapabilities()` to delete unsupported `state` attributes, which are …
=> Merry Christmas!

database.cpp, de_web_plugin.cpp, general.xml, read_files.cpp, rest_sensors.cpp
- Re-enable typ check for RConfigCoolSetpoint
- Remove unsupported config parameters for Danfoss/Hive thermostats (`RConfigSchedule` and `RConfigScheduleOn` got created while loading the sensor from DB without the device supporting it)
- Some cleanup for thermostat capabilities (re-order the entries, remove `RConfigMode` duplicate for Zen and prevent ELKO Super TR to expose `RConfigSchedule` and `RConfigScheduleOn`)
- Additions for Xiaomi specific cluster
- Update for Xiaomi special reporting output
- Add Sinope specific clusters/attributes to general.xml (#2104)
- Process Konke motion sensor battery reports (#1607)
- Further additions for Xiaomi special reporting output
- Ensure button map is only loaded once
=> Various fixes

de_web_plugin.cpp, de_web_plugin_private.h, green_power.cpp, green_power.h, permitJoin.cpp, rest_sensors.cpp
- Send GP Pair command to at most 3 proxies, which report at least moderate LQI for the GPD;
- Send GP Proxy Commissioning Mode only while Permit Join is set;
- Add logging for LQI/RSSI of received proxy notifications.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/436
=> Fix ZGP proxy pairing

database.cpp, de_web_plugin.cpp, poll_manager.cpp
- Fill the data from endpoint 0x01, which is the only valid Basic Cluster, into endpoints 0x02 and 0x03;
- Use Basic Cluster application version attribute for `swversion`;
- Don't endlessly read empty string attributes in poll manager.
=> Lidl plugs fill manufacturername, modelid and swversion for all endpoints

rest_sensors.cpp
Wait for IAS Zone status, the sensor doesn't update presence if in activated state.
In future we should configure reporting for Zone status.
=> Lidl motion sensor (TY0202) don't reset presence

discovery.cpp
Current versions of deCONZ are much newer than the announced version and since it was a simple compare not equal it always showed an update was available.
Changed it so only if a newer version is announced an update is shown.
=> No updates if current version is newer than announced version.

discovery.cpp
- Don't run discovery while update is in progress;
- Add versionToIntList() and remoteVersionIsNewer() for easier testing and readability.
This builds on top of PR #3675
=> Refactor remote update version check

button_maps.json, de_web_plugin.cpp, sensor.cpp, tuya.cpp, tuya.h
- The missing break, did load all entries which started with a modelid. So lumi.sensor_switch.aq2 was overwritten by lumi.sensor_switch;
- Prevent single press button event to be emitted twice for lumi.sensor_switch.aq2;
- Don't use `QString::startsWith()` always require exact modelId;
- Put manufactuer name of Tuya switch in button map and use it as modelId;
- Add helper `isTuyaManufacturerName()` to detect Tuya devices.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3719
=> Fix ambiguous loading of button maps

bindings.cpp, button_maps.json, de_web_plugin.cpp, read_files.cpp, xmas.cpp
=> LIDL remote, Trådfri shortcut button

rest_lights.cpp, window_covering.cpp
The support change according to version https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3876
> 0x0B > need reverse (code reverse) WORKING (dpmworld with bticino)
> 0x16 > No need to reverse (code reverse) NOT WOKING (zinoalex with bticion)
> 0x1A > need to reverse (code reverse) WORKING (samsam-rolon with Legrand)
> 0x1C > No need to reverse (code reverse) NOT WOKING (zinoalex with bticion)
> 0x21 > No need to reverse (code don't reverse) WORKING (samsam-rolon with Legrand)
=> Improve Legrand Shutter support.

button_maps.json, button_maps.schema.json
- Explicitly state model identifiers;
- Split into one map per switch to improve documentation and clearly state what a certain switch supports.
=> Fix iCasa Pulse 2, Pulse 4S and Pulse 8S button maps

database.cpp, de_web_plugin.cpp, general.xml, rest_sensors.cpp, thermostat.cpp
- Updates on manufacturer specific cluster
- Change the command to set the heatpoint. so the device instantly reacts by opening/closing the valve (#3927)
- Enabled on-device schedules (as supported with firmware version 1.08) (#3699)
=> Enhancements for Danfoss Ally

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, ias_zone.cpp, resource.cpp, resource.h
Short description (for now):
- Streamline coding with other clusters
- Ensure to always pick the right sensor containing IAS cluster
- Significantly increase verbosity
- Catch attribute read requests which were silently discarded and retry until success
- Catch failed IAS CIE address write requests and retry until success
- Based on the 2 aforementioned enhancements, drastically improve IAS enrollment
- IAS enrollment is checked and initialized (if required) upon full attribute read
- Expose `config.enrolled` to provide IAS enrollment transparency via REST API
- Check enrollment status upon reception of IAS zone status notifications and set `config.enrolled` to "true" if enrollment is confirmed to be successful
=> Refactor of IAS zone cluster handling to improve robustness

de_web_plugin.cpp, poll_control.cpp, rest_sensors.cpp
This should also fix draining battery of Samsung SmartThings devices, which do MAC Data Polling every 5–10 seconds if not configured otherwise.
In general devices which contain an Poll Control cluster will be configured as well.
Issues: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2908 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4130
=> Fix Poll Control cluster configuration

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h
Align with original SmartThings configuration
* Report battery state every 6 hours instead 5 minutes;
* Samjin muli sensor open/close reporting set to 1 hour instead 5 minutes;
* Samjin muli sensor orientation reporting set to 1 hour instead 5 minutes;
* Further, align with ZCL spec and use manufacturer code in ZCL Default Response when the request was manufacturer specific.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4131
The main battery safer comes via Poll Control configuration PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4163 formerly SmartThings devices did MAC Data Polling in very short intervals, sometimes every 5–10 seconds. With the PR this interval is raised to 15 minutes.
=> Improve Samjin multi sensor and Samjin battery reporting

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, light_node.cpp, rest_configuration.cpp
Currently, the period for updating `lastseen` is fixed to 60 secs and if the actual timestamp is older, the value is updated, emitting a websocket event for `/light` resources. By introducing `lightlastseeninterval` for the REST API gateway configuration, this value is now configurable between 1 and 655535 seconds, keeping the default of 60 seconds.
=> Allow throttling of `lastseen` updates

de_web_plugin.cpp
This adds the silabs3MacPrefix prefix on mac address for the Lidl/Silvercrest Smart Window or Door Sensor (`TY0203`) to add it as supported device.
Some details on my sensor with mac address `ec:1b:bd:ff:fe:95` (via the zll.db sqlite3 db):
```
ZHAOpenClose|TY0203|SILVERCREST|ec:1b:bd:ff:fe:95:4d:e7-01-0500|
```
Thus making it not part of the supported silabs7MacPrefix prefix (`0xbc33ac0000000000ULL`). This PR makes sure this device is supported so I can add this Silvercrest/Lidl sensor without issues to the list of sensors in Deconz.
=> Add silabs3MacPrefix for Lidl/Silvercrest Smart Window or Door Sensor

de_web_plugin.cpp, de_web_plugin_private.h
In some cases like database read/writes the QTimer callback was called too early.
This could mess up time based triggering of rules.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4106
=> Prevent too early idle timer callback

resource.cpp, resource.h, rest_sensors.cpp, sensor.cpp, sensor.h
* Prevent duplicated Websocket push events;
* Fix skipped Websocket push events when time stamps don't align due system time changes.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3707
=> Make sensor Websocket push logic independent from absolute time stamps

database.cpp, resource.cpp, resource.h
Helper for devices with cryptic manufacturer names and modelId.
This allows matching for more readable productId:
```cpp
if (R_GetProductId(sensor) == QLatin1String("SEA801-ZIGBEE TRV"))
{
}
```
This is only an initial PR, the table will be filled in further PR's.
=> Add initial product identifier map

de_web_plugin.cpp, ias_zone.cpp
Proposed fix avoid possible segfault by wrong type of argument supplied to DBG_Printf, expected int (got wide-int?),
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3611#issuecomment-761917726 for details
I'm pretty sure it is not the single place where it is used in same way, but have no time at the moment to check whole codebase.
FWIW, it is doubtful (at least not advisable) to use printf without check of argument types, let alone the arguments declared as auto-variable supplied without cast, etc.
=> Fix possible segfault by wrong printf argument type

rest_lights.cpp, tuya.cpp, window_covering.cpp
Direction problem https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3757#issuecomment-751828899
This PR reverse the motor direction compared to native one. Thery are using classic covering cluster (not the tuya one)
Model TS130F Tuya Zigbee Curtain module QS-Zigbee-C01 : _TZ3000_vd43bbfq
Tuya covering switch : _TZ3000_xzqbrqk1
Edit:
Tested, working mode ok.
=> Tuya covering direction correction for models "Tuya Zigbee Curtain module QS-Zigbee-C01" and _TZ3000_xzqbrqk1  (covering switch)

de_web_plugin.cpp, general.xml
- Add support for Hue dimmer switch (2021 model, RWL022), see #4287;
- Add _Manufacturer Name_/_Model Identifier_ translations for LIDL Livarno Lux light bar (Lichtleiste) and mood light (Stimmingsleuchte), see #4248;
- Add _Manufacturer Name_/_Model Identifier_ translations for LIDL Xmas lightstrip.
=> Hue dimmer switch (2021), Livarno Lux lights

de_web_plugin.cpp, de_web_plugin_private.h
Only whitelisted lightnodes were previously allowed to get rx() updated. This is now generally allowed, but only whitelisted devices get `RStateOn` updated based on special reporting.
Xiaomi cluster has been added as well (XIAOMI_CLUSTER_ID) and is now taken into account for sensor creation
References #2583 #4139 #4238
=> Fix for Xiaomi lightnodes not getting a proper rx()

ias_zone.cpp, rest_sensors.cpp
The hereby removed `config.pending` "mode"  was exposed to the REST-API in 98a6217 but provides currently no value and causes confusion.
=> Don't expose config.pending "mode"; remove nonsense IAS debug logging for non IAS devices

authorisation.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_configuration.cpp
Without this command-line deconz argument option the basic config (without a user/api-key) isn't hue-compatible as the mode is normally based on the api-key. That seems to hinder initial hue-app pairing sometimes.
=> Add option to enable hue-mode as a deCONZ argument

de_web_plugin.cpp, rest_lights.cpp, tuya.cpp
Add new device > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4132
Working but for the moment the api create 2 fake device for it, (this code part is used for switches and no way to differentiate them).
=> Tobular Motor Zemismart ZM25TQ

bindings.cpp, de_web_plugin.cpp
Adds support for the new door bell device, which shows up as a IAS Zone 'Contact Switch' device.
After these changes deconz emits the correct events, but it doesn't show up in Phoscon, is that expected behavior?
=> Add support for Lidl/Silvercrest door bell (TS0211)

database.cpp, de_web_plugin.cpp, general.xml, resource.cpp, resource.h, rest_sensors.cpp, thermostat.cpp
Allows for setting an externally-measured temperature value via the REST
API. Useful for those of us who have radiators under desks or covered by
radiator covers.
=> Add API config "externalsensortemp" for Danfoss Ally thermostat

de_web_plugin.cpp, rest_lights.cpp, tuya.cpp
Ok no not sure for model name but probably "Zemismart Chain Roller Shades Driver (Model M515EGB)".
Battery powered device, using tuya cluster for covering, see > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4071
Have added too a new generic tuya covering too (_TZE200_nogaemzt), no more information https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4288 (Not tested)
=> Add initial support for MoesHouse / Livolo Roller Blinds

bindings.cpp, de_web_plugin.cpp, general.xml, thermostat.cpp
Resolves #4273 
The device is a bit tricky to join. It's basically a bridge exposing each In-Room Thermostat in a Danfoss Icon floor heating controller as an endpoint. It takes a while for all the simple descriptors and clusters to be read (the Danfoss literature suggests up to 3 minutes), so the process sometimes fails in Phoscon. I've had success by starting the "Add Sensor" process in Phoscon, and then manually reading the "Node Descriptor" and "Simple Descriptors" in the GUI, once a node for it shows up, followed by manually reading the Basic cluster for each endpoint. The bindings aren't setup reliably - I wonder if it has something to do with the device taking so long to setup.
The REST API exposes the sensor nodes correctly, but they don't show up in the sensor list in Phoscon …
=> Add basic support for Danfoss Icon Zigbee Module

bindings.cpp, de_web_plugin.cpp
=> Add initial support for Eria Adurosmart Wireless Dimming Switch

database.cpp, poll_manager.cpp
No need to filter attributes per device, if attributes aren't available they won't be read a second time, as this is checked later on.
Fixes Blitzwolf BW-SHP13 ZHAPower sensor updates.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3788
=> Fix Electrical Measurement cluster readings

button_maps.json, de_web_plugin.cpp, general.xml, rest_lights.cpp, rest_sensors.cpp
- Correct data type typos in general.xml
- Use dedicated modelID ZG2833K8_EU05 in button_maps.json (#4439 #4429)
- Add some missing etag updates (#4451)
- Relocate code for RConfigSwingMode to actually be considered (#3374)
- Don't cast power values for Instantaneous Demand
- Enable Develco SIRZB-110 to emit audio using state.alert (#4432)
- Add PIR Unoccupied To Occupied Threshold to general.xml
- Fix button events for Sengled E1E-G7F switch (#4413)
=> Various smaller bugfixes

database.cpp, de_web_plugin.cpp, resource.cpp, resource.h, rest_sensors.cpp, thermostat.cpp
Allows for manually signaling to the thermostat that windows in the room where it's located have been opened. Useful for helping the built-in logic enter "window open" mode when the thermostat is not situated directly under a window.
=> Add API config "externalwindowopen" for Danfoss Ally thermostat

bindings.cpp, de_web_plugin.cpp
=> Add initial support for Envilar ZGR904-S remote

.github/ISSUE_TEMPLATE/device-request.md
Following up from #4469.
When requesting device support for a new light, it wasn't clear to me what cluster screenshots are actually required.
I think we can simplify this by adding headings for each cluster (for easy anchors to links to each cluster screenshot), and then declare in comments for each one if or when it's required.
Could someone point me to other docs or post what clusters are required for what device types?
=> Add subheadings for each cluster in the device template

bindings.cpp, de_web_plugin.cpp
See #4403
When support has been added, you should enter sensor search in Phoscon and pair the device. However, you also need to keep an eye on deconz GUI for the device to show up, as the manufacturer name and model ID might not be read automatically. When it appears in deconz GUI, you need to read the basic cluster's attributes while sensor search is still running (which is the case even when Phoscon already issued the greenish success message) for the sensor resource to be created.
=> Add initial support for ORVIBO open/close sensor SM11

resource.cpp, resource.h
- Remove duplicated code by reusing `Resource` and `ResourceItem` move assignment operator in move constructor;
- `ResourceItem::rulesInvolved()` return by const reference rather when copy the `std::vector<int>`.
=> Resource code simplify

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h
- Make it a free standing function, since there is no Database class yet. This is a forecast to remove database code dependency of the plugin, which will ultimately result in a proper testable Database class;
- Remove sqliteGetAllSensorIdsCallback() dependency from plugin class;
- Make `sensorIds` a local variable since it's only used here;
- Modernize code and and reduce unperformant code paths;
- Ensure new sensor ids only grow, don't reuse sensor ids which where formerly deleted.
Code has been tested in debugger for various cases.
The PR also fixes that formerly deleted sensor ids from the database were reused under certain conditions. Which was the whole point to actually access the database in this function, but it never worked. I'm not sure if this is too useful other than to …
=> Refactor getFreeSensorId(); fix reuse of deleted sensor ids

bindings.cpp, button_maps.json, de_web_plugin.cpp, general.xml
- Add support for IKEA STYRBAR, see #4572.
- Whitelist device in `de_web_plugin.cpp`;
- Add commands to `button_map.json`;
- Hack in `checkSensorButtonEvent()` to ignore additional commands on holding left or right button (see issue);
- Streamline code for SHORTCUT and SYMFONISK, in line with STYRBAR:
- Only bind _OnOff_ client cluster to group;
- Discard unicast from client cluster to prevent double button events;
- Fix bugs in verifying bindings/reporting;
- Remove unneeded code for binding SYMFONISK to coordinator, as it sends commands to coordinator already by default.
- **TODO**: Check older IKEA end devices for double button events (haven't seen any reports, so don't expect any;
- **TODO**: Check whether old wireless dimmer (with dial) sends commands to coordinator by default as …
=> IKEA STYRBAR and Minor changes

de_web.pro
Will be used to fix depreacted warning after Qt 5.14
=> Add SKIP_EMPTY_PARTS define for QString::split()

database.cpp, de_web_plugin.cpp, light_node.cpp
Especially for Tuya devices, preservation of the given manufacturer name for lights and sensors is required to have the devices set up correctly. For sensors, this is quite easily done, however, for lights, this requires to step away from assigning the manufacturer name based on the manufacturer code.
=> Stop Tuya devices getting Heiman as manufacturer name

de_web_plugin.cpp, sensor.h
* Limited to IKEA and Tuya devices (also LIDL) to discard duplicated commands;
* For all other devices a warning is printed so we can track the issue;
* Sensor.previousSequenceNumber changed to uint16_t with initial value 0xffff to not accidantly discard valid commands.
This PR is successor for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4265 but only addresses the duplicate switch events.
The whole ZCL Default Response needs to be fixed at a higher level for all handlers in a separate PR.
=> Button events check for duplicated sequence number (IKEA, Tuya and LIDL)

de_web_plugin.cpp, green_power.h
Treated as Friends of Hue switch, but this module works differently as the known FoH switches when parsing messages.
No test done yet if and how it works with the Philips Hue bridge.
Therefore the `modelid` and `manufacturername` might need to change in future versions.
**Button Events**
x is the button number 1...8
x000  Initial press
x001  Hold
x002  Short release
x003  Long release
=> Initial support for ZGP PTM216Z switch 

de_web.pro
Compared to C++11 it brings mainly some improvements for lambda `auto` deduction and `constexpr`.
Since we still support Raspbian Stretch C++17 isn't in reach until 2024.
=> Raise C++ version to C++14

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, reset_device.cpp, rest_devices.cpp, rest_devices.h
The new `deleteDevice(extAddress)` function has following side effects:
- Delete all related Sensor and LightNodes;
- Delete device related entries from database;
- Send ZDP Mgmt_Leave_req to device to remove it from network (also sleeping end-devices).
Coming with v2.11.0 this can be invoked from the GUI via <key>Delete</key> key or node context menu.
=> Support delete device and its REST resources

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h
=> Add initial support for D-Link DCH-B112 door/window sensor

bindings.cpp, database.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, rest_devices.cpp, rest_sensors.cpp, utils/utils.cpp, utils/utils.h
Since the function doesn't use any members of plugin it can be free standing. And other modules which use it don't need to depend on plugin.
Nothing fancy just removing dependency on plugin.
=> Add utils module; move generateUniqueId() into it

de_web_plugin.cpp, de_web_plugin_private.h
- Removal of duplicate MAC prefix entries.
- Rename ikeaMacPrefix and danalockMacPrefix as silabs1MacPrefix
- Use celMacPrefix for keenhomeMacPrefix
=> MAC prefix hygene

de_web_plugin.cpp, linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh, linux/deCONZ/usr/bin/deCONZ-homebridge.sh
Updated homebridge hue version and dependencies.
Set correct "hosts" parameter in homebridge hue config for version > 0.13.2
=> Updated Homebridge Hue deCONZ

bindings.cpp, database.cpp, de_web_plugin.cpp
- Whitelist for binding
- Calculate the correct power values
- Do not expose current and voltage
=> Fix for Xiaomi Aqara Single Switch Module T1 (With Neutral)

poll_manager.cpp
This should generally be allowed for Tuya devices as well. The code handles any non-existance, so no polling will occur if the on/off cluster doesn't exist.
=> Allow Tuya devices to poll onOff attribute

de_web_plugin.cpp
Use reported on/off state via Xiaomi special reporting for light resources . Those will be treated as reqular on/off reports from the corresponding cluster. That aids in reducing polling as special reporting occurs on a regular basis in contrast to standard reporting of the typical clusters.
=> Limit polling on/off by using Xiaomi special reporting

bindings.cpp, button_maps.json, de_web_plugin.cpp, de_web_plugin_private.h
SLC S57003 is produced by Sunricher, identical to Namron 4512703 and others. 
See issue #4544, device request "SLC SmartOne S57003 - Wall 4xMono"
=> Add support for SLC S57003 4 channel remote switch, issue #4544

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, resource.cpp, resource.h, rest_sensors.cpp, thermostat.cpp
- Expose `RConfigCoolSetpoint`
- Introduce `RConfigControlSequence` to API for usage with thermostats
- Correct wrong data type in occupied heating setpoint reporting
=> Enhancements for Bitron thermostat 902010/32

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_sensors.cpp, simple_metering.cpp
=> Expose RConfigInterfaceMode for Develco EMI Norwegian HAN

de_web_plugin.cpp
Access to `sensor->node()` wasn't checked for nullptr and could crash when a button was pressed for a sensor which doesn't have the node set.
- SEGV since v2.11.0  PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4627
- Related issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4766
=> Fix SEGV on button press without deCONZ::Node available

de_web_plugin.cpp, de_web_plugin_private.h
This function provides the ability to choose a sensor more precisely than both functions `getSensorNodeForAddressAndEndpoint()`. The first implementation (which doesn't use the sensor type as argument) returns the first sensor found, which is problematic if more than one "sensor-worthy" cluster is available on one endpoint. The second implementation (which uses the sensor type as argument) is more accurate, but can only handle one sensor type (e.g. there's multiple sensor types based on IAS zone cluster).
The proposed function would eliminate both weaknesses, however, it relies on the correctness of a sensor's fingerprint. In this regard, some minor updates on the corresponding code might be required.
Presumably, the following code passage could be removed as a consequence as well: …
=> Introduce getSensorNodeForAddressEndpointAndCluster()

de_web_plugin_private.h, electrical_measurement.cpp
The call `sensor->modelId()` iterates over all ResourceItems and dereferences the QString pointer.
Since the value is used quite often it can be cached to prevent looping every time the `modelId` is used.
Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4802
=> Electrical measurement: Improve handler performance

database.cpp, de_web_plugin.cpp
When deleting a light or sensor, don't store entries with state 'deleted' but purge a device completely. 
Since deCONZ 2.10.4 **one** of the following conditions must be met to create a `deCONZ::Node`:
1. Permit Join is enabled and messages are received from an unknown node (Device Announce etc.);
2. A `device` table entry exists and a Node Descriptor can be retrieved from `device_descriptors` table or as fallback from older `session.default` file;
3. A not deleted entry in `nodes` or `sensors` tables exist.
This is done in order to prevent reappearance of deleted nodes.
-------
~~This PR also enables creation of light nodes even if light search isn't running anymore, but minimal required data has already been queried from the device (Node Descriptor and Simple Descriptors).~~
~~The …
=> Improve lights and sensor deletion

bindings.cpp
Calls like `sensor->modelId()` iterate over all `ResourceItem` and their descriptors to get the actual item.
This PR caches the `modelId` at the beginning of the function. Most redundant checks for sensor pointer where removed as well. Further the `manufacturerCode` from `bt.restNode->node()->nodeDescriptor().manufacturerCode()` is cached.
=> Improve sendConfigureReportingRequest() performance

bindings.cpp, poll_manager.cpp
This PR is intended to streamline the behavior in `checkLightBindingsForAttributeReporting()` and `checkSensorBindingsForAttributeReporting()` to check if the corresponding bindings exist and require attribute reporting.
For both functions, a grace time of `(val.maxInterval * 3 / 2)` is now given (the resources must have the `maxInterval` already set internally), so that basically 2 reports are allowed to have gone MIA before configuring the reporting again. Otherwise, a default value will be assumed (60 * 6 secs for lights, 60 * 15 secs for sensors (previously 60 * 45)).
All this also has been better aligned with the poll manager, which takes the same code as `checkLightBindingsForAttributeReporting()`. This should ensure light nodes get a proper fall back to polling, in case no reports …
=> Streamline attribute reporting config and align polling

de_web_plugin.cpp, poll_manager.cpp, resource.cpp, resource.h, window_covering.cpp
The reporting could stop when the device rejoins the network for various reasons like parent loss or transmission errors.
This PR:
- Marks KADRIL and FYRTUR roller blinds as light sleeper with the new non public `ResourceItem` "attr/sleeper" (borrowed from Device code);
- Support polling light sleeper *Window Covering* devices `state.lift` while reporting isn't setup;
- Fix window covering update by ZCL report / read attributes value (was always set to by report);
- Fix reconfiguration of window covering bindings and ZCL reporting.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1121
=> Fix IKEA KADRILJ and FYRTUR roller blind reporting

database.cpp, de_web_plugin.cpp, resource.cpp
Note: This PR requires a newer firmware, since the device only exposes required endpoints when the coordinator *Node Descriptor* has the Xiaomi manufacturer code set to 0x115F: [deCONZ_ConBeeII_0x266b0700.bin.GCF](http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x266b0700.bin.GCF)
The PR contains a fix to query  *Basic Cluster* attributes like manufacturer name for newer Xiaomi Zigbee 3.0 devices.
The Xiaomi Aqara T1 Cube exposes the same API and button events as the older Xiaomi Aqara Cube does.
```json
{
"1": {
"config": {
"battery": 100,
"on": true,
"reachable": true,
"temperature": 2500
},
"ep": 2,
"etag": "2c4057c509efa2d9e42d30a5697331d6",
"lastseen": "2021-04-29T23:26Z",
"manufacturername": "LUMI",
"mode": 1,
"modelid": "lumi.remote.cagl01",
"name": "Mi Magic …
```
=> Initial support for Xiaomi Aqara T1 Cube

general.xml
Added generic and manufacturer specific attributes and commands as specified in the ID Lock 150 Zigbee specification. Information about the generic attributes and methods fetched from the Zigbee cluster library
=> Door lock database modifications

product_match.cpp
Manufacturer: _TZE200_yw7cahqs
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4841
=> Support Tuya Hama Smart Radiator Thermostat model (TS0601)

de_web_plugin.cpp
This PR fixes the missing button events upon < and > press. Most likely, a handful of further devices is affected by this as well.
The root cause is that for the newer 2.X firmware, the device doesn't natively expose the _scene_ cluster (only used on APS layer), which is hence not considered in the sensor fingerprint. Further devices where a cluster is not hidden, but not included in the sensor fingerprint, could be affected as well. As a consequence, the newly inttroduced `getSensorNodeForAddressEndpointAndCluster()` cannot select the correct sensor. The subsequent code has a more or less appropriate fallback to select the fitting sensor, but gets discarded.
=> Fix for missing Tradfri remote button events

rest_lights.cpp
Concern model :
-  _TZE200_xuzcvlku
-  _TZE200_nueqqe6k
The "bri"/"lift" command is working, the return too, but the command "open" alone have wrong direction side.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4840
=> Fix : covering direction for some Tuya blind

light_node.cpp, light_node.h, rest_groups.cpp, rest_lights.cpp, zcl_tasks.cpp
IKEA firmware has a bug that it ignores the off setting in a scene. As workaround unicast *Off With Effect* commands are send to IKEA lights which are `off` in a scene.
In same fashion plain off commands to IKEA lights are changed to use *Off With Effect* command.
The group recall scene code was refactored to be more dense and properly handle color loop.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3135
=> Fix IKEA lights not turn off in scenes and IKEA unicast off commands

de_web_plugin.cpp
In theory item pointer should never be null, the explicit check prevents false positive warnings for clang scan-build.
=> Fix static analyzer warning in checkSensorButtonEvent()

de_web_plugin_private.h
Writing to the SD card every 5 seconds due lights and sensor updates blocks the whole application way too often, sometimes for seconds.
Since the database is saved on clean deCONZ shutdown anyway the only drawback of the increased delay is the loss of 1 minute data in case of power failure.
=> Raise short database save delay from 5 seconds to 1 minute

de_web_plugin.cpp
This could happen if node[0] isn't the coordinator (rare case).
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4820
=> Fix 0xA6 APS errors due false srcEndpoint selection

authorisation.cpp, rest_configuration.cpp, rest_groups.cpp, rest_lights.cpp, rest_sensors.cpp
This is preparation for a refactored QHttpRequestHeader class which uses static strings wherever possible.
A call like `hasKey("If-None-Match")` implicitly creates a QString since the method expects a `const QString&`.  This leads to a operator new call in QString. Since we mostly just have static strings this can be avoided alltogether.
=> Use QLatin1String for all HTTP header queries

de_web_plugin.cpp, de_web_plugin_private.h
No need to keep `QHttpRequestHeader` copy and created `QDateTime` timestamp, they were never used.
=> Cleanup TcpClient dead code

de_web_plugin.cpp, rest_lights.cpp, rest_schedules.cpp
The upcoming version returns `QLatin1String` values instead `QString`. Note the path splitting in the plugin will be removed in near future, since this is already done by the new `QHttpRequestHeader` without the `QString` overhead.
=> QHttpRequestHeader use QLatin1String methods

database.cpp, de_web_plugin.cpp, rest_sensors.cpp, thermostat.cpp
This PR allows setting the manufacturer specific attribute 0x404B (Regulation SetPoint Offset) via the offset resource item exposed through REST API. It has an allowed range of +-2.5° C. Using it will basically make the thermostat over-/underheat accoding to the set value, thereby automatically adjusting the set heat setpoint.
Includes some further minor enhancements.
=> Make Regulation SetPoint Offset usable as offset for Danfoss Ally

utils/utils.cpp, utils/utils.h
Older versions of Qt don't provide them as member functions.
=> Add QLatin1String helper functions: indexOf, startsWith and contains

bindings.cpp, de_web_plugin.cpp, light_node.cpp, light_node.h, poll_manager.cpp, rest_node_base.cpp, rest_node_base.h
In v2.12.0-beta various `QList` containers in the deCONZ library are replaced by `std::vector`. `QList` is way slower than `std::vector` and more badly has the habit of detaching an allocating extra memory when iterated over a non const container.
Not copying Simple Descriptors has an significant impact since this was done very frequently and caused needless copies of all clusters and attributes and their `QStrings`, going into the millions after just 10 minutes. With this PR only a const pointer to the Simple Descriptor in core is used.
=> Update QList iterators and prevent copy of Simple Descriptor

de_web_plugin.cpp, rest_devices.cpp, rest_devices.h
Most usable is the `state/buttonevent` introspection. Other items can be queried as well but don't provide much details yet.
Implemented uses free functions to be able to write tests. This PR sits on top of PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4932
Example request for IKEA 5 buttons remote:
```
/api/<apikey>/devices/<uniqueid>/state/buttonevent/introspect
```
```json
{
"type":"int32",
"buttons": {
"1": {"name": "Large middle button"},
"2": {"name": "Top dimm up button"},
"3": {"name": "Bottom dimm down button"},
"4": {"name": "Left arrow button"},
"5": {"name": "Right arrow button"}
},
"values": {
"1001": {"action": "HOLD", "button":1},
"1002": {"action": "SHORT_RELEASE", "button": 1},
"2001": {"action": "HOLD", "button": 2},
"2002": {"action": "SHORT_RELEASE", …
```
=> Add introspection REST API for state and config attributes

de_web_plugin.cpp
Webkit boundary marker uses only 6 dashes.
Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4916
Issue: https://github.com/dresden-elektronik/phoscon-app-beta/issues/391 and https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4962
=> Fix loading backup on Chrome (and Safari?) regression

backup.cpp, de_web.pro, de_web_plugin_private.h
* Add `std::array` include for clang;
* Change `ApiResponse` from struct to class to fix forward declaration and make the type consistent to `ApiRequest`;
* Disable deprecated warning (addressed later);
* Disable Qt SDK version is not tested on macOS version warning;
* Link to SQLite3 (can be installed via Homebrew).
=> Small changes to fix macOS compilation

de_web_plugin_private.h, thermostat.cpp, window_covering.cpp
Move them as members into plugin object. The destructors of `TaskItem` would be called after main application quits, this clashes with new APS and ZCL allocator pools and would cause a crash.
=> Remove global TaskItems in thermostat and window covering modules

de_web_plugin.cpp
Small optimization, no need to construct anything on the heap.
=> getAcceptHeaderApiVersion() don't construct temporary QStringList

database.cpp, de_web_plugin.cpp, rest_sensors.cpp
Develco/frient motion sensors MOSZB-1XX currently have `RConfigDuration` exposed to set presence from `true` to `false`. However, this is not necessary, as the device sends an attribute report with occupancy `false` when no motion is detected within the timeframe specified in `PIR Occupied To Unoccupied Delay` (0x0010). Based on that, `RConfigDelay` is the more accurate choice to set the desired timeframe when the sensor should report unoccupied state.
As the same mechanism like for the Hue motion sensors will be used, `RConfigPending` will also be exposed for the occupancy sensor endpoints. The presence sensor based on the IAS Zone cluster will keep `RConfigDuration`.
=> Expose `RConfigDelay` instead of `RConfigDuration` for Develco motion sensors

ias_ace.cpp
For keyfobs, no arm response is send to an arm command, resulting in a retransmission of the initial command by the device. This is due to an incorrectly set ZCL payload length (6 instead of 3) which results in the command not being processed to generate the required response.
=> Fix: Use correct payload length for IAS ACE arm commands for Keyfobs

tuya.cpp
Model : 
- _TYST11_yw7cahqs
- _TZE200_yw7cahqs
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4841
Can change value using API, but value are not updated if using manualy the device.
=> FIX : missing Temperature and Setpoint Value return for Hama (Tuya) TRV 

bindings.cpp
This should, in conjunction with PR #4765, prevent 1002 ghost events.
In #4232, it has been suggested to manually disable attribute reporting for IAS zone status to prevent the unwanted events. This has been reported not to be effective. Apparently, this was due to the fact that the code to trigger any attribute reporting configuration disrespects the value for disablement and consequently "resets" and re-configures reporting.
With this PR, attributing will always be set to "disabled" upon reoccurring configuration thereby ensuring persistence. This is primarily intended to prevent any re-paring of the device.
=> Disable IAS zone status reporting for Samjin Button

de_web_plugin.cpp
* Performance is secondary here, the PR prepares to get rid of `ApiRequest::path`QStringList in favor of new fast `QHttpHeader` methods.
* Removed various QString temporaries;
* Strict branching for paths with 3 components;
* Removed UTF-8 QByteArray JSON output conversion to QString, the assignment of `Json::serialize()` is a fast move operation;
* Replace temporary QString for *Content-Length* with QTextStream  `operator<<(int)` for  `str.size()`.
=> Improve HTTP REST API dispatching performance and use new methods

bindings.cpp, button_maps.json
Add support for 4-gang switch by Tuya named "_TZ3000_xabckq1v"
Most credits go to @Smanar, only finally fixed some button numbers, and together we debugged/corrected EP numbers.
Unfortunately, only 6 of advertised 12 scene possibilities are working yet. Double press doesn't send events, as does long press on the left two buttons. But better than nothing.
=> Add support for Tuya 4gang switch, issue #4810

aps_controller_wrapper.cpp, aps_controller_wrapper.h, basic.cpp, bindings.cpp, change_channel.cpp, de_otau.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, firmware_update.cpp, ias_ace.cpp, ias_zone.cpp, poll_control.cpp, reset_device.cpp, thermostat_ui_configuration.cpp, time.cpp, tuya.cpp, upnp.cpp, utils/utils.cpp, utils/utils.h, xiaomi.cpp, xmas.cpp
This PR adds automatic handling of ZCL Default Response to also catch cases where we currently miss sending the response.
The magic happens by observing outgoing APS requests if they contain a specific ZCL response and automatically send the ZCL Default Response at the end of the APS indication processing. For this C++ RAII is used with an extra ZclDefaultResponder object which sends the response in its destructor.
* All outgoing APS requests use `ApsControllerWrapper` instead of plain `ApsController`.
* All manual sending of ZCL Default Responses was removed.
* Moved `isSameAddress()`into `utils.h`.
* Removed `sendZclDefaultResponse()` from plugin.
=> Fix handling of ZCL Default Response

air_quality.cpp
In some cases the name could be "Bosch", the filter is strict enough here.
=> BOSCH AIR sensor don't match for manufacturer name on report

de_web_plugin.cpp
When pushing the on/off button of the switch approx. 5 seconds, the device changes the operational mode so that the arrow buttons do not send any commands on hold/long press. Under certain conditions (apparently when the arrow keys haven't been used before), this can lead to button event 1002 not being emitted, although the corresponding command is send.
As the respective code was intended for the STYRBAR remote, it is now restricted to that device.
=> Fix: Emit button event 1002 again for TRADFRI remote control after mode switch

basic.cpp
When pressing the middle button for more than 5 seconds the remote reads the Application Version attribute. If the coordinator doesn't respond with value 17 as indicated in earlier remote firmware versions, the arrow buttons don't send hold/long release commands anymore.
This is a followup PR for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4951
=> Fix TRADFRI remote control arrow buttons hold/long release events

rest_sensors.cpp, utils/utils.h
`QLatin1String` doesn't provide `isEmpty()` in Qt 5.7, use `size()` instead.
The `isValid(match)`overloads help to simplify the code a bit.
=> Fix build on older Qt version add isValid(match)  helpers

button_maps.json, rest_rules.cpp
- Manually standardised button names (see Discord, **general** channel);
- Fix button map for LIDL remote: only send 1002 on _On_ button (see Discord, **general** channel);
- Allow rules with condition on `config/on` to fire when `config/on` is false (see Discord **technical-talk** channel).
=> LIDL remote, button names, rules on config/on

de_web_plugin.cpp
Battery value must be shown as 100 instead of 200
=> Fix: Correct battery values for LK Wiser sensors

rest_lights.cpp
Problem in direction between API request and Zigbee return.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4257#issuecomment-855281308
=> Fix : Reverse side for Yoolax covering

de_web_plugin.cpp
With introduction of `isSameAddress()`, a consistent address comparison became availble. Currently, quite a few functions to select alight/sensor have a similar code implemented which varies in some details.
With this PR, the address comparision gets streamlined for the functions `getLightNodeForAddress()`, `getSensorNodeForAddress()`, `getSensorNodeForAddressAndEndpoint()` and `getSensorNodeForAddressAndEndpoint()` while sparing a few lines of code
=> Partially harmonize light/sensor selection logic

general.xml
Code cosmetic to use correct hex prefix.
The ZCLDB parser already expects hex values in certain cases but it's better to be strict.
=> Use proper hex prefix 0x in general.xml <datatypes>

general.xml
- Manufacturer specific commands to configure the covering direction where provided by E-Wand (untested).
- Use correct data type for *Temperature Setpoint Hold Duration* attribute.
=> Add E-Wand Window Covering commands to general.xml

de_web_plugin.cpp, de_web_plugin_private.h
All the `handleZdpIndication()` function did is handled by other parts of the code, like PollManager. The removal gets rid of an extra loop through all light nodes.
FLS-NB specific code to set the sensor reachable is handled by `updateSensorNode()` and friends.
=> Remove obsolete ZDP code

zdp/zdp_handlers.cpp
When a device is or was previously paired and either gets reset or at least sends a device announce, the IAS zone enrollment check is not triggered as the corresponding sensor has already the configuration item `enrolled` set to 1 (enrolled). Consequently, if is not checked if that is really accurate.
This PR sets the resource item to the value initializing the enrollment check upon device announcement.
=> Improve IAS Zone enrollment

de_web_plugin.cpp, utils/utils.cpp, utils/utils.h, zdp/zdp_handlers.cpp, zdp/zdp_handlers.h
With next firmware version and deCONZ v2.12.2-beta, Node Descriptor requests are forwarded to the application.
The handler allows to customize the response for specific devices.
=> Add custom Node Descriptor response handling

de_web_plugin.cpp, de_web_plugin_private.h
This device (_TZ3000_excgg5kb) use a new tuya manufacture number, so the workaround for lights and smart plugs with multiple endpoints but only one basic cluster not working.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5085
=> Improve : better description for Tuya 4CH Smart Switch.

zdp/zdp_handlers.cpp
The default `std::array` initialization sets every unspecified member to 0, resulting in `std::find_if`  returning the last entry.
* Fix the array size
* Add check to catch this error in future
=> Fix ZDP manufacturer specific array size

bindings.cpp, de_web_plugin.cpp, poll_manager.cpp, reset_device.cpp, rest_sensors.cpp, utils/utils.cpp
This PR is intended to make use of `isSameAddress()` more often when address comparisons are required and thereby save some lines of code.
There's further places where `ext()` and its existance is checked exclusively, but I'm not sure if it's appreciated to change those as well (would probably result in a slight processing overhead).
=> Use `isSameAddress()` for address comparison

button_maps.json
Regression from v2.12.2-beta. Due the duplicated JSON key "xiaomiSwitchB1acn01Map", only the last one was properly  loaded.
Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5067
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5117
=> Fix Aqara WXKG11LM 2018 remote button handling

de_web_plugin.cpp, ias_zone.cpp, sensor.cpp, sensor.h
`incrementRxCounter()` and `rxCounter()` do not seem to be used anymore in the plugin, hence the removal.
=> Removal of unused rxCounter() functions and calls

xiaomi.cpp
Due to some missed lines of code (which should have been deleted), the mechanism did exclusively work for Opple switches but not for the WRS-R02 (in case initial configuration fails). This also resolves the corresponding compiler warning.
=> Correct switch configuration code for Opple/WRS-R02

database.cpp, de_web.pro, de_web_plugin.cpp, de_web_plugin_private.h, event_emitter.cpp, event_emitter.h, event_queue.cpp, light_node.cpp, poll_control.cpp, rest_devices.cpp, rest_groups.cpp
For now with a global `enqueueEvent()` free function, to not change hundret's lines of code. In future we can make this cleaner and get rid of the globals.
One timer call handles multiple events, if the total processing time is below 10 ms. This is done because one timer activation might take +-10 ms until called by Qt (borrowed from Device code).
The event queue uses `std::vector` instead `std::queue`, which is several times faster.
=> Add EventEmitter class to decouple enqueueEvent() from plugin

de_web_plugin.cpp
This code is just specific for 1-2 devices and iterates over all available sensors. However, if the sensor fingerprint is set correctly, the right sensor is chosen one instruction before.
Additionally, this code is responsible for generating quite a lot false warnings in the debug log, depending on the number of devices available with an IAS Zone cluster.
=> Remove superfluous IAS sensor selection

product_match.cpp, rest_lights.cpp, tuya.cpp
Add support for _TZE200_la2c2uo9 and correct an issue with "transitiontime".
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5152
=> Add support for Tuya Dimmer _TZE200_la2c2uo9

aps_controller_wrapper.cpp
When a device sends a ZCL Default Response to the coordinator, it shouldn't send one back.
=> Don't send ZCL Default Response to answer one

occupancy_sensing.cpp
Philips SML00X and Develco MOSZB-1XX motion sensors get `RConfigDelay` exposed which represents the occupied to unoccupied delay setting of the device. If no further motion is detected, they report occupied state `false` amongst regular attribute reporting intervals.
As the `durationDue` mechanism is used for those sensors as well, certain unwanted behavior can occur in rare cases, leading to a swift change in presence (`true` to `false` to `true`) rather than a constant `true`. This e.g. can happen, if the attribute report to prevent the automatic change from presence `true` to `false` is processed a second too late.
This PR omits usage of the `durationDue` feature for both motion sensors and additionally adds a 3 seconds grace time for late attribute reports from other motion sensors …
=> Do not use `durationDue` for Philips and Develco motion sensors

aps_controller_wrapper.cpp
For end devices it can happen that the APS request is enqueued in the firmware but never sent, in which case the APS confirm ends with a timout status code (0xF0).
It looks like a timing issue, where the plugin doesn't push the APS request fast enough, and the end device MAC data polls too fast for a response. Or when the end device's initial request required an APS ACK from the coordinator.
This can be seen for Samjin Motion sensor, where not a single ZCL Default Response made it to the device. I suspect a few other devices could be affected as well.
The fix is simple, with APS ACK enabled the firmware will just retry to send the response if it doesn't work on the first attempt.
This is more heavy, but given that the ZCL Default Response is kind of important in order to keep devices …
=> Enable APS ACKs for ZCL Default Response

database.cpp, zdp/zdp_handlers.cpp
As there's always one more place to whitelist, the device now adds `RConfigPending` after restart to allow switch configuration.
Additionally, to make the configuration procedure more robust, `RConfigPending` is now set to require configuration upon device announcement (currently applicable for Opples and WRS-R02). This ensures the Xiaomi device operation mode is marked for writing when the device is reset AND a ZHASwitch resource already exists which is not marked as deleted. Without it, the device does not get configured if reset more than once while deconz is running.
=> Fix: Make Xiaomi WRS-R02 switch configuration more robust

bindings.cpp, de_web_plugin.cpp, rest_sensors.cpp
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5121
And Add support for the SLT3 (a SLT2 clone) nothing special.
=> FIX: Re-enable "mode" command for Hive Devices

rest_sensors.cpp
Affects door locks and eCozy thermostat
=> Fix: Correct erroneous bool value flip

database.cpp, de_web_plugin.cpp
Do not expose RConfigBattery (mains powered) and RStatePower (for consumption sensor)
=> Omit exposure of certain resource items for Aqara Single Switch Module T1 (with neutral)

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h
- Product name: Door Window Sensor Smartlife Zigbee 3.0 Model: ZD06 (AVATOO)
- Manufacturer: _TZ3000_402jjyro
- Model identifier: TS0203
Nothinf special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5301
=> Add Initial support for tuya door windows sensor _TZ3000_402jjyro 

websocket_server.cpp
The websocket server can now be bound to the IP address specified via command line, similar to the regular webserver. If the parameter is not provided or the IP is invalid/not found, it will default back to listen on any IP.
The example below has the webserver running on port 8080 and the websocket server on port 8888. This change is already running in my production environment 😉
=> Enable websocket server to listen on IP specified via `--http-listen` command line parameter

general.xml, product_match.cpp
- Product name: Zemismart Battery Roller Shade
- Manufacturer: _TZE200_iossyxra
Warning the support is partial, still need a tuya command for calibration.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5191
Edit:
Have added in the xml a new tuya command for calibration.
=> Add Initial support for Tuya covering _TZE200_iossyxra

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h
- Product name: Temperature Probe CTHS-317-ET
- Manufacturer: CASAIA
- Model identifier: CTHS317ET
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5138
=> Add Initial support for CASA.ia Temperature probe CTHS-317-ET

rest_lights.cpp, tuya.cpp
This device don't use standard tuya command for covering.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5238
=> Fix : Correct direction for tuya covering _TZE200_rddyvrci

ias_zone.cpp, rest_sensors.cpp
Attempt to determine whether an IAS Zone motion sensor sends restore reports and only queue presence reset if it does not.
=> Don't reset Sonoff SNZB-03 presence

de_web_plugin.cpp
All sensors now get the basic cluster added (previously, only switches got it), air quality sensors receive the power configuration cluster and all devices get the OTAU and time client cluster, if available. Besides the corrections, there should also be a minor performance increase as unnecessary sensor iterations are thereby prevented.
=> Corrections on sensor fingerprints

database.cpp, de_web_plugin.cpp, ias_ace.cpp, ias_ace.h, rest_alarmsystems.cpp, rest_alarmsystems.h, rest_configuration.cpp, rest_rules.cpp, rule.cpp
- With this PR alarm systems can be used as a trigger in rules via `state/armstate`.
- Further alarm systems can be armed and disarmed by rules, e.g. arm at a certain time.
- All alarm systems are returned in the `GET /api/<apikey>` full config response.
Example to turn a light on when the alarm system gets `armed_away`:
```json
{
"actions": [
{
"address": "/lights/15/state",
"body": {
"bri": 255,
"on": true
},
"method": "PUT"
}
],
"conditions": [
{
"address": "/alarmsystems/1/state/armstate",
"operator": "dx"
},
{
"address": "/alarmsystems/1/state/armstate",
"operator": "eq",
"value": "armed_away"
}
],
"name": "Armed away"
}
```
=> Enable alarm systems in rules; return alarm systems in full config request

electrical_measurement.cpp
Value was previously multiplied by 1000 instead of kept as is.
=> Correct Apex smart plug current readings

de_web_plugin.cpp, device.cpp, zdp/zdp.cpp, zdp/zdp.h
Seen with the Hue motion sensor, the NWK address can change. This is detected in the core but it needs the MAC address in the APS request to switch to the new NWK address.
=> Fix ZDP requests to devices with changed NWK addressing

de_web_plugin.cpp, resource.cpp
Due to an incorrectly set data type (unsigned instead of signed), `RStateAngle` was not exposed via API anymore.
=> Fix data type for `RStateAngle`

device.cpp, rest_devices.cpp
- With DDF enabled the creation of bindings was repeated too often. The fix tracks the timestamp of successful ZDP Bind_req.
- Manufacturer specifc ZCL attribute reporting is now handled, using the mfcode specified in the DDF per report configuration.
- Fix writing DDF from the editor discarded the "mf" reporting configuration attribute.
=> Fix tracking of binding creation; use of mfcode in ZCL reporting

tuya.cpp
Prevent some TRV use the min temperature command as temperature command
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5394
Correct issue on schedule command.
=> Fix Tuya TRV reporting temperature value (MOES TRV HY368 TS0601)

de_web_plugin.cpp, rest_sensors.cpp
See here for further details https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5433#issuecomment-957240588
This PR ensures there're now 2 consecutive requests being send with different task and request IDs (confirmed to be send by sniffing). As it is still unknown which information of the device needs to be considered to undoubtly distinguish between the truly required request, this sort of hack should remain.
This PR also amends the evaluation of requests being on air. The limits are set to 2 for unicast and 6 for groupcast, previously effectively allowed were 1 and 5.
=> Fix Eurotronic Spirit heatsetpoint change for newer models

de_web_plugin.cpp
By moving cluster related code to dedicated files, those clusters have been removed in the whitelist of `updateSensorNode()`. However, the clusters are just checked while the sensor iteration has already entered and consequently, all sensors are looped for a non-regarded cluster.
The check for valid clusters is now moved up at the very beginning, before the sensor loop, thereby potentially sparing quite a number of unnecessary loops.
=> Prevent unnecessary sensor iterations in `updateSensorNode()`

de_web_plugin_private.h, thermostat.cpp
For thermostats, negative values were never send due to an inappropriate data type in the respective function. E.g. negative offsets for devices supporting it were always send as 0.
=> Fix sending of negative values for thermostats

bindings.cpp, de_web_plugin.cpp, utils/utils.cpp, utils/utils.h
=> Add support for Aqara TVOC Air Quality Monitor (VOCKQJK11LM)

devices/innr/sp_120.json
Required cluster is 0x0006 instead of 0x0008.
=> Fix: Correct cluster for innr SP120 `state/on`

de_web_plugin.cpp, electrical_measurement.cpp, ias_zone.cpp
In order to better test created DDFs and the associated new code processing, using strict mode will disable legacy data processing for numerous clusters.
=> Enforce skipping legacy code while in strict mode for numerous clusters

resource.cpp, resource.h, rest_sensors.cpp, utils/utils.cpp
Config group is uses to specify the group id(s) used in group bindings.
This affects switches like Ubisys C4/S1/S2 where the group list is configured via REST-API.
Regression from: babe2ac60b4ad698f7b486ef929138b21075f3ec
=> Fix update sensor config/group via REST-API

rest_alarmsystems.cpp
The device `armmask` in the PUT request is correctly stored and used.
However, REST API GET always returned "none" if no 'A' is part of the `armmask`.
=> Fix alarm system GET response to include armmask without 'A'

de_web_plugin.cpp, de_web_plugin_private.h, identify.cpp
The new Ikea firmware broke group cast support. This PR sends an Identify Query Response during joining to the switch.
With that the switch automatically sends commands as unicast to the coordinator, which it didn't before.
No extra unicast bindings are created, and group bindings are still supported for older firmware.
To prevent duplicated button events, the ZCL sequence number check is enabled for Ikea switches.
Tested with:
- On/off switch
- 5 button remote control
- Styrbar remote control
- Shortcut button
=> Fix Ikea switches for new and old firmware

database.cpp, de_web_plugin.cpp, device_compat.cpp, rest_groups.cpp
- Lights with a DDF didn't load groups after startup.
- After "parse" always emit events for sub resources, not only on push. This fixes group `any_on` / `all_on`.
=> DDF fix loading light group membership and events

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, device.cpp, device_compat.cpp, device_ddf_init.cpp, device_descriptions.cpp, device_descriptions.h, devices/generic/items/config_group_item.json, event.h, resource.cpp, resource.h, rest_devices.cpp, rest_sensors.cpp, zdp/zdp.cpp, zdp/zdp.h
For each "auto" entry in the comma separated group list a new `Group` is allocated and assigned to the device via device membership and  `group.uniqueid`.
The `group.uniqueid` is generated based on the position in the `config.group` list:
```
"auto":            00:11:22:33:44:55:66:77
"auto,auto":       00:11:22:33:44:55:66:77
00:11:22:33:44:55:66:77-1
"auto,auto,auto":  00:11:22:33:44:55:66:77
00:11:22:33:44:55:66:77-1
00:11:22:33:44:55:66:77-2
```
Where 00:11:22:33:44:55:66:77 is the MAC address of the device.
Note: The first group has no "-0" suffix, to be backward compatible with old code.
Requires deCONZ v2.13.3.
The group bindings specified in the DDF refer to the `RConfigGroup` group list and can be changed via REST-API. 
The Device binding state machine takes care of creation, …
=> DDF group bindings and group allocation

database.cpp, de_web_plugin.cpp, device_descriptions.cpp, device_descriptions.h, devices/dresden_elektronik/fls_pp3.json, devices/immax/07048L_smart_plug.json, devices/innr/sp_120.json, devices/philips/rwl02_dimmer_switch.json, devices/philips/sml001_motion_sensor.json, devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json, rest_sensors.cpp, ui/device_widget.cpp, ui/device_widget.h, ui/device_widget.ui
The "Disabled" DDF mode is replaced by "Basic" mode in which only DDF files with enabled status are loaded.
The default is Gold, but Bronze and Silver can also be enabled. *This setting is persistent.* "Strict" and "Hybrid" (formerly Normal) modes are *not* persistent and revert to Basic mode after each deCONZ start to prevent user errors.
When the modes are changed in Control panel, all Devices with DDF will be reloaded, one per second, to reflect the changes without restarting deCONZ.
To prevent any surprises all Gold status DDF files are set to Silver for now. This is done so that they are not enabled by default. After more testing these can be set to Gold again.
=> Enable Gold status DDF files by default

button_maps.json, de_web_plugin.cpp, device.cpp, devices/dresden_elektronik/kobold.json, rest_sensors.cpp
New Dimmer Switch which can be configured to control lights or groups directly.
The DDF makes use of the new groupcast bindings and group configuration capabilities.
Via REST API the `config.group`can be set to control a specific Zigbee group (on/off and dimming).
=> Add DDF for Phoscon Kobold

de_web_plugin.cpp
This fix should allow the device to be paired again.
=> Fix Xiaomi WXKG11LM regression bug for ZHASwitch resource creation

de_web_plugin.cpp
Noticeable for example in the Hue Dimmer DDF which stopped processing of rules on button events.
=> DEV enqueue missing state/lastupdated event to fix rule handling

button_maps.json
https://www.robbshop.nl/robb-smarrt-draadloze-schakelaar-wit-2knops-zigbee
https://www.robbshop.nl/robb-smarrt-draadloze-schakelaar-wit-4knops-zigbee
https://www.robbshop.nl/robb-smarrt-draadloze-schakelaar-wit-8knops-zigbee
These are rebranded Sunricher remotes. Tested with the 2-button version.
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5000 already added the 8-button version (as `ROB_200-008`), but mine apparently has a trailing `-0`, which according to the website the other versions should also. Seeing the screenshots in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4601 that's probably another revision.
=> Add button events for ROBB Smarrt wireless remotes

bindings.cpp, database.cpp, de_web_plugin.cpp, diagnostics.cpp, rest_sensors.cpp, thermostat.cpp, thermostat_ui_configuration.cpp
=> Add support for POPP Smart Thermostat

bindings.cpp, button_maps.json, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, device_ddf_init.cpp, devices/ubisys/c4_5504.json, resource.cpp, rest_sensors.cpp
The C4 is currently broken for various reasons. The DDF is meant to replace the C++ implementation while being backward compatible. Group binding and reconfiguration of these works as for Kobold with the "auto" `config.group` support for all 4 endpoints.
Initially with the DDF the C4 wil create 4 device groups and binds to them so that x002 button events are received right away.
The controlled groups can be reconfigured via REST API or within the Phoscon App switch details view. It might take a minute or two until the changes are applied.
**TODO**
* ~~Check the C++ implementation of `processUbisysC4Configuration()` it looks incomplete, is it even needed?~~
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/bindings.cpp#L4496
* ~~Remove C++ code for C4~~
The PR seems good …
=> DDF add Ubisys C4

devices/sengled/E12-N1E.json
Previously color temperature support for this device was broken; added state/ct in DDF to allow this property to be properly picked up by api clients. Has been tested.
I believe this addresses #4833 and possibly #5590
=> Added DDF for Sengled E12-N1E

de_web_plugin.cpp
When holding the side buttons for a few seconds, the 1002 and 2002 events won't be triggered anymore.
This happened since we filter out the OnOff cluster commands during long press which are send by the side and the top and bottom buttons.
This PR resets the remembered state making the 1002 and 2002 button events for top and bottom buttons work again.
Note: The long press for for the side buttons works, but only starts after pressing them for more than 4 seconds.
=> Fix Ikea Styrbar lockup of top/bottom buttons short press after long press side buttons

bindings.cpp, button_maps.json, de_web_plugin.cpp, devices/ubisys/s1_5501.json, electrical_measurement.cpp
The ubisys S1 wasn't working for a few releases due some other code changes.
The DDF replaces most of the C++ implementation.
Note for the ubisys S1-R a separate DDF needs to be created, except if it is equal... needs to be tested.
=> DDF add ubisys S1

bindings.cpp, button_maps.json, de_web_plugin.cpp, devices/ubisys/s2_5502.json, electrical_measurement.cpp
The DDF replaces most part of the C++ implementation.
The S2 was broken since a few releases due code changes.
Note that the Electrical Measurement cluster doesn't support reporting, and Simple Metering cluster only for attribute 0x0400. The rest gets polled.
Like the C4 the `button_maps.json` was broken due incomplete modelid in combination with startsWith() check.
=> DDF add ubisys S2

de_web_plugin.cpp, ias_zone.cpp
This affected at least Electrical Measurement and Simple Metering devices.
Due recent refactoring the reachable handling was skipped since the function
bailed out early to non matching clusters.
- Streamline reachable handling to happen in fewer places
- Removes a few loops through sensor and light arrays
- Simplify MAC data request handler
- Improve IAS handler by bail out more early
Testet with ubisys J1 and various end devices.
=> Fix certain sensors become unreachable; ubisys J1

device_js/device_js_wrappers.cpp
For some data types a string instead of numeric was returned. If the expression was evaluated weird results appeared, e.g:
`"5" + 1 = "51"`
This fixes DDF state/humidity values.
=> Fix DDF Javascript numeric value convesion for Attr.val

device.cpp
The version field in Node List UI was not filled for DDF devices.
=> Fix showing swversion of DDF devices in Node List

tuya.cpp
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4693
Sorry.
=> Fast FIX: reverse fire state on Woox smoke sensor

database.cpp
Auto generated DDF draft sensors — without a prior C++ implementation — have initially the ednpoint part set to FF in the uniqueid template.
This PR prevents loading and storing incomplete sensor of the database.
The problem was mostly even than the template was completed, two sensor resources existed with the FF one conflicting with the correct one.
One example is Wisers LK Switch: https://forum.phoscon.de/t/schneider-wiser-devices-not-working-in-dyna-version-2-14-00/1516
=> DDF prevent load/store incomplete sensors with endpoint 0xFF

de_web_plugin.cpp, device_tick.cpp
This is only a rough workaround which will be replaced by a more precise method later. The problem is in a network with lots of DDF devices the APS queue can be stressed too fast, since the DeviceTick triggers polling without waiting if the previous polling device is already finished.
=> Prevent DDF devices to poll too fast in idle mode

devices/xiaomi/xiaomi_zncz04lm_smart_plug.json
Default behavior to poll voltage and consumption as defined in `state/voltage` and `state/current` shall be prevented, as otherwise the wrong clusters are polled.
=> Prevent unnecessary polling for ZNCZ04LM

database.cpp, de_web_plugin.cpp, device.cpp, device_ddf_init.cpp, device_descriptions.cpp, light_node.cpp, poll_manager.cpp, tuya.cpp
See the linked issue for further info.
- Ensure that the model ID **and** the manufacturer name are now queried if the values are not yet known.
- The respective DDF match is now executed on both attributes instead of just the model ID.
- Additionally, neither the manufacturer name nor the model ID is set to "Unknown" if not queried and respective checks have been removed.
The DDF match might be extended in future to e.g. take a device firmware into account.
Additionally, this includes the successor of #5829 to fix matching the manufacturer name agains constants.
=> Trigger manufacturer name read and consider it while selecting DDF

bindings.cpp, database.cpp, de_web_plugin.cpp, devices/niko/170-33505_170-33605_smart_socket.json, electrical_measurement.cpp, simple_metering.cpp
Adds the respective DDF and removes legacy code.
=> Add DDF for Niko connected socket outlet 170-33505/170-33605

bindings.cpp, database.cpp, de_web_plugin.cpp, devices/develco/smszb-120_smoke_detector.json, devices/frient/smszb-120_smoke_detector.json, light_node.cpp, power_configuration.cpp
Adds the respective DDF and removes legacy code.
=> Add DDF for Develco/frient SMSZB-120 smoke detector

devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json
Apparently, the respective resource item was missing so that the sensor was skipped for any incoming updates.
=> Add `config/enrolled` resource item for MCCGQ14LM to allow sensor usage

backup.cpp, crypto/random.cpp
`qrand()` is not suitable for generating the network key when factory resetting an adapter.
The first call to `qrand()` sets the public PAN ID. This leaks enough RNG state to make bruteforcing the full state feasible from a single captured packet and thus allows the network key to be easily computed.
Unoptimized PoC: https://github.com/puddly/deconz-network-key-leak-poc
---
I can't figure out how to test this branch with the deCONZ Docker image so while the code compiles, I'm not certain of its correctness.  Feel free to close this PR and re-implement it yourself, the changes are pretty minor.
=> Securely generate network key when resetting adapters

button_maps.json, devices/wiser/fuga_4button_battery_switch.json
Endpoints 0x17 and 0x18 don't seem to be used by the device
Add bindings for Level Control ZCL
Add button actions for _HOLD and _HOLD_RELEASED
=> Extend functionality of LK FUGA Wiser Wireless Battery 4 Button Switch

de_web_plugin.cpp, de_web_plugin_private.h, device_access_fn.cpp, device_access_fn.h, device_descriptions.cpp, general.xml, rest_lights.cpp, state_change.cpp, state_change.h, tuya.cpp, zcl_tasks.cpp
This PR adds support of DDF "read", "write" and "parse" functions for the Tuya manufacturer specific cluster (0xEF00).
Example: MoesGo Smart Dimmer Module (_TZE200_e3oitdyu): (PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5869)
```
[
{
"name": "state/on",
"parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val;" },
"write": {"fn": "tuya", "dpid": 1, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
"read": {"fn": "tuya"},
"refresh.interval": 300
},
{
"name": "state/bri",
"parse": {"fn": "tuya", "dpid": 2, "eval": "Item.val = (Attr.val / 1000.0) * 254.0;"},
"write": {"fn": "tuya", "dpid": 2, "dt": "0x2b", "eval": "(Item.val / 254.0) * 1000.0;"},
"read": {"fn": "none"}
}
]
```
1. The **parse** function needs to specify the datapoint `dpid` to be parsed. The actual …
=> DDF support Tuya manufacturer specific cluster

devices/merten/meg5113-0300_cover_controller.json, general.xml
Adds DDF and manufacturer specific cluster/attributes.
=> Add DDF for Merten MEG5113-0300 cover controller

devices/tuya/_TZE200_e3oitdyu_smart_dimmer_module.json, devices/tuya/tuya_swversion.js
The PR depends on https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5868
For Tuya devices it adds the `devices/tuya/tuya_swversion.js` which should be used to correctly parse the `attr/swversion` item.
```
{
"name": "attr/swversion",
"parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
"read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
}
```
The Tuya firmware version is stored in *ZCL Basic* cluster *Application Version* 8-bit attribute as packed major.minor.patch version. For example: 0x41 results in `0b 01 00 0001 = 1.0.1`.
The device provides two REST-API lights with on/off and dimming, unfortunately no button events.
```
{
"1": {
"etag": "660b09d282b480796bb1e995af7b6efc",
"hascolor": false, …
```
=> DDF for MoesGo/Tuya Smart Dimmer Module (_TZE200_e3oitdyu)

de_web_plugin.cpp
The modelid change was never made, since the button map check bailed out too early.
=> Fix detection of GIRA/JUNG switches

device_js/device_js_wrappers.cpp
For signed integers the C++ union is tricky as the correct member needs to be
extracted. In contrast to unsigned integers  num.s16 != num.s64. Since the
ZclAttribute already has the correct negative number in its internal QVariant
we can just use it.
Also expose 56-bit values as string since JS only has 2^52 integers.
The scopes where added to prevent stack corruption  (not actually reported but to be safe..).
=> Fix DDF handling of negative values and values above 2^52

electrical_measurement.cpp
If the item is `null` in the REST-API the plain value comparisons against 0 fails and the items aren't set to 0 properly.
=> Fix initally set value in electrical measurment cluster, if value is 0

devices/xiaomi/xiaomi_ws-euk03_h1_switch.json
Adds the respective DDF. Device specific code will be removed later to prevent merge conflicts.
=> Add DDF for Xiaomi H1 single rocker switch (neutral wire) WS-EUK03

devices/develco/aqszb-110_voc_sensor.json, devices/develco/splzb-131_smart_plug.json, devices/frient/aqszb-110_voc_sensor.json, devices/frient/splzb-131_smart_plug.json, devices/generic/items/state_consumption_item.json, devices/generic/items/state_current_item.json, devices/generic/items/state_power_item.json, devices/generic/items/state_voltage_item.json, devices/immax/07048L_smart_plug.json
Some DDF updates/additions:
- Prevent fakeouts of air quality raw values (65535) for develco/frient aqszb-110 voc sensor
- Prevent fakeouts of power values by ignoring values positive max values as well (32768)
- Promote immax 07048L smart plug DDF to gold and remove unnecessary entries
- Add correct power handling to develco/frient splzb-131 smart plug for `state/power` in ZHAConsumption sensor
- Fix voltage calculation for develco/frient splzb-131
- Set `"default": 0` for `state/voltage`, `state/current`, `state/power` and `state/consumption` resource item
=> DDF updates and additions

de_web_plugin.cpp, de_web_plugin_private.h, device_access_fn.cpp, device_js/device_js.cpp
Create JS engine instance as singleton only once. Likely speeds up parsing but also allows to use the JS engine for other purposes (separate PR).
=> Don't create DeviceJs instance on each "parse" invocation

database.cpp, device.cpp, device_descriptions.cpp, device_descriptions.h, device_js/device_js.h, device_js/device_js_wrappers.cpp, device_js/device_js_wrappers.h, rest_devices.cpp
This allows to select a DDF not only by modelid and manufacturer name
but optionally also other aspects as endpoints of the device.
The initial version supports `R.endpoints` property which returns an array of active endpoints of the node
e.g. `[1, 2]`. So it can be queried for specific endpoints or simply the number e.g.:
```
{
....
"modelid": "ACME",
"matchexpr": "R.endpoints.length === 2",
...
}
```
Note this should only be used in very specific cases!
=> DDF initial support for top level "matchexpr" property

device_descriptions.cpp, device_descriptions.h, rest_devices.cpp
A optional "meta" JSON objects can be provided which may describe static aspects of a device
not fitting in general "items" or other keywords.
One example is `group.endpoints` of an upcoming PR to describe which endpoints
reflect the index belonging to an endpoint of `config.group`.
```
{
"meta": {
"group.endpoints": [1, 2]
}
}
```
The C++ code can query the meta object for a sub device as QVariantMap via 
```
Resource *r = ...;
const auto &sub = const DeviceDescription::instance()->getSubDevice(r);
if (sub.isValid())
{
if (sub.meta.contains(QLatin1String("group.endpoints")))
{
// sub.meta is an QVariantMap
}
}
```
**Warning:** It is *not* intended to add endless things to the meta object, most often it's better to find a general approach!
=> DDF support sub device "meta" objects

json.cpp
This issue can impact state/consumption with big value.
To reproduce the issue.
- take a DDF for a sensor
- add the config/powerup field (UInt32)
- set the "static defaut value"
- try values
1999999 result > 2000000
12345678 result 12345700
This patch will work only on recent QT version, no change for older.
=> Better precision for big value in API result.

devices/third_reality/3RMS16BZ_motion_sensor.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5337
For information this device can't be added using editor, because the comma in the manufacture name.
=> DDF for THIRDREALITY Zigbee Motion Sensor

button_maps.json, de_web_plugin.cpp
This adds support for the _TZ3000_wkai4ga5 variant of the TS0044 Tuya 4-Gang Scene Switch, fixes https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5879.
=> Extended 4-button Tuya scene switch support to include TS0044 _TZ3000_wkai4ga5

devices/generic/items/state_lastset_item.json, devices/generic/items/state_localtime_item.json, devices/generic/items/state_utc_item.json
The time related resource items had the respective evals missing in the parsing functions.
=> Fix: add missing eval to parsing functions

database.cpp, de_web_plugin.cpp, fan_control.cpp
See https://forum.phoscon.de/t/centralite-pearl-3-thermostat-not-presenting-all-hvac-modes-in-home-assistant/1803
=> Fix : Thermostat variant for Centralite Pearl 3 Thermostat

database.cpp, de_web_plugin.cpp, devices/generic/items/config_windowcoveringtype_item.json, devices/generic/items/state_lift_item.json, devices/generic/items/state_tilt_item.json, devices/ubisys/j1_5502.json, electrical_measurement.cpp
Adds DDF, removes some ubisys related legacy code, adds missing `config/windowconveringtype` resource item and adds default functions for `state/lift` and `state/tilt`.
=> Add DDF for ubisys J1 covering controller

devices/generic/constants.json, devices/generic/subdevices/door_lock_controller.json, devices/generic/subdevices/warning_device.json
Add 
- Door lock controller https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3973
- Warning device
I m not sure for the "Fan device", will be usefull but not used by third app ..
Can add it if needed.
=> Add door lock and warning device DDF types

devices/generic/items/config_externalsensortemp_item.json, devices/sinope/th1124zb.json
Some corrections and add a command to send a temperature from external sensor to be displayed on the device
`sudo /usr/bin/curl -X PUT -H "Content-Type: application/json" -d '{"externalsensortemp": 2500}' "http://127.0.01:PORT/api/MY_KEY/sensors/182/config"`
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2104
=> Update DDF for the Sinope TH1124ZB

devices/orvibo/CM10ZW.json
This device have many version.
The first one is supported by legacy code, but not this one.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3973
=> Add DDF for ORVIBO Zigbee Dry Contact CM10ZW

de_web_plugin.cpp, device.cpp, device.h, device_access_fn.cpp, device_descriptions.cpp, devices/danfoss/etrv0100_thermostat.json, devices/generic/items/state_lastset_item.json, devices/generic/items/state_localtime_item.json, devices/generic/items/state_utc_item.json, time.cpp
Make the function `time` available for DDFs as a 2in1 function, allowing data from time server cluster to be parsed for `config/utc`, `config/localtime` and `config/lastset`. For `config/utc`, a time drift of +/-11 seconds triggers an automatic time sync by writing current time data to the device while confirming the success with another read.
This is basically just a transition of the previous approach for ZHATime sensors.
```
01:01:57:841 cc:cc:cc:ff:xx:xx:xx:xx-01-000a/state/utc : time drift detected, -13 seconds to now
01:01:57:841 cc:cc:cc:ff:xx:xx:xx:xx-01-000a correcting time drift...
01:01:57:842 cc:cc:cc:ff:xx:xx:xx:xx-01-000a time verification queued...
...
01:01:59:273 cc:cc:cc:ff:xx:xx:xx:xx-01-000a/state/utc : NO considerable time drift detected, -2 seconds to now
```
=> Add DDF functions to sync time

device_access_fn.cpp, devices/xiaomi/xiaomi_known_issues_mccqg01lm.md, devices/xiaomi/xiaomi_mccgq01lm_openclose_sensor.json
That's the older rounded version of the sensor.
PR also fixes Xiaomi special report struct processing in DDF.
Since the sensor is finicky to pair, the following is added to the sensor documentation.
To pair the sensor it needs to be reset first, by pressing the pin-hole button for 10 seconds.
Then after starting sensor search, press the button again until the LED blinks.
Finally continuously press the button every 2 seconds until joining is confirmed.
=> DDF for Xiaomi Mijia contact sensor (MCCGQ01LM)

de_web_plugin.cpp, device.cpp
- In legacy `delayedFastEnddeviceProbe()` function don't interfere with Device code ZDP requests for Node Descriptor, Active Endpoints and Simple Descriptors.
- Consider already available data in Basic cluster attributes during pairing, which is needed for some Xiaomi sensors that send the modelid in a report.
- Fix handling of unsupported binding table status (Xiaomi sensors send a response which has only 2 bytes of payload).
- Check if there is polling needed after awake event, that's useful during pairing to quickly query all needed attributes.
- Sync NWK address changes from core to device `attr/nwkaddress` resource item.
Related issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5974
=> Device code improve pairing

device.cpp, device.h, device_ddf_init.cpp, rest_sensors.cpp, xiaomi.cpp
The battery state needs to be pushed to deCONZ core in order to be shown.
Looks like prior also this was only done once per deCONZ start, now it's updated when the value is refreshed.
=> Fix battery icon not shown for DDF devices

device.cpp
The `{"fn": "none"}` parse functions don't need to be processed by the poll state machine. There was also a subtle bug that `poll` referenced item was accessed after it was popped from the `d->pollItems` vector which is undefined behavior.
=> DEV poll state machine, harden "none" parse function handling

de_web_plugin.cpp, de_web_plugin_private.h, event_queue.cpp, rest_sensors.cpp
Since DDF devices and their light and sensor resources are created async, the rule triggers can't be indexed in the plugin constructor.
The PR delays/debounces the indexing so that all devices are handled properly. This is also a bit faster since prior for each device useless container calls where made during startup.
=> Fix processing rules referencing DDF devices

database.cpp, device_ddf_init.cpp
If there aren't already entries in 'resource_items' extract them from 'config' and 'state' of the sensors table.
Also store managed device data in the legacy DB store function for now, needs a better solution later on.
=> Improve loading DDF sensor data from legacy DB tables

light_node.cpp, sensor.cpp
Updating the `lastseen` attribute is done very often especially for lights.
In my 100 node test setup this caused frequent storing of all lights state, taking 5-7 seconds on a Raspberry Pi SD-card.
This PR skips setting the needSaveDatabase flag for `RAttrLastSeen`.
=> Fix lastseen attribute changes causing frequent database writes

database.cpp, de_web_plugin.cpp, de_web_plugin_private.h
- Fix warnings to normalize signatures.
- Use old signal/slot syntax for source routes. On older Qt versions the derived   deCONZ::ApsController signals don't seem to propagate. (source routes not stored).
=> Fix Qt signal/slot issues

de_web_plugin.cpp, device.cpp
While changing the settings of the Daylight sensor, the code runs into a segmentation fault in `DEV_GetSubDevice()`, trying to iterate over the available sub devices of the device provided, although a nullptr was given.
In addition to the above, two further missing guards were added.
=> Fix: Guard against non-existent device to prevent SIGSEGV

devices/generic/illuminance_cluster/sml_light_level.js
Fixes https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6041
If `lightlevel=0`, the `lux` value was not set. Also, `lux=0` was no longer possible.
=> Fixes lux value if lightlevel is 0

devices/danalock/danalock_v3.json
Compared to the legacy implementation the PR configures bindings and reporting for Power Configuration, Poll Control and Doorlock clusters.
This yields a bit more traffic towards the gateway and shows the battery symbol in the GUI.
There are several reports that the device has difficulties keeping the connection (this seems to also happen with other gateways). Looking at various sniffer logs one reason is when the lock changes the parent from a router to the coordinator, this wasn't handled correctly in all cases. The bug is fixed in the new ConBee || and RaspBee II firmware 0x26780700 ([firmware changelog](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog)).
The lock runs fine now in my setup for a few days with the new firmware and DDF.
However the sniffer …
=> Add DDF for Danalock V3

de_web_plugin.cpp
The event was emitted for each `state/*` item which was changed in one received message. This could be seen in Philips Hue dimmer switch button handler, provoking wrong rule handling but is a general problem.
The PR compresses multiple state updates to only one `state/lastupdated` event.
Fixes https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6059
=> Fix state.lastupdated event fired multiple times

devices/namron/4512737_thermostat.json
Solve voltage convertion and bind on wrong cluster.
See [Namron Thermostat Touch](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6053#issuecomment-1130499119)
=> Fix Namron Thermostat Touch

devices/philips/sml004_motion_sensor.json
Add DDF for this device. It is a simple copy/paste from sml003_motion-sensor.json with only replacing "SML003" with "SML004". Reporting of motion, illuminance, battery, temperature works fine. Other features I did not test extensively, but no issues so far.
=> Add DDF: Hue Outdoor Motion Sensor rev. SML004

devices/sinope/th1124zb.json
- Remove the ZHATemperatur device (not usefull as there is too a ZHAThermostat
- Add "config/ledindication" that impact the display mode.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2104
=> Edit DDF for sinope thermostat TH1123ZB and TH1124ZB

button_maps.json, devices/tuya/_TZ1800_ladpngdx_lild_doorbell.json
As, the original PR with code edition is locked https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5702
This PR can make the doorbell working using DDF, see https://github.com/Smanar/Domoticz-deCONZ/issues/125
tuya device  : _TZ1800_ladpngdx
=> FIX, Add DDF for the lidl Silvercrest Doorbell

button_maps.json, devices/tuya/_TZ1800_ladpngdx_lild_doorbell.json
Additions for PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6071
The DDF didn't load due 0-100% "invalid utf8" in config/battery. It's actually valid but needs another fix...
Main problem is that we have different modelid/manufacturernames in the databases out there. The variants are added so the DDF is picked up for each of these. Note for later we need to have something like:
"apimodelid"
"apimanufacturername"
To express what should actually be exposed and be backward compatible, since the legacy code sometimes replaces the original Zigbee values (Lidl/Tuya).
=> Followup LIDL/Silvercrest door bell (HG06668)

devices/xiaomi/xiaomi_rtczcgq11lm_fp1_presence_sensor.json
- Leverage Xiaomi special reporting for updating values to reduce number of polls (reports every 5 mins)
- Use presence event `enter` to set presence to true
=> Optimizations for Aqara FP1 presence sensor

de_web_plugin.cpp, zdp/zdp_handlers.cpp
For non DDF devices with multiple resources the sensor.config.reachable wasn't set for sensors which weren't at the first index.
This was seen with the Heiman sirene which has a WarningDevice at index 0 and ZHAAlarm sensor at index 1, other devices might have been affected as well.
=> Fix setting lastannounced and sensor reachable

button_maps.json, devices/sunricher/vivares_pbc4_01.json
Might be the same as the legacy code version, but this testing unit has modelid VIVARES_PBC4_01.
Keep seperated for now. The DDf is based on the ubisys C4.
=> DDF for Sunricher C4 (VIVARES_PBC4_01 / SR-ZG2833PAC-C4)

devices/tuya/_TZE200_bjawzodf_hum_temp.json
This device use tuya cluster.
Battery not tested, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5927
=> Add DDF for tuya sensor _TZE200_bjawzodf (hum + temp)

devices/frient/aqszb-110_voc_sensor.json, devices/frient/splzb-131_smart_plug.json, devices/ikea/tredansen_block-out_cellul_blind.json, devices/namron/4512737_thermostat.json, devices/neo/NAS-WR01B.json, devices/sengled/E12-N1E.json, devices/sengled/e1c-nb7.json, devices/sinope/sp2610zb_smart_switch.json, devices/sinope/th1124zb.json, devices/sonoff/zbmini-l_relay.json, devices/third_reality/3RMS16BZ_motion_sensor.json, devices/tuya/_TZE200_bjawzodf_hum_temp.json, devices/wiser/fuga_socket_outlet.json, devices/woox/woox_r7060_ts0101.json
In a DDF the item description needs only be specified when it differs from the default item description.
The DDF editor should detect this, but currently this fails in some cases.
=> DDF cosmetic, use default description of items

rest_sensors.cpp
Used by `CLIPDaylightOffset` sensor, the time string passed to `item->setValue(QVariant)` is automatically interpreted as UTC.
The PR creates a `QDateTime` as local time and passes this to `setValue()` to be handled without modification.
=> Fix PUT sensor/state/localtime

devices/xiaomi/xiaomi_rtcgq14lm_lux_to_lightlevel.js
Apparently, when there's not much light, the sensor seems to report extremely high values not making any sense. While testing, the value lux value has not gone below 65531 lux. However, to allow for some buffer, the maximum allowed lux value has been set to 65519, anything above will be considered as 0.
It's unknown if that is a bug in the device firmware or maybe even a hardware issue. As of now, Xiaomi hasn't released an updated firmware.
=> Filter inappropriate illumination values for Aqara P1 presence sensor

device.cpp, zcl/zcl.cpp, zcl/zcl.h
As report configuration for one cluster is merged into one ZCL command, the resulting APS frame can be too large.
Such commands could cause overwriting invalid memory in core (now fixed). This PR splits up ZCL reporting read and configure into multiple ZCL commands.
The problem was exposed by Ikea Starkvind PR which needs to configure 9 attribute reports: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6124
=> Fix ZCL report configuration for more than 6 entries

devices/blitzwolf/bw_shp13_smart_plug.json
Because TS011F_TZ3000_amdymr7l was not able to recognize the power consumption and energy readings in Home assistant with Deconz. Added Manufacturername and modelid.
=> Add support for TS011F_TZ3000_amdymr7l

devices/frient/kepzb-110_keypad.json
If frient is not mention it doesn't work why this keypad.
=> DDF add manufacturer name "frient A/S" for keypad KEPZB-110

de_web_plugin.cpp
Missing ZCL payload length check can cause a segmentation fault
=> Fix rare and device-related SIGSEGV

button_maps.json, devices/tuya/_TZ3000_i8jfiezr_temp_hum_sensor.json, devices/tuya/_TZ3000_ygvf9xzp_4gang_remote.json, devices/tuya/ih-f001_door_sensor.json, devices/tuya/ih-k009_temp_hum_sensor.json
Add DDF for a tuya switc/remote _TZ3000_ygvf9xzp, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6080 and _TZ3000_ee8nrt2l see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5836
Add DDF for a tuya sensor _TZ3000_i8jfiezr (aka RTX ZTH1) , see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6123
Add DDF for another tuya sensor _TZ3000_dowj6gyi aka IH-K009, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6100
Add DDF for a door sensor _TZ3000_oxslv1c9 aka IH-F001 see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5665
=> Add DDF for various tuya devices

devices/xiaomi/xiaomi_airmonitor_acn01.json, devices/xiaomi/xiaomi_swversion.js
Update includes:
- Promote DDF to Gold status
- Change processing of `state/airquality`, as the device reports it via attribute 0x0129 on the 0xfcc0 cluster. The applicable scale is the one of the WHO
- Change `attr/swversion`. Recent discovery is that item 0x08 of the Xiaomi special reporting holds the true firmware version (also displayed and confirmed by the Xiaomi App). In rare cases, it can also be item 0x0d on different devices
- Consider the device as awake, when `attr/modelid` is recieved. This usually happens when the device button is pressed (it does mac poll then, should be standard for all Xiaomi battery powered devices)
- Set a binding and attribute reporting for `state/airqualityppb`. Some people mentioned reporting would eventually stop otherwise. Has been tested for more …
=> Update DDF for Aqara TVOC sensor

de_otau.cpp, de_web_plugin.cpp, de_web_plugin_private.h, device_tick.cpp
- Fix missing emitting Websocket "added" event after sensor or lights where added via DDF.
- Fix starting fast polling `DeviceTick` after Permit Join gets enabled.
- Continue fast polling after Permit Join is disabled for 20 seconds to let setup tasks finish in time.
- Additionally slow down idle polling during OTA updates with raising tick time from 1 to 8 seconds, otherwise sending OTA responses too often fails since the queue is occupied.
Overall this results in a much faster joining and setup process. Main problem was the that the fast poll Qt signal wasn't updated after introducing the `EventEmitter` class a while ago.
=> Fix DDF joining issues

devices/frient/kepzb-110_keypad.json, devices/generic/items/state_seconds_remaining_item.json
Concern devices
- Develco Products A/S
- frient A/S
Add the support for "state/seconds_remaining"
Else the keypad can't work because of code 
```
ResourceItem *panel = r->item(RStatePanel);
ResourceItem *secondsRemaining = r->item(RStateSecondsRemaining);
if (!panel || !secondsRemaining) { continue; }
```
=> Fix : change state/action for keypad Develco/Frient

devices/xiaomi/aq_curtain_acn002.json, devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json, devices/xiaomi/xiaomi_rtcgq14lm_p1_presence_sensor.json, devices/xiaomi/xiaomi_rtczcgq11lm_fp1_presence_sensor.json, devices/xiaomi/xiaomi_wrs-r02_h1_switch.json, devices/xiaomi/xiaomi_ws-euk01_h1_switch.json, devices/xiaomi/xiaomi_ws-euk02_h1_switch.json, devices/xiaomi/xiaomi_ws-euk03_h1_switch.json, devices/xiaomi/xiaomi_ws-euk04_h1_switch.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug.json
Devices will now get the same version string as shown in their native app.
=> Update Xiaomi FW version strings for DDF supported devices

product_match.cpp, rest_lights.cpp, window_covering.cpp
Followup to #3757
I know that PRs regarding devices are not merged if they are not in DDF format, but don't stop reading here.
The logic of reversing the percentage like it is implemented is currently **not possible** with the DDF specification.
If that changes I am happy to add and test a DDF for the device.
=> Fix Zigbee Dual Curtain Switch _TZ3000_j1xl73iw (TS130F)

devices/samsung/samjin_multi_sensor.json
- Set Gold status.
- Fix empty version attribute.
- Handle vibration and orientation in DDF.
- Handle bindings and reporting in DDF.
- Add missing IAS items to be configured without legacy code.
The DDF works without legacy code, but the code can't be removed yet
since other variants as 2016 version of SmartThings "multiv4" depend on it.
=> Update Samsung multipurpose sensor DDF

devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
Devices with firmware version 24 have a different endpoint for consumption measurement
=> Add DDF for Xiaomi Mijia smart plug ZNCZ04LM with newer FW version

state_change.cpp
In case read and parse function for a resource item differ, the state change will fail, as the read attributes command cannot be issued. This leads to a condition where the state change will always have the state failed and gets deleted on the next occasion.
As of now, this seems to impact just a hand full of devices.
=> Fix state changes failing prematurely under rare conditions

rest_configuration.cpp, rest_sensors.cpp
Fix creating the lat/long items on first deCONZ start.
Prior this was at least fixed by database code in next deCONZ start.
Fix in case the discovery server isn't used or provides invalid coordinates the `config/configured` was never set to true, when the coordinates where set via REST-API.
Fix REST-API `PUT sensor/<id>/config` to check for valid lat/long values (coordinate as string) and provide proper error message.
Refactored the code to check and update daylight sensor `attr/uniqueid` and `config/configured` items.
=> Fix daylight sensor configuration

database.cpp, device_access_fn.cpp, device_js/device_js.cpp, devices/tuya/_TZ3000_4fjiwweb_smart_knob.json, devices/tuya/_TZ3000_4fjiwweb_smart_knob_buttons.js
It's a weird device having two modes, 'scenes' and 'remote', which can be toggled by pressing the knob 3 times very quickly (less than 0.5 seconds). The knob doesn't require bindings for button handling since it sends all commands to group 0x0000 per default.
- This PR also adds support to parse any ZCL command in a DDF and exposes the `ClusterId` to the Javascript engine.
- The database is cleaned up from older invalid light resources for this device.
- Creating group bindings is confirmed by the device but they are ignored, in order to let the knob address another group the *Groups* cluster *Add to group* command is needed which is currently not implemented for the DDF "auto" group mechanism which uses bindings.
Depending on the mode following button events are emitted:
Mode scenes:
- …
=> Add initial DDF for Tuya smart knob (_TZ3000_4fjiwweb)
