dresden-elektronik/deconz-rest-plugin

devices/robb_smarrt/rob_200-029-0_covering.json
This device have 2 clusters set, covering and on/off/setlevel and have as type "Dimmable light"
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6283
=> DDF fix ROB_200-029-0 - Roller Shutter Switch

device_access_fn.cpp
When a ZCL Frame should be parsed for a resource item through the respective `zcl` parse function, defining a command is optional. However, if it is defined and the intention is to only consider those commands, one might experience some unwanted side effects.
Something like `"eval": "Item.val = (ZclFrame.payloadSize == 1 && ZclFrame.at(0) == 0x00) ? false : true;"` will way to often result in true, as all incomming responses are evaluated and not pre-filtered by commandID. The PR now adds that pre-filtering to be able to bail out early.
=> Fix potentially unwanted behavior if DDF has `cmd` defined in zcl parser

device_access_fn.cpp, devices/generic/items/config_selftest_item.json, devices/generic/items/state_carbonmonoxide_item.json, devices/generic/items/state_test_item.json, devices/generic/items/state_windowopen_item.json, devices/xiaomi/xiaomi_jtqj-bf-01lm_gas_leak_detector.json, devices/xiaomi/xiaomi_jtyj-gd-01lm_smoke_detector.json, general.xml, resource.cpp, resource.h, rest_sensors.cpp
Superseedes #5210 and relies on #6264
This PR adds `config/sensitivity` and `config/selftest` to the Honeywell smoke and gas sensors.
The selftest is a bit challenging for the smoke sensor, as it mac polls just every 15 secs (instead of the usual 7.5, a quite remarkable deviation). It's handled via a state change with a duration of 1 min. The successful write of the required value to trigger the audio test is used behind the scenes to set the item back to false. The gas sensor reacts instantly (mains powered).
As for the sensitivity, the same scale for the allowed values and the meaning is applied as for the Hue motion sensor (0 - low, 1 - medium, 2 - high).
Additionally, the tamper state is removed, as both devices do not support it anyway. They have also been excluded from the IAS …
=> Add DDF for Mijia Honeywell gas leak detector JTQJ-BF-01LM/BW and smoke detector JTYJ-GD-01LM/BW

device_js/device_js.cpp
The prototype method is padStart not padString.
=> Fix JS padStart polyfill

devices/woox/woox_r7060_ts0101.json
Is it possible to promote the "Woox R7060 Smart Garden Irrigation Control" DDF to Gold? 
I've got 4 of these and they have two issues with the legacy implementation. Both are solved with using the DDF for this device:
- Battery status is not present in the legacy support, but is there in de DDF
- On reboot of deconz, the device is unresponsive to on/off from deconz, and requires a push of a button on the physical device for commands from deconz to work again. With the DDF, the device on/off calls responds as it should after a reboot.
I've been reading up on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4325 for a solution to both of these problems and I've solved it by just using this DDF
=> DDF: Promote woox_r7060_ts0101 Gold

devices/namron/4512737_thermostat.json
This is the same thermostat as the 4512737, but the model is black and thus has another model identifier: (4512738).
Product name: Namron termostat touch ZigBee 16A
Manufacturer: Namron AS
Model identifier: 4512738
Device type : Thermostat
Note that this is the same DDF as the white model, just with the updated modelId.
=> Add DDF for black namron thermostat

device.cpp, event.cpp, event.h, event_emitter.cpp, event_emitter.h
This was a tricky one. A state handler function must not process any events before the `state.enter` event arrives. Since this event is delivered asynchronously, to not blow up the stack if another state is entered from this event, we could get into troubles and invalid state if other events arrive before the enter event was handled.
- The PR processes all `state.enter` events (marked as urgent) before any other events.
- Removed the dead code for start/stop timer events.
- The event queue drops duplicated events now, so we don't have multiple awake events and similar floating around.
- Speedup of processing events directly after an APS request is processed. No need to wait for the idle timer.
=> Fix Device code async state enter

de_web.pro, de_web_plugin.cpp, device.cpp, device_access_fn.cpp, device_access_fn.h, event.cpp, event.h, zcl/zcl.h
- Fix timeout didn't increase the retry counter of a poll item, machine was stuck in infinite retries.
- Also check that clusterId is the one from the request.
- Allow to optional specify `"noseq": true` in DDF item read parameters to ignore the response ZCL sequence number and only match against clusterId. This is needed for devices like Danfoss Ally which respond with a random sequence number.
- Fix potential rare SEGV when poll items are already empty.
=> DEV improve robustness of ZCL attribute polling

devices/tuya/ts0202_presence_sensor.json
Add support for the _TZ3000_otvn3lne_presence_sensor.json
This is a relatively new sensor from Tuya, but follows the style of using an IAS Zone cluster at 0x500 rather than at 0x0406.
Tested as working on two examples of the sensor using a Conbee II.
Created using the DDF tool in the deconz app, and not externally edited.
=> Add support for _TZ3000_otvn3lne presence sensor (and other 0x0500 IAS cluster Tuya sensors).

de_web_plugin.cpp, rest_rules.cpp
The events where fired fine, but Event::num() wasn't set which is used by some operators.
The change uses the Event constructor which extracts the `num` value from the `ResourceItem`.
Fixes: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6169
=> Fix events of DDF devices not triggering rules properly

de_web_plugin.cpp
When a sensor has a cluster in its fingerprint, which doesn't exist under the sensor's endpoint, function `checkSensorNodeReachable()` will set the respective sensor unreachable, as it checks for existence of **all** clusters.
While it makes sense to add those non-existent clusters to leverage some advantages on the legacy code, it apparently impacts the overall sensor status (falsely). To resolve this, the last check in the function to check for all clusters has been made lazy to just find one fit and then move on.
It's more unlikely this will occur on DDF supported devices, but can happen there as well (especially if the device is not newly paired). Eventually, this cluster check can be removed completely, as it seems to be a too tight precaution.
=> Fix potentially jumpy reachable state for sensors

device_ddf_init.cpp, devices/xiaomi/xiaomi_rtcgq14lm_p1_presence_sensor.json, devices/xiaomi/xiaomi_wrs-r02_h1_switch.json, rest_sensors.cpp, state_change.h, xiaomi.cpp
Primarily Xiaomi sleeping enddevices with configuration options benefit from this change. However, this one might come in handy for other devices as well where timing is important.
An item write frunction can now be extended by the `state.timeout` attribute, where its value is expressed in seconds:
```
"write": {
"at": "0x0152",
"cl": "0xFCC0",
"dt": "0x20",
"ep": 1,
"eval": "Item.val",
"fn": "zcl",
"mf": "0x115F",
"state.timeout": 2
}
```
This allows to overwrite the internal timeout of a change (5 seconds). The current state flow would be: _read -> after 5 seconds write -> after 5 seconds read (to verify)_. As many Xiaomi battery powered devices are deep sleepers usually waking up roughly every 50 mins or upon button press, there's only a tiny timeframe (4 - 6 seconds) to interact with …
=> Expedite state changes via optional write function attribute `state.timeout`

devices/siglis/zigfred_plus_wired_switch.json, devices/siglis/zigfred_uno_wired_switch.json
Initial support for zigfred uno and zigfred plus smart in-wall switches by Siglis.
This pull request builds upon and supersedes pull request GH-6280 and #6258
Many thanks go to @WhistleMaster and @Smanar for the initial code.
Best regards
Markus, Team zigfred
=> Initial support for zigfred uno and zigfred plus smart in-wall switches by Siglis

de_web_plugin.cpp, rest_sensors.cpp
This PR is intended to:
- Allow for a single resource BJ RM01 switch
- Allow usage of state changes for `config/pulseconfiguration` and `config/interfacemode` when setting values via API
=> Preparations for further DDFs

tuya.cpp
The time sync could fail if no sensor or light resources where created at the time of the request. This can happen for DDF devices, I've seen it with Nous E6 sensor.
The PR puts the time sync code on top as it is independed of any sensor and light resources.
Related: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6064
=> Fix Tuya time sync in early pairing stages

devices/tuya/nous_hum_temp_e6.json
For the display to show the current time PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6305 is needed.
Related sensor which may work identically: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6063
=> DDF for Nous E6 temperature and humidity sensor

.github/workflows/verify-ddf-json.yml
This GitHub action verifies that the JSON files under /devices are valid JSON.
There is no schema yet, but this should catch some recurring errors.
=> Add GitHub action to validate DDF JSON files

button_maps.json, devices/tuya/_TZ3000_rco1yzb1_switch.json
-    Product name: SilcerCrest Smart Button (LIDL)
-    Manufacturer: _TZ3000_rco1yzb1
-    Model identifier: TS004F
-    Device type : Switch
Issue : Don't support the long press.
Take care this device have 2 modes enabled with pressing a button 3 times, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6107#issuecomment-1215738357
=> DDF : add support for SilverCrest Smart Button (LIDL) _TZ3000_rco1yzb1

devices/linkind/ZBT-CCTLight-D0106.json
Linkind A60 LED Tunable White Bulb 800 lumen, works here.
Available on Amazon for €10.
=> DDF: Linkind A60 LED Tunable White Bulb 800 lumen

event_emitter.cpp
While an event is processed new events can be added to the queue. If this happens and the `m_queue` capacity is reached the container is resized and references point to an invalid memory address.
The PR makes a local copy of the event so that event handlers are always have a valid reference during execution.
=> Fix event emitter invalid memory references

de_web_plugin.cpp, device_js/device_js.cpp, device_js/device_js.h, device_js/device_js_wrappers.cpp, device_js/device_js_wrappers.h
Prior to this PR only the direct item emitted events after `Item.val = 123`.
The change now also emits events for indirect set items via `R.item(...).val = 456`.
=> DeviceJS emit events for all ResourceItems where setValue() is called

devices/develco/iomzb-110_switch_module.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5258
The device don't use button map stuff.
Ha have 1 binary switch by entry, so 4 ZHAswitch.
=> DDF, Add support for Develco IO module - IOMZB-110

device_access_fn.cpp
The PR adds a check for the command ID and the manufacturer code to the standard zcl parsing function. Those were just used once during function assignment, but not subsequently in regular operations.
=> Add checks for command ID and MFC to `parseZclAttribute()`

crypto/scrypt.cpp
Fixes #6369 - or at least silences the compiler.
=> Fix scrypt use of mixed signed/unsigned char*

product_match.cpp
Another identifier, `_TZE200_cpmgn2cf`, added as a TRV of type `TS0601` to the product mapping.
Since before, I have another identical device, but that one is advertising itself as `_TZE200_cwnjrr72`.
=> Add support for thermostatic radiator valve from MOES

rest_sensors.cpp, utils/utils.cpp
Datatype must be `boolean` here, otherwise the state change will never succeed and finally time out.
=> Fix: use correct datatype for `config/mountingmode`

devices/xiaomi/xiaomi_known_issues_plugfw.md, devices/xiaomi/xiaomi_sp-euc01_smart_plug.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
These devices need to be updated in order to work correctly with the DDFs. This PR adds the known issues section to the DDF based compatibility list:
https://dresden-elektronik.github.io/deconz-rest-doc/devices
and in there links to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly
=> Add wiki link in DDFs for lumi.plug.mmeu01 and lumi.plug.maeu01

device_access_fn.cpp
When `ResourceItems` where updated in the "parse" function outside of the JS engine the related events weren't emitted. This leads to rules to fire too late and also Websocket events not emitted.
Affected where:
- IAS Zone devices `{"fn": "ias:zonestatus"}`
- Time sync `{"fn": "time"}` (likely not so important for rules/websocket)
- Air Quality sensors using `{"fn": "numtostr"}`
=> Fix delays in rules processing and event propagation

devices/tuya/_TZE200_amp6tsvy_wired_switch_1gang.json
- Manufacturer: _TZE200_amp6tsvy
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5505
=> DDF add support for Tuya 1 gang wired Moes ZTS-EUB - 1

devices/develco/zhemi101_external_meter_interface.json
This commit removes the division by 1000 when extracting the consumption value for the Develco/friend external meter interface ZHEMI101. This sensor comes in different flavors that are compatible with different standards. For example the EU version is compatible with the EU standard of 1000 pulses per kWh, so the value is already correct from the sensor.
=> Remove rescaling of consumption in Develco/friend ZHEMI101 DDF

devices/stelpro/smt402ad.json
Changing $TYPE_HUMIDITY_SENSOR uuid to respect the fact that it's on cluster 25 (0x19) and not 1 (0x01)
=> Update smt402ad DDF to reflect correct endpoint

devices/easyaccess/easyfingertouch_doorlock.json, devices/generic/subdevices/door_lock.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870
- Product name: EasyAccess EasyFingerTouch
- Manufacturer: Onesti Products AS
- Model identifier: EasyFingerTouch
This DDF is for sensor version (ZHADoorlock) it expose :
- config/lock to unlock lock the device
- state/lockstate that can be not fully locked/locked/unlocked/undefined
- state/open that say if the door is open or not
This device don't have poll cluster.
I have added a json item corrected for ZHADoorlock.
=> DDf, add support for doorlock EasyAccess EasyFingerTouch

devices/heiman/HS2WD-E.json
From issues https://forum.phoscon.de/t/heiman-hs2wd-e-siren-state-alert-always-remains-at-none/2101/22 and https://forum.phoscon.de/t/heiman-warningdevice-ef-3-0-siren-no-battery-and-tampered-status/2346
=> DDF for Heiman Smart siren HS2WD-E

devices/develco/moszb-140_motion_sensor.json
That's the older version of the 140, apparently with the same endpoints/clusters.
=> Add modelID MOSZB-130 to Develco motion sensor DDF

devices/xiaomi/xiaomi_ssm-u02_t1_switch.json
PR should allow the device to be included and create a ZHASwitch resource, but there's no button map yet.
DDF is **untested**.
=> Add DDF for Aqara T1 single rocker switch (no neutral wire) SSM-U02

general.xml
Re-indent `general.xml`, replacing TABs with SPACEs.
There was also an unmatched close comment (`-->`).
I'm doing this in a separate PR, as GitHub cannot show the changes in any useful way.
Double-checked with `diff -w` that this re-indent didn't break anything:
```
$ diff -w general.*
123,125c123,124
< 	<domain name="General" useZcl="true"
< 	description="The general functional domain contains clusters and information that provides generally applicable functions and attributes that are not specific to other functional domains.">
< 
---
>   <domain name="General" useZcl="true" description="The general functional domain contains clusters and information that provides generally applicable functions and attributes that are not specific to other functional domains.">
>     <domain …
```
=> Re-indent general.xml

de_web_plugin.cpp
In a network with multiple ZGP devices (FoH switch,..) the ZGP proxy keep alive broadcast could have been send in the while loop without taking a break after each broadcast.
The fix adds a minimum delay of one second (idle timer delay) between each broadcast.
=> Fix flooding the network with ZGP broadcasts

devices/xiaomi/xiaomi_sp-euc01_smart_plug.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
Apparently, another rare combination fo system characteristics making this hard to catch.
The previous `matchexpr` seemingly failed on "older" qt JSEngine versions leading to the DDF not being picked up at all and causing various issues. Oddly, this primarily occurred on HA installations/setups.
The amended expression is simpler, more robust and has also been tested with the next JS engine.
=> Use simpler and more robust endpoint match expression for Xiaomi smart plugs

devices/heiman/HS2WD-E.json
The original DDF refers to a non-existent attribute for this device. Changing it to "Date Code" attribute in cluster 0x0000
=> Fix DDF for Heiman Smart siren HS2WD-E, modifiying swversion attribute

database.cpp, device_compat.cpp, utils/utils.cpp, utils/utils.h
When a resource item is changed by DDF code is written to the database quickly. The PR throttles this so that `state/*` items are only written if they don't exist or the version in the database is older than 10 minutes.
In future we need to denote items via JSON to have a storage interval. There are many items which aren't that important and are ok to be stored in larger intervals or only when deCONZ is closed.
The PR also fixes that static modelid and manufacturername items are respected in the DDF init code.
=> Fix too frequent database writes

devices/woox/woox_r7052_ts0215a.json
- Product name: Woox R7052 Smart SOS Button
- Manufacturer: _TZ_3000_ssp0maqm and _TZ3000_zsh6uat3
- Model identifier: TS0215
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4323
=> DDF, add support for Woox R7052 Smart SOS Button

de_web_plugin.cpp, de_web_plugin_private.h, device.cpp, device_access_fn.cpp, device_access_fn.h, device_tick.cpp, state_change.cpp, state_change.h
Track running unicast APS requests of the plugin and core. In Device poll handling and `StateChange` processing check that the queue isn't too busy before adding new APS requests.
This fixes too many `StateChanges` to be fired in parallel as seen for Philips Hue sensors and switches (and likely others).
Related issues: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6461 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445
=> Improve scheduling of APS requests

de_web_plugin.cpp, device.cpp
Polling should only be done if the value is old enough. This wasn't handled properly, fix by always taking lastSet and report timestamps into account.
Depends on #6514
=> Improve Device polling and group task scheduling

devices/generic/items/state_colormode_item.json
`Item.val = Attr.val` produces "2" from the enum8 value, use the generic script to get proper "hs", "ct", etc. strings.
=> Fix state/colormode default DDF item

de_web_plugin.cpp
A non available device could block the processing.
This could lead to lights not being added or removed to a group when requested via REST-API.
=> Fix group membership tasks not executing

resource.cpp
If you read a string on an attribute using the GUI, this one can be updated in the API with added space.
Like for Legrand for exemple
```
"manufacturername": " Legrand",
"modelid": " Cable outlet",
```
Can cause all check based on string will fail.
=> Fix missing whitespace trimming on strings

database.cpp
I've noticed strange output in my debug log, resourcelinks are printed as schedules - fixing it.
=> Fix misleading debug message for resourcelinks

devices/tuya/nous_a1z_smart_plug.json
* _TZ3000_ksw8qtmt_plug_nous_a1z.json renamed to nous_a1z_smart_plug.json
* manufacturername _TZ3000_2putqrmw added
=> Unified DDF for different Nous A1Z smart plugs

button_maps.json, devices/nedis/nedis_zbrc10wt.json
Resolves https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4524
The DDF is based on the DDF from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6506 as the devices seem to be very similar. 
```
Product name: Nedis ZBRC10WT
Manufacturer: TZ3000_fsiepnrh
Model identifier: TS0215A
Device type : Remote
```
=> Add DDF for Nedis ZBRC10WT 4 button remote

devices/develco/moszb-141_motion_sensor.json
This is "just" a stripped version of the MOSZB-140, lacking temperature and light level functionality and it doesn't have a tamper switch.
=> Add DDF for Develco/frient MOSZB-141 motion sensor

devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json
This adds support for the Nedis ZBSC10WT temperature/humidity sensor. Which is nothing more than another TS0201 tuya device.
https://nedis.com/en-us/product/smart-home/climate/monitoring/550726063/smart-climate-sensor-zigbee-30-battery-powered-android-ios-white
=> DDF support for the Nedis temperature/humidity sensor (_TZ3000_fie1dpkm)

button_maps.json, devices/xiaomi/xiaomi_wxkg17lm_e1_switch.json
Adds the DDF and respective button map. Device was previously not supported and map is not yet tested.
=> Add DDF for Xiaomi Aqara E1 dual rocker wireless switch WXKG17LM

product_match.cpp
Added device for Lidl Silvercrest Garden Spike with 2 Sockets HG06620
=> Zusatzgerät für Lidl Silvercrest Gartenspieß mit 2 Steckdosen HG06620 

devices/develco/iomzb-110_switch_module.json
This device is a wired one, so no need battery field.
=> Fix DDF remove unused battery field for IOMZB-110

rest_sensors.cpp
This should allow other devices to make use of `config/devicemode` again (other than Hue wall switch module). A few duplicate string checks have been removed as well, which are already part for the preceding data type check.
=> Fix regression for `config/devicemode` usage

devices/tuya/ZY-M100_human_breathing_presence.json
All is described in issue [#6517](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6517#)
=> Add DDF for ZY-M100 human breathing presence sensor

devices/tuya/_TZE200_pay2byax_door_sensor.json, devices/tuya/_TZE200_pay2byax_openclose_sensor.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6597
- Product name: Zigbee Door Sensor ZG-102Z
- Manufacturer: _TZE200_pay2byax
Clone
- _TZE200_kltffuzl
- _TZE200_fwoorn8y
=> DDF for Tuya door sensor ZG-102Z (_TZE200_pay2byax)

devices/tuya/_TZE200_byzdayie_din_enrgy_meter.json
Replace the PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5287
With 2 clones
-    Manufacturer: _TZE200_byzdayie , _TZE200_fsb6zw01 ,  _TZE200_ewxhg6o9
-    Model identifier: TS0601
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4957
=> DDF for Tuya Single Phase 65A Din Rail Smart Energy Meter

devices/ikea/tredansen_block-out_cellul_blind.json
IKEA PRAKTLYSING is a sibling of the IKEA TREDANSEN block-out cellular blind.
Tested by duplicating the IKEA TREDANSEN Gold DDF.
=> DDF for IKEA PRAKTLYSING cellular blind

devices/sengled/e1c-nb7.json
Proposing a modification to initial json to have Instantaneous power demand as a new monitoring device in third party apps like Domoticz or HS4 (https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/jowihue-w-vuyk-aa/1551540-sengled-e1c-nb7-power-monitoring).
It's perhaps not so clean, thus every advice will be welcome ...
=> Update e1c-nb7.json to add pseudo power cluster for third party apps.

devices/tuya/ts0202_presence_sensor.json
Received device off Aliexpress that is exposing `_TZ3000_6ygjfyll` instead of `_TZ3040_6ygjfyll`
Adding this extra entry fixes the issue.
=> Update ts0202_presence_sensor to support _TZ3000_6ygjfyll

device_js/device_js_duktape.cpp, device_js/device_js_wrappers.cpp
Use intermediate `quint8` variable for value for `zclFrame.payload().at()` to force an unsigned value, see #6670.
Found and fixed same issue for Qt Javascript engine as well.
Unfortunately, I cannot test as I don't have an x64 system running deCONZ.
=> Negative value for zclFrame.payload().at() on x86

product_match.cpp
Added new manufacturerName "_TZE200_h4cgnbzg" of my brand new Hama Thermostats to the product match list.
Signed-off-by: Johannes Ott <mail@johannes-ott.net>
=> Adds new manufacturerName for HAMA TRV

devices/stelpro/smt402ad.json
swversion is not proposed by device, filled from App version attribute to don't have it empty. More cosmetic than other concern.
=> Update SMT402AD swversion attr to be fullfilled from Application version

rest_sensors.cpp
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6692#issuecomment-1411019802.
=> Save automatic state change on `config/duration` to database

devices/xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json
When `xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json` was introduced, a workaround for #1748 was [removed](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5812/files#diff-d0aaee66bc2f60fdd243c0e5b86aebca01fa3eb36c7ec39578d5beeca47078abL8859-L8862).
This PR brings the workaround to the DDF. I have simply added the `parse` section from `generic/items/state_temperature_item.json` and modified it with an `if`.
I did test that this works but I have no experience with DDF so I am quite sure that there is an improved way to do it.
=> Ignore invalid Aqara -100 temperature

devices/adeo/ledsenk08_door_vibration_sensor.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6717
The DDF create a fake endpoint for the door sensor (both are using same cluster)
So the DDF is working but I m not sure for some things.
The device use 1 mask for the door detection and 1 mask for the vibration detection, do we need to use the enrollment stuff on both ?
It seem the device work better if we make a report on the cluster 0x0500, there is no error on logs, but it's not something "classic".
=> DDF, add support for Adeo\Lexman door+vibration sensor

devices/xiaomi/xiaomi_jtqj-bf-01lm_gas_leak_detector.json, devices/xiaomi/xiaomi_jtyj-gd-01lm_smoke_detector.json, devices/xiaomi/xiaomi_rtcgq14lm_p1_presence_sensor.json, devices/xiaomi/xiaomi_wrs-r02_h1_switch.json, rest_sensors.cpp
This PR is intended to allow for "external" control over the state change lifetime, which might be especially relevant for deep sleeping enddevices.
The internal default settings are 180 seconds to have a state change completed. However, if you want to change the configuration on a battery Xiaomi device via API, this is not long enough if you don't want to be forced to push the button on the device to wake it up, as they're only able to receive data only once every 50 mins. With the new attribute, the lifetime can be set at will and the relevant Xiaomi DDFs will get a lifetime of 60 mins. That should be sufficient to complete the change (but does not necessarily omit the physical button press).
=> Expose change timeout via optional write function attribute `change.timeout`

devices/innr/rc_250.json, general.xml
Ok so long story, with the @Idaho947 help, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6618
This device can work with button map, but not possible for all buttons, thoses one just cycle some vlaues.
@kasteleman that know a lot this device have found a solution.
Need to use the GUI, to update the attribute 0x0004 in the cluster 0xfd01 with the value 63
> Attribute is uint8 you should set the first 6 so that would be 00111111
> 00111111 is 63 in dec and 0x3F in hex
After that the device use the special cluster to send special command. So the DDF can work without the buttonmap file.
The manufacture number of the device is 0x1166 but need to use 0x1169 in the request .....
=> DDF : add support for Innr 250

devices/wattle/hc-slm-1_doorlock.json
- Product name: Wattle Door Lock SPL Smart
- Manufacturer: Home Control AS
- Model identifier: HC-SLM-1
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6749
=> DDF add support for Wattle Door Lock SPL Smart

devices/heiman/HS3AQ_air_quality_sensor.json, general.xml
- Product name: Carbon Dioxide Detector Heiman HS3AQ
- Manufacturer: HEIMAN
- Model identifier: HS3AQ-EFA-3.0
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6396
=> DDF add supprt for the Heiman HS3AQ carbondioxide detector

button_maps.json, devices/tuya/_TZ3000_itb0omhv_1gang_bat.json
- Manufacturer: _TZ3000_4upl1fcj
- Model identifier: TS0041
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5843
=> DDF add support for a tuya 1 Gang switch 

rest_lights.cpp
Tuya TS0219 siren only seem to support the combination Siren level=1, Strobe level=1, Warning mode = 1.
All other combinations are ignored.
=> Support Tuya TS0219 siren.

devices/generic/items/config_windowopen_set_item.json, devices/tuya/_TZE200_hhrtiq0x_nedis_trv.json, devices/tuya/_TZE200_thbr5z34_awow__trv.json, devices/tuya/tuya_trv_preset.js, devices/tuya/tuya_trv_preset_set.js, rest_sensors.cpp
So with the @TheHaf 's help, the first working tuya trv with DDF
If you want to help there is a version with more debug lines on the issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5831
Clean version of https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054
**UNTESTED YET**
=> Add DDF for a Tuya TRV _TZE200_hhrtiq0x , and prepare the code to use it

devices/generic/items/attr_swversion_item.json
Why 8400 sec instead of a whole day ?
=> Adjusting swversion to a whole day refresh

devices/tuya/_TZE200_htnnfasr_water_valve
- On/Off and swversion are working
- make battery, frostlock and valve open duration available via RestAPI in separate sensor object (wrong values / no impact on actual device)
=> DDF for LIDL Smart watering timer (_TZE200_htnnfasr)

devices/generic/items/cap_color_gamut_type_item.json, devices/philips/fc03_state.js, devices/philips/light_zll_A.json, devices/philips/light_zll_B.json, rest_lights.cpp
- Leverage 0xFC03 cluster for Hue gamut-A ZLL lights;
- Fix crash of deCONZ v2.20.1, due to JavaScript called from DDF for Hue gamut-A ZLL light;
- Fix missing `state` web socket notification when only `xy` has changed;
- Fix superfluous `capabilities` web socket notification with `websocketnotifyall` and only non-`capabilities` attribute changes.
- Reset `colormode` to `xy` and `effect` to `"none"` from 0xFC03/0x0002 instead of waiting for _Color Control_ to be polled.
=> Hue gamut-A ZLL lights

device_ddf_init.cpp
For legacy sensors, `state/presence` was automatically reset while loading resource values from the DB. With DDF supported sensors, that particular function isn't called and the item keeps its (incorrect) value.
The PR ensures the item is similarly forced to `false` directly after it is loaded from the DB using the new load approach.
=> Force DDF supported presence sensors to state false during start

devices/generic/items/config_windowcoveringtype_item.json, devices/ubisys/j1_5502.json, devices/ubisys/j1r_5602.json, general.xml, window_covering.cpp
While the legacy code was able to check every couple of seconds if the cover is still moving, this code doesn't work anymore while using DDFs. As a quick workaround, it is assumed full open/close doesn't last longer than 30 secs.
With the amended time spans, auto calibration has been successfully tested. All in all not pretty, but easily implemented and functional.
=> Fix ubisys J1 auto calibration

devices/develco/zhemi101_external_meter_interface.json
For my sensor the manufacturername is just "Develco"
=> DDF add variant for Develco ZHEMI101 external meter

devices/aeotec/WG001-Z01_range_extender.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6785
- Product name: Range Extender Zi
- Manufacturer: AL001
- Model identifier: WG001-Z01
=> DDF add support for Aeotec Range Extender Zi

devices/namron/5401395_heater.json
- Product name: Namron Panel Heater (1000W White)
- Manufacturer: Namron AS
- Model identifier: 5401395
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6574
=> DDF add support for Namron Panel Heater

devices/ubisys/d1_5503.json
Loads of `config` attributes for the _Dimmable Light_, for the rest pretty straightforward.
Note that _Instantaneous Demand_ is reportable, but _Current Summation Delivered_ isn't.  Neither are the _Electrical Measurement_ attributes.
I currently have the device online on low voltage, so I cannot test everything, but it looks fine in the sniffer.
=> DDF for ubisys D1

devices/hzc_electric/s900w-zg_water_leak_sensor.json
Copied DDF from bosch water leak sensor and modified for this sensor.
These entities popped up in Home Assistant for the sensor (after a restart of HA):
Confirmed that `binary_sensor.water_x` works
Haven't confirmed the rest of the sensors.
`sensor.water_x_battery` is still 100% so can't be sure it works.
Not sure if `tampered` is relevant for this sensor. How could that trigger?
fixes #6831
=> DDF for HZC S900W-ZG water leak sensor

devices/legrand/cable_outlet.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6707 or https://forum.phoscon.de/t/legrand-cable-outlet/3455
Since last version the Legrand cable outlet stop working in mode "fil pilote". The fingerprint in sensor part are altered in last versions, can impact other devices too https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6706
The PR only impact device detection, all is handled by legacy code.
=> Fix device detection for Legrand cable outlet

device_js/device_js_duktape.cpp
The new code now prints the unsupported value. This can happen for example if NaN, null or undefined is returned, as well as JS objects and arrays.
@ebaauw this should prevent the crash in your network and give some info which item needs to be handled.
I'm not sure what we should do with NaN, null, or undefined in terms of setting a value suitable for a `ResourceItem`.
=> Fix Javascript crash when setting unsupported JS value to item

devices/gledopto/gledopto.json
DDF for my GLEDOPTO flood light, to eliminate the need to whitelist this device in Homebridge deCONZ.
The older GLEDOPTO devices all used `GLEDOPTO` for _Manufacturer Name_ and _Model Identifier_, but they would expose different endpoints.  This is for the RGBW lights, that expose a dimmable light on endpoint 0x0A and an extended color light on endpoint 0x0B, like the flood light that I have on my balcony.  I have some other devices (controllers) whitelisted in Homebridge Hue, but I'm not sure if I still have these.
Notes:
- I want to add a check for _SW Build ID_ of `1.0.2`, but that's currently not possible in a DDF.
- The max/min `ct` values are assumed; unfortunately, the light does not report the actual `ct`.  Note that `ct` is emulated using the RGB channels.
=> DDF for GLEDOPTO RGBW

devices/heiman/smartplug.json
I have two of these models, an older one that exposes neither _SW Version ID_ nor _Date Code_ and a newer one with _Date Code_ of `2018.1.11`.  So `swversion` is based on the date code, and `null` for the older model.
The fingerprints in this DDF should get rid of all the "Missing cluster in sensor fingerprint" messages.
I've removed the `state.power` from the ZHAConsumption resource.  This was completely redundant, as it was also exposed on the ZHAPower resource.  The ZHAConsumption `power` was based on the _Instantaneous Demand_ attribute of the _Simple Metering_ cluster; the ZHAPower on the _Active Power_ of _Electrical Management_.  The device reports the same value on both clusters.  
However, because the device only has room for attribute reporting for five attributes, …
=> DDF for Heiman SmartPlug

devices/lidl/hg06338.json
Pretty straightforward, with following remarks:
- Forcing `manufacturername` and `modelid`to `LIDL Silvercrest` and `HG06338` from Tuya non-sensical names;
- Removed `state.alert`, as device doesn't blink any LED on _Identify_ (from any endpoint);
- Map `swversion` to _Application Version_, as devices supports neither _SW Build ID_, nor _Date Code_.
- Note: this DDF is tested with the old model, which works out of the box.
=> DDF for LIDL Silvercrest Smart USB Extension Lead

devices/ikea/fyrtur_block-out_roller_blind.json
Bug fix: `state.open` showed incorrect value.  Note that `state.open` is true when the blind if fully opened, and false otherwise.  Note that `state.lift` reports % closed, as per ZCL spec.  So `state.open` is true only when `state.lift` is 0.
Remove `state.on` and `state.bri`, which have been deprecated for over three years now.
=> Fix IKEA FYRTUR block-out roller blind

devices/tuya/_TZE200_bvu2wnxz_trv.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6883
- Product name: Avatto Tuya Zigbee Radiator Actuator
- Manufacturer: _TZE200_6rdj8dzm
And 2 clones.
=> DDF for Tuya Avatto radiator actuator (_TZE200_bvu2wnxz)

devices/xiaomi/lumi_curtain.json
This is the original mains-powered `lumi.curtain` from around 2017.
The DDF is pretty straightforward, but note:
- `state.on` and `state.bri` are no longer exposed.  These have been deprecated for _Window Covering_ devices since 2020/04/08, so over three years now.
- No bindings, but the device reports _Current Position Lift Percentage_ to the coordinator out-of-the-box.
- The device doesn't support _DW Build ID_, so `swversion` is based on _Date Code_.
- The device also reports the current position as _Present Value_ on the _Analog Output (Basic)_ cluster.  The legacy C++ code also considers this, but the DDF currently ignores it.  I don't think I've ever seen a report from _Analog Output_ without one on _Window Covering_.
- The device supports a _Reversed_ configuration setting, but …
=> DDF for Xiaomi Aqara Smart Curtain Controller

devices/stelpro/smt402ad.json
Add fingerprint in smt402ad DDF to avoid error in log like "no thermostat found in cluster 0x19" but with all seemed to report anyway.
Fix #5502
=> Add fingerprint in SMT402AD thermostat DDF

de_web_plugin.cpp
This PR is enhancement and fix at the same time.
**Fix**
When already supported switches shall be exposed by 1 resource only (and previsouly had 2 or more resources), they would not work properly, if the model ID is not explicitly hardcoded. That's required so that all relevant events are redirected to a predefined endpoint used by the switch resource.
The new code only requires existence of a single switch resource, which is then automatically selected. Potential events do not get lost anymore.
**Enhancement**
The new code reduces complexity and processing time. Additionally, only `ZHASwitch` resources are now considered as allowed.
Instead of typically 3 sensor selection loops, there should only be 1 in most cases. The hardcoded model IDs are also not required anymore. If just 1 switch …
=> Refactor switch selection to emit button events

de_web.pro, rest_devices.cpp, utils/utils.cpp, utils/utils.h
As deconz was missing a native way to use zigbee install codes, this PR adds the respective capability. The code to derive the required hash is ported from the zigpy implementation.
It has been tested with the reference codes from zigbee smart energy standard and also with some device codes on Ubuntu 20.04 LTS. Also, A Bosch Thermostat II has been successfully paired.
It is important to include the CRC for the correct calculation, so all characters of the code are required.
=> Enable usage of zigbee install codes

devices/generic/items/config_heatsetpoint_item.json
Some thermostat DDFs only have added the resource item `config/heatsetpoint` in its generic form, most notably the Namron and Xiaomi Thermostats. However, it only offers a read and parse function. The required write function to set temperature via attribute 0x0012 is not available and the respective legacy code is not entered for DDF supported devices.
As for the Xiaomi thermostat, it cannot be ensured that the temperature can/must be set this way, the device is not available for testing.
=> Fix resource item `config/heatsetpoint` not having a default write function

devices/tuya/_TZ3000_pfc7i3kt_smart_switch_3gangs_locked.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6682
- Product name: Moes Smart Switch Module 3 Gang MS-104CZ
- Manufacturer: _TZE3000_pfc7i3kt
- Model identifier: TS0003
New DDF because locked state.
=> DDF for Moes Smart Switch Module 3-gang MS-104CZ  (_TZ3000_pfc7i3kt)

general.xml
```
$ /usr/bin/deCONZ --dbg-zcldb=1
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
libpng warning: iCCP: known incorrect sRGB profile 
libpng warning: iCCP: known incorrect sRGB profile 
14:22:41:350 void deCONZ::ZclDataBase::load(const QString&) reading file /usr/share/deCONZ/zcl/general.xml 
14:22:41:362 ZCL line: 1047, invalid range attribute
14:22:41:362 ZCL line: 1048, invalid range attribute
14:22:41:365 ZCL line: 1417, invalid range attribute
```
=> Update general.xml to avoid  'invalid range attribute' at startup

devices/computime-salus/computime_battery.js, devices/computime-salus/ss909zb_temp_sensor.json
Add JSON and associated JS files to enable support of Computime/Salus PS600 Pipe Temperature Sensor
Fix https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6871
=> DDF for Salus PS600 Pipe temperature sensor

general.xml
Update On/Off Cluster (0x0006) to be complinant with Zigbee Cluster library specifications : 
- Default value for `GlobalSceneControl` should be 0x01
- `OnTime` and `OffWaitTime` should be writeable
Close #4642 and fix #6888
=> Fix ZCLDB On/Off cluster attribute compliance

devices/tuya/_TZ3000_TS011F_PowerStrip.json
To use new attribute `config/tuya_unlock` instead of deturning `config/configured`
Will definitely close #6571 and fix #6225
=> Update _TZ3000_TS011F_PowerStrip to include config/tuya_unlock

device_js/device_js_duktape.cpp
On Windows the qPrintable(str) conversion to local 8-bit strings might be problematic.
Related issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6873
Not tested yet if this solves the problem.
=> DucktapeJS convert eval strings to UTF-8

devices/tuya/_TZ3000_zmy4lslw_2channel_module.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6446
- Product name: 2CH Zigbee Switch Module (Tuya Smart ZigBee 3.0 Switch Module)
- Manufacturer: _TZ3000_zmy4lslw
- Model identifier: TS0002
- Device type : 2 gang/ch Switch
=> DDF for Tuya 2-channel switch module (_TZ3000_zmy4lslw)

power_configuration.cpp
For `power_configuration.cpp`, setting the resource item value is changed from `resource::setValue()` back to `resourceItem::setValue()`, as it was prior to version 2.13.0. This will ensure internal resource item timestamps are updated upon reception of an attribute report, even upon no value change.
In the end, this will prevent certain sensors to go into `unreachable` state and bring back some previously seen websocket events.
=> Fix battery updates not contributing to sensor availability

button_maps.json, devices/tuya/_TZ3000_ja5osu5g_smart_button.json
My Try at a DDF for a smart button I recently bought:
https://de.aliexpress.com/item/1005005238316199.html?spm=a2g0o.order_list.order_list_main.11.49a15c5fjVVmas&gatewayAdapt=glo2deu
This is a single button, battery powered (button cell).
The button has two modes, you can switch between them by 3xPressing the button very fast.
Single Press
Double Press
Long Press
**I added the button events for this mode. They are working very reliable.**
_Not very much info yet._
Single Press to turn on, double to turn off.
When on: press and hold to dim.
It seems to increase, then decrease and cycle again.
I was not able to identify a "start" event for dimming, although a "LEVEL_CONTROL STOP" event was sent.
Single press when on: Seems to cycle between 4 Presets of Level & Color Control based on the …
=> Add DDF + Button Map for _TZ3000_ja5osu5g Tuya Smart Button

devices/legrand/Remote_switch_Wakeup_sleep.json
- Manufacturer: Legrand
- Model identifier: Remote Switch Wake up / Sleep
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5902
=> DDF add support for Legrand wakeup/sleep remote 064884

devices/moes/Moes_TZ3000_TS0012_2_gang_switches.json
1. It's not battery powered device but wired with or without neutral (changing name of the DDF file)
2. Newer version need tuya unlock sequence to toggle switch individualy.
Thx to @tosko in Discord to mention this.
=> Use Tuya unlock sequence for Moes 2-gang switch (_TZ3000_18ejxno0)

button_maps.json, devices/ikea/styrbar_remote_control.json
See #6761.
The API still exposes `config/group` and creates a corresponding `/groups` resource.  I suppose the legacy code handling _ZLL Commissioning_ (0x1000) doesn't check for managed devices?
=> IKEA Styrbar firmware 2.4.5.

devices/tuya/_TZ3000_bmfw9ykl_vibration_sensor.json
- Product name: Moes vibration sensor
- Manufacturer: _TZ3000_bmfw9ykl
- Model identifier: TS0210
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6270
WARNING: this device is a vibration sensor, but used as ZHAPresence. The users prefer this mode for the "auto return to false"
=> DDF for Moes vibration sensor (_TZ3000_bmfw9ykl)

crypto/mmohash.cpp, crypto/mmohash.h, de_web.pro, rest_devices.cpp, utils/utils.cpp, utils/utils.h
- Load OpenSSL function dynamically to not hard link the library.
- Replaced various std::vectors with simple C arrays.
- Move code from utils.cpp to crypto/mmohash.cpp
- Verify that that install code has valid sizes of 6, 8, 12, 16 plus two bytes CRC and contains actual hex data.
- Test if the CRC is valid and auto correct if not (there are some devices with invalid/twisted CRC)
- Verified against Zigbee Alliance test vectors.
- On Windows include msvcr100.dll to deCONZ installer, required for the OpenSSL libraries and might be missing on the host system.
This was also needed to get it compile for v2.22.0-beta Windows release (which didn't work out).
=> Refactor MMO hash function

devices/aubess/aubess_multi_sensor_TZ3000_bguser20.json, devices/aubess/aubess_plug_TZ3000_hdopuwv6.json, devices/generic/subdevices/moisture_sensor.json, devices/ikea/cws_light.json, devices/lixee/zlinky_tic_histo_tri_hphc.json, devices/lixee/zlinky_tic_historique_mono_base.json, devices/lixee/zlinky_tic_historique_mono_hphc.json, devices/lixee/zlinky_tic_standard_mono_base.json, devices/lonsonho/_TZ3000_TS011F_smart_plug.json, devices/mli/zbt-extendedcolor.json, devices/moes/Moes_TZ3000_TS0201_temp_hum_with_LCD.json, devices/nexentro/nexentro_blinds_actuator_mini.json, devices/sonoff/snzb-02-multisensor.json, devices/terncy/terncy_dc01_contact_sensor.json, devices/third_reality/3RTHS24BZ_multi_sensor.json, devices/tuya/_TZ3000_cehuw1lw_smartplug_EU.json, devices/ubisys/s1_5501.json, devices/ubisys/s2_5502.json, devices/ubisys/s2r_5602.json, devices/wiser/contact_sensor_cct591011_as.json, devices/wiser/socket-outlet-double-16A-connected.json, devices/xiaomi/lumi_sensor_wleak_aq1.json
The PR contains several commits to better keep an overview and be able to revert or modify if needed.
The majority fixes are for refresh.interval vs reporting interval, if the refresh interval is too low, reporting can't be utilized optimally.
There are some power measurement plugs affected by this which had very small refresh.interval compared to the reporting configuration. The PR raised the refresh.interval in favor of the reporting intervals, some users might not be happy with that, here the max reporting intervals should be lowered, but I strongly advise against max reporting < 60 seconds as it scales poorly.
=> Fix errors reported by DDF validator

crypto/mmohash.cpp
The Install Code MMO module fails to build without OpenSSL installation, don't make this a hard build error.
Not relevant for official releases but internal developer setups.
=> Support building without OpenSSL

backup.cpp, bindings.cpp, change_channel.cpp, de_web_plugin.cpp, green_power.cpp, permitJoin.cpp, reset_device.cpp, rest_configuration.cpp, rest_sensors.cpp, utils/utils.h
Since Qt 5.15.x various functions are deprecated.
More `qrand()` warnings will be fixed in the next release by replacing it with new deCONZ library `U_rand32()` function.
=> Fix deprecated and other warnings

devices/danalock/danalock_v3.json
The main sub-device is a lightoid, therefore add battery as  ZHABattery sensor.
=> Add ZHABattery sensor Danalock V3

devices/tuya/_TZE200_myd45weu_soil_sensor.json
Device is working, already tested by some users.
For exemple https://forum.phoscon.de/t/tuya-qt-07s-myd45qeu-soil-humidity-en-temp-sensor-always-reports-0-humidity/3727
=> DDF set state to "Gold" from "Silver" for the Tuya Soil Sensor _TZE200_myd45weu

devices/sengled/E12-N1E.json
Reported by validator, device didn't have even ctmin/ctmax before.
=> Fix Sengled E12-N1E use cap/color/ct/[min | max]

devices/samsung/samjin_multi_sensor.json
Fix DDF validation errors.
- Invalid item `state/orientation`;
- Invalid refresh interval for `config/battery` (3x).
=> Fix DDF validation errors for samjin_multi_sensor.json

devices/aubess/aubess_multi_sensor_TZ3000_bguser20.json
`parse.eval` was missing. Reported by validator.
=> Fix Aubess multi sensor config/battery parse function

devices/bosch/thermostat2.json
Apparently, this got simply overlooked. Binding was already there, but the resource item was not exposed by the DDF.
=> Fix missing battery resource item for Bosch thermostat II

light_node.cpp, rest_schedules.cpp, rest_touchlink.cpp
Use deCONZ library `U_rand32()` instead.
=> Fix rand() deprecated warnings

device.cpp
Seen for Sonoff multi sensor, the requests kept repeating forever. Handle the error, and fall back to "blindly" creating the bindings.
https://forum.phoscon.de/t/sonoff-sensors-ewelink-disconnected-and-not-sending-out-updates/3774/5
=> DEV handle Mgmt_Bind_rsp NOT_PERMITTED status

devices/bosch/thermostat2.json
=> Fix Bosch thermostat  RBSH-TRV0-ZB-EU battery refresh interval

devices/philips/light_zb3_white.json
Hue ZB3 white lights with firmware image 0x0012.
Similar to the ZB3 White Ambiance lights, except for the colour temperature.  They do seem to support the `candle` dynamic effect.
As yet untested, as I don't have any of these.
I think these lights makes me regret exposing `effect` through `colormode`, as clearly these don't have a regular color mode.  We could set it to `ct` (after all, it's a white, albeit fixed).  For now I just removed `colormode`.  I think that should work with `fc03_state.js`, but that really depends on the values these lights report for the state.
=> DDF for Hue Zigbee-3 White lights

devices/owon/THS317-ET_temperature_sensor.json
It seem this device have 2 version, one using the endpoint 0x01 and one other using the endpoint 0x03
So this DDF use the 0x00 endpoint to autoselect the only one available and make bind/report on both.
Some correction to the DDF too, battery and timer.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5738#issuecomment-1579521543
IDK if this method is better than using 2 DDF with a Endpoint check ?
=> DDF Update for the Owon THS317-ET

devices/xiaomi/lumi_motion_ac01.json
Typo (wrong tag) in handling `config/triggerdistance` for Aqara FP1 from Xioami special attribute, resulting in errors "failed to evaluate expression for 54:ef:44:10:00:4d:7b:c1-01-0406/config/triggerdistance_bis: R.item('config/triggerdistance').val = ['far', 'medium', 'near'][Attr.val], err: TypeError: failed to set Item.val".
(Re-submit of #7073)
=> Bug fix: fp1 triggerdistance not updated from special atttribute

devices/eva/powermeter.json
=> DDF for Eva Powermeter

device_descriptions.cpp, resource.cpp, resource.h, utils/utils.h
Support creation of `ResourceItemsDescriptor` from `generic/items` JSON files. Works the same as the items defined in C++ code.
Dynamic items are only added if they aren't already registered. Later on we can remove items defined in C++ code, but need to reroute `const char*` suffix pointers like `RStateOn`.
=> Add dynamic ResourceItemDescriptors

devices/tuya/_TZE200_bjawzodf_humidity_temp.json
This device use special convertion, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7107
=> Fix humidity values for _TZE200_bjawzodf sensor

devices/home2link/H2L-ZBPH-RS.json
This device was placed under manufacturer Philips. It's actually a Hue shutter which was branded H2L-ZBPH-RS, just like the model ID. It's from the Dutch webshop Home2Link. The DDF was not working (anymore) with manufacturer Philips.
=> Update DDF for H2L-ZBPH-RS roller shutter

button_maps.json, devices/paulmann/501_34_battery_switch.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6102
-    Product name: Zigbee Wandschalter On/Off/Dimm
-    Manufacturer: Paulman LichtGmbH
-    Model identifier: 501.34
-    Device type : Switch
=> DDF Add support for Paulmann Zigbee Switch 501.34

devices/xiaomi/lumi_sensor_wleak_aq1.json
Remove `state/water_bis` as Xiaomi special attribute doesn't always reflect the water detected state, see #7061
=> Bug fix: false water detection for lumi_sensor_wleak_aq1

device_access_fn.cpp, device_js/device_js.h, device_js/device_js_duktape.cpp
Sometimes multiple attributes are received in one message. The Javascript eval is called once for each attribute, but has no knowledge if it's currently working on the first or nth attribute.
The `Attr.index` tells just that, first attribute has index 0, second index 1, etc.
=> Add Attr.index to Javascript engine

BUILDING.md, build-macos.sh
The script compiles the plugin with CMake and adjusts the framework loading paths.
=> Add macOS build script (Intel / x86_64)

device_access_fn.cpp, device_ddf_init.cpp, zcl/zcl.cpp, zcl/zcl.h
The DDF `zcl:cmd` function allows sending arbitrary commands. By specifying the frame control field we can control the whole ZCL frame.
I'm using this to send ZCL structured read/write attributes commands to the ubisys C4 *Device Setup Cluster (0xFC00)*.
These commands are ZCL profile wide and need respective bit 0x01 to be set to 0.
Background: There will be a separate PR for the ubisys devices in question like C4 and Sunricher SR-ZG2833PAC-C4 rebrand  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4703#issuecomment-813414935 structured write attribute is needed because writing the full array of elements to configure larger amounts of input actions (attribute 0x0001) can't be done with one write attribute request, so the C4 can't be configured to let all 4 buttons send …
=> Support setting ZCL frame control (optional) in "zcl:cmd"

devices/generic/items/cap_measured_value_max.json, devices/generic/items/cap_measured_value_min.json, devices/generic/items/cap_measured_value_unit.json, devices/generic/items/state_measured_value_item.json
Related to https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673#issuecomment-1635627969
The main item `state/measured_value` provides a generic way to expose a measurement as floating point value e.g a temperature. The related `cap/measured_value/*` items describe the details — unit, min and max — about the value.
`state/measured_value`
`cap/measured_value/min`
`cap/measured_value/max`
`cap/measured_value/unit`
=> Add generic measured_value items

xmas.cpp
Not actually a bug fix, only using saner functions.
Adding also `'\0'` at the end of strings since `snprintf` may bring surprising results. Further prevent writing over bounds, the code calling `tlvEffect()` does already ensure this, guard for it anyway for later refactor.
=> Fix unsafe sprintf warning, replace with snprintf (xmas strip)

CMakeLists.txt, authorisation.cpp, crypto/password.cpp, crypto/password.h, database.cpp, de_web.pro, de_web_plugin_private.h, rest_configuration.cpp
The main goal was to dynamically load *libcrypt* with `dlopen`. The release build on Debian buster doesn't work Ubuntu Jammy, because it has a different version of the library.
Further the code was separated from `DeRestPluginPrivate` into the `crypto/password.cpp` module not using Qt and be testable.
TODO: Move away from libcrypt and use the stronger scrypt functionality which we already have on each platform.
=> Refactor gateway password code

bindings.cpp, de_web_plugin.cpp, de_web_widget.cpp, reset_device.cpp, rest_lights.cpp, rest_touchlink.cpp, window_covering.cpp, zdp/zdp_handlers.cpp
The PR removes various legacy log outputs which I think aren't relevant anymore and superseeded by DDFs.
Further `QString deCONZ::Address::toStringExt()` is deprecated in first steps to create a QString alternative. Since it's a heavy method also which allocates memory on each call, change debug printing to plain numeric `printf`. It isn't pretty but will do for now. There will be a better method to print MAC addresses soon.
=> Cleanup debug prints and remove addr.toStringExt() usage

database.cpp
A few years back lights where stored not with the uniqueid but as hex string `0x0011223344556677`. By now all setups should have been updated the respective data in `zll.db`.  Also safes us an extra database round trip during start.
=> Remove support loading old MAC address format of lights

bindings.cpp, database.cpp, de_web_plugin.cpp, de_web_plugin_private.h, electrical_measurement.cpp, occupancy_sensing.cpp, rest_lights.cpp, rest_rules.cpp, rest_sensors.cpp, rule.cpp, rule.h
Most of this code was used by old FLS-NB units. It had quite an performance impact in general due all the string comparisons and loops.
The ubisys legacy code is also removed in favor for followup PR adding missing S1-R and D1-R as DDF.
=> Remove FLS-NB, ubisys C++ code and rule "BIND" support

backup.cpp
`deconz.h` has heavy build times and includes everything. This module only needs a few interfaces.
=> Cleanup backup.cpp include dependencies

general.xml
Attribute is available for just a view devices (MOSZB-14X motion sensor and the new SPLZB-14X smart plug).
=> Add Develco specific LED indication attribute to basic cluster

general.xml
Changed duplicate 0x0300 wrong attribute number for Neutral current to right number 0x0303 in Electrical measurement cluster.
=> Fix ZCLDB wrong « Neutral current » attribute number

devices/tuya/_TZ3000_TS0044_4gang_remote.json
Battery % didn't report anymore since last modification, and missing "read" in "config/battery".
Fix #7048
Replace PR #7050 cause of conflicting changes
=> Fix battery not reported for Tuya 4-gang  remote _TZ3000_TS0044_4gang_remote.json

devices/tuya/_TZE200_htnnfasr_water_valve.json
The actual DDF can cause issue on third app if they look for a state/open in the created ZHAOpenClose device.
See https://github.com/home-assistant/core/issues/94921
=> Fix LIDL smart watering timer missing ZHAOpenClose state/open item (_TZE200_htnnfasr)

devices/philips/fc03_state.js, devices/philips/light_zb3_C.json, devices/philips/light_zb3_C_festavia.json, devices/philips/light_zb3_C_gradient.json, devices/philips/light_zll_C.json, hue.cpp
Add support for latest [Hue firmware](https://www.philips-hue.com/en-us/support/release-notes/lamps):
- Rename `loop` effect to `prism` (now visible in the Hue app);
- Add support for new effects `opal` and `glisten` (Hue Festavia, requires firmware 1.107.1);
- Add support for effects on gamut-C ZLL lights (requires firmware 1.108.5).
Note that the DDFs list the possible `effect` values to generate the documentation, but, depending on the firmware versions, the light might not support all of these.
`capabilities/color/effects` lists the actual supported effects, as reported by the light firmware.
=> Add support for latest Hue firmware

devices/generic/items/cap_measured_value_dimension.json, devices/generic/items/cap_measured_value_substance.json, devices/generic/subdevices/carbondioxide_sensor.json, devices/generic/subdevices/formaldehyde_sensor.json, devices/generic/subdevices/particulatematter_sensor.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7121
=> DDF add item file for cap/measured_value/substance

devices/xiaomi/lumi_vibration_aq1.json
See Discord, upon sniffing the Aqara app / Hub M2, it appears that the Xiaomi vibration sensor uses Zigbee values 1: High, 2: Medium, 3: Low.
The device seems to accept and report back any value, even higher then 21.  This was carried over from the C++ code when the sensor was supported initially, but, apparently, never verified.
See also:
- https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1396#issuecomment-478644832
- https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1935#issue-502937054
- https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6919
=> Fix sensitivity for lumi_vibration_aq1

button_maps.json
Bug fix: TRADFRI SHORTCUT Button sent 2004 on double press.  See https://github.com/ebaauw/homebridge-deconz/issues/163.  Obviously, this should be 1004, as the device only has one physical button.
=> Fix TRÅDFRI Shortcut button sent 1004 instead 2004 event

devices/generic/constants.json, devices/generic/subdevices/carbonmonoxide_sensor.json
To shut up DDF validation errors, on `xiaomi/xiaomi_jtqj-bf-01lm_gas_leak_detector.json`
```
Error: 1 validation error in file devices/xiaomi/xiaomi_jtqj-bf-01lm_gas_leak_detector.json at subdevices/0/items
Error: The device is missing the device definition for the type "ZHACarbonMonoxide"
```
=> Add sub device for ZHACarbonMonoxide

devices/tuya/_TZ3000_wkr3jqmr_4channel_module.json
Nothing special, just need the tuya unlock sequence
See https://forum.phoscon.de/t/zigbee-4-channel-smart-relay-switch-tz3000-wkr3jqmr-only-switching-first-relay/3934
=> DDF add support for 4 channel module _TZ3000_wkr3jqmr

devices/generic/items/cap_measured_value_quantity.json, resource.cpp, resource.h, rest_sensors.cpp
- Add JSON for `cap/measured_value/quantity`.  Note that `substance` specifies about what the measurement is (e.g. `air`)`quantity` specifies what is measured (e.g. `temperature`); and `unit` specifies in what units the measurement is done (e.g, `°C`);
- Add support for `state/measured_value` and `cap/measured_value/*` in API and web socket notifications;
=> Add API and websocket support for `state/measured_value` and corresponding `cap` items.

devices/ikea/tradfri_signal_repeater.json
Not the most useful device to expose over the API, but now you can also see the `productid`, next to renaming and identifying it.  Note that there's two variants of the `modelid`, even though they share the same `productid` and firmware image and version.  The do have different values for _Date Code_ (which is supposed to be the hardware manufacturing date, not the firmware date, although it's mostly used for the latter).
```
{
"capabilities": {
"alerts": [
"none",
"select",
"lselect"
]
},
"etag": "f9ba728ddedfb37d0b534e02d61ccb01",
"hascolor": false,
"lastseen": "2023-09-17T14:12Z",
"manufacturername": "IKEA of Sweden",
"modelid": "TRADFRI Signal Repeater",
"name": "Range extender 15",
"productid": "E1746",
"state": {
}, …
```
=> DDF for IKEA TRADFRI Signal Repeater

ui/ddf_editor.cpp, utils/bufstring.h
=> Fix compiler warning for QLatin1String bounds

devices/ikea/tradfri_bulb_e27_cws_opal_600lm.json, devices/ikea/tradfri_bulb_e27_cws_opal_806lm.json, devices/ikea/tradfri_bulb_e27_w_opal_1000lm.json, devices/ikea/tradfri_bulb_e27_ws_opal_980lm.json, devices/ikea/tradfri_control_outlet.json
I only did the DDFs for the bulbs I possess, but I'm pretty sure all IKEA bulbs support 0x0000/0x000A.
E.g. the CWS 806lm now exposes as:
```
{
"capabilities": {
"alerts": [
"none",
"select",
"lselect"
],
"color": {
"ct": {
"computes_xy": true,
"max": 454,
"min": 250
},
"effects": [
"none",
"colorloop"
],
"modes": [
"ct",
"effect",
"hs",
"xy"
],
"xy": {
"blue": [
0.13,
0.04
],
"green": [
0.11,
0.82
],
"red": [
0.68,
0.31
]
}
}
},
"colorcapabilities": 31,
"config": {
"bri": {
"execute_if_off": true,
"on_level": "previous",
"startup": "previous"
},
"color": {
"ct": {
"startup": "previous"
},
"execute_if_off": true
},
"groups": [
"0"
],
"on": {
"startup": false
}
},
"ctmax": 454,
"ctmin": 250,
"etag": "ce840e90b610b475e245fef6bbe8f3a0",
"hascolor": true,
"lastseen": …
```
=> IKEA bulbs: add `productid`

sensor.cpp
CLIP sensors might include `config/battery`, i.e. when the real, non-Zigbee sensor is battery-powered.  On creation of the CLIP sensor, `config/battery` can be specified.  However, the `RConfigBattery` item is not re-created on restart, as CLIP sensors don't get a fingerprint with a _Power Configuration_ cluster.
This PR re-creates the item while loading the CLIP sensor from the database, when the `config` column contains a key for `battery`.
=> Bug fix: CLIP sensor's `config/battery` not restored

devices/ikea/tradfri_wireless_dimmer.json
New DDF, in line with DDFs for other IKEA controllers.
This is the cursed, old, round wireless dimmer.  It insists on sending multiple groupcasts from _Level Control_ when turning it, completely flooding the Zigbee network.  It won't honour any unicast binding for _Level Control_ (even though it does for _Power Configuration_).  When you delete the group binding, it continues to send groupcasts to group 0x0000.
I think the device should have been exposed with only a ZHARelativeRotary resource, since it only supports turning and has no buttons.  This might be challenging to do in JSON and Javascript, as it sends three different commands, _Move_, _Move (with On/Off)_, and _Move to Level (with On/Off)_, that need to be considered for rotary events.  For now it's still exposed as ZHASwitch, …
=> DDF for IKEA TRADFRI wireless dimmer

devices/ikea/0006_presence.js, devices/ikea/tradfri_motion_sensor.json
New DDF, in line with DDFs for other IKEA controllers (!).
The DDF handles both the gen-1 (E1525) and gen-2 (E1745) motion sensors.  They use the same `modelid`; but the `productid` to tell them apart.
Note that these are indeed controllers (not sensors), sending _On with Timed Off_ on detecting motion.  Light can be controlled directly (without deCONZ running) by adding them to the associated group.
The sensors won't detect next motion for the period from _On Time_, so we set `config.duration` based on that parameter.  This is a change with respect to the C++ code, that used `config.delay` for that.  However the DDF logic to reset `state/presence` only works for `config/duration`, and it should be set to `0` (so the C++ code used `config/delay` instead) or to the `config/delay` value …
=> DDF for IKEA TRADFRI motion sensor

devices/ikea/tradfri_open_close_remote.json
New DDF, in line with DDFs for other IKEA controllers.
Controller no longer supports groups.
```
{
"config": {
"battery": 100,
"on": true,
},
"ep": 1,
"etag": "6edbf2215f774c46b5fa62561593d499",
"lastannounced": "2023-09-16T15:02:20Z",
"lastseen": "2023-09-16T15:02Z",
"manufacturername": "IKEA of Sweden",
"mode": 1,
"modelid": "TRADFRI open/close remote",
"name": "Open/Close",
"productid": "E1766",
"state": {
"buttonevent": 1002,
"lastupdated": "2023-09-16T11:26:15.709"
},
"swversion": "2.3.079",
"type": "ZHASwitch",
"uniqueid": "00:0d:6f:ff:fe:e3:f4:90-01-0102"
}
```
=> DDF for TRADFRI open/close remote

devices/legrand/Remote_switch_home_away.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7202
- Product name: BTicino Living Now K4570CW
- Manufacturer: Legrand
- Model identifier: Master remote SW Home / Away
The battery level is probably not working, due to a device specificity.
=> DDF for Legrand / BTicino Master remote SW Home / Away

devices/generic/items/config_alert_item.json, devices/ikea/0008_rotaryevent.js, devices/ikea/symfonisk_sound_contoller.json
New DDF, in line with DDFs for other IKEA controllers.
This is the old Symfonisk controller with one button and dial.
The button is functionally unchanged, but the ZHASwitch resource got some new attributes:
```
{
"config": {
"battery": 50,
"on": true,
},
"ep": 1,
"etag": "af60abcc21af47ac5f0c04c35063063a",
"lastseen": "2023-09-16T19:27Z",
"manufacturername": "IKEA of Sweden",
"mode": 1,
"modelid": "SYMFONISK Sound Controller",
"name": "Symfonisk",
"productid": "E1744",
"state": {
"buttonevent": 2003,
"lastupdated": "2023-09-16T19:27:45.226"
},
"swversion": "2.3.080",
"type": "ZHASwitch",
"uniqueid": "14:b4:57:ff:fe:66:48:62-01-1000"
}
```
As before, the ZHASwitch supports single press (1002), double press (1004) and triple press …
=> DDF for IKEA SYMFONISK Sound Contoller

devices/ikea/starkvind_air_purifier.json, devices/ikea/starkvind_parse_pm2_5.js
The air purifier uses the IKEA-specific 0xFC7D cluster for both the Air Purifier and PM2.5 density sensor features.  We expose the latter as a separate resource, faking a standard 0x042A cluster.
This PR makes the following changes:
- Add `productid`;
- Adjust `change` values in bindings to match data type.
```
{
"config": {
"filterlifetime": 259200,
"ledindication": true,
"locked": false,
"mode": "auto",
"on": true,
},
"ep": 1,
"etag": "d21eaa7d4c887ebfd431ef2a85d7203a",
"lastseen": "2023-09-23T14:07Z",
"manufacturername": "IKEA of Sweden",
"modelid": "STARKVIND Air purifier",
"name": "AirPurifier 141",
"productid": "E2007",
"state": {
"deviceruntime": 858341,
"filterruntime": 21843,
"lastupdated": "2023-09-23T14:07:42.513",
"replacefilter": …
```
=> Updated DDF for IKEA STARKVIND Air Purifier

devices/tuya/_TZ3000_TS0203_door_sensor.json
- Product name: Nous door\windows sensor E3
- Manufacturer: _TZ3000_v7chgqso
- Model identifier: TS0203
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7231
Nothing special, another clone.
=> DDF for Tuya / Nous contact sensor E3 sensor (_TZ3000_v7chgqso)

devices/ikea/blind.json, devices/ikea/fyrtur_block-out_roller_blind.json, devices/ikea/kadrilj_blind.json, devices/ikea/tredansen_block-out_cellul_blind.json
This new DDF exposes the IKEA FYRTUR, KADRILJ, PRAKTLYSING, and TREDANSEN blinds from one DDF.
It replacing the individual DDFs for FYRTUR, and for KADRILJ and the combined DDF for PRAKTLYSING and TREDANSEN.
I've only been able to test it on the FYRTUR as I don't posses any of the other blinds
I've downgraded the existing DDFs to status `Draft`, instead of deleting them.
This way, there's an easy fallback in case the new DDF doesn't work: mark it `Draft` and set the old DDF to `Gold`.
Once the new DDF has been confirmed to work with the other blinds, the existing DDFs can be deleted.
Note that the DDF for the KADRILJ was set to `Silver`.
Changes:
- Add `productid`;
- Add `cap/groups/not_supported`.  While the blinds support the _Groups_ cluster, deCONZ cannot send groupcasts to these, as …
=> New DDF for all IKEA blinds

devices/ikea/blind.json, devices/ikea/tradfri_on_off_switch.json, devices/ikea/tradfri_open_close_remote.json, devices/ikea/tradfri_remote_control.json, devices/ikea/tradfri_shortcut_button.json
Lastest IKEA firmware v24.x.x reports _Battery Percentage Remaining_ in 0.5%, in line with ZCL standard.  Older firmware versions reported full %.  This PR updates the DDFs for impacted devices, supporting both older and newer firmware versions.  This is against my better judgement; I'd rather support only the latest version and tell people to upgrade.
See also #7245.
Note that the 24.x.x  firmware versions aren't yet listed on https://github.com/Koenkk/zigbee-OTA, but IKEA did publish them to http://fw.ota.homesmart.ikea.net/, where the `ikea-ota-download.py` script downloads them from.
=> New IKEA firmware

devices/tuya/_TZ3000_TS0207_water_leak_sensor.json
Nothing special, more clones
- Manufacturer: _TZ3000_k4ej3ww2
- Model identifier: TS0207
- Manufacturer: _TZ3000_awvmkayh
- Model identifier: TS0207
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7259
=> DDF add some clone for Tuya water sensor

database.cpp, de_web_plugin.cpp, device_compat.cpp
Currently there are some database writes after startup and closing deCONZ which are very heavy and just write already present entries. The change prevents these writes.
Also fixes trying to change a valid sensor `uniqueid` to one with invalid endpoint 0xFF.
=> Fix heavy bogus database writes

devices/ikea/blind.json, devices/ikea/fyrtur_block-out_roller_blind.json, devices/iluminize/roller_shutter_actuator_mini.json, devices/merten/meg5113-0300_cover_controller.json, devices/ubisys/j1_5502.json, devices/ubisys/j1r_5602.json, devices/wiser/wall_switch_shutter.json, devices/xiaomi/lumi_curtain.json, devices/xiaomi/lumi_curtain_acn002.json
Should be `false` only when fully closed (`state.lift === 100`), see #7313 .
Also added `state/alert` and `config/alert` for IKEA blinds (as they do support _Identify_).
=> Bug fix: wrong value for `state/open` on Window Covering devices

resource.cpp
The currently set limits for the items (min=0, max=100) are set too tight, so that any higher values reported by an arbitrary attribute are not processible. In such cases, an error is thrown while setting the item value.
```
JS failed to set Item.val for state/lift
failed to evaluate expression for 00:1f:ee:00:00:00:ab:22-01/state/lift: Item.val = Attr.val;, err: TypeError: failed to set Item.val
```
As devices must not necessarily use values from 0 - 100, the DDF is responsible for checking/translating values. This also allows devices to express a potentially unconfigured state.
=> Remove value limits for `state/lift` and `state/tilt` resource items

button_maps.json, devices/woox/woox_r7054_remote.json
- manufacturername: _TZ3000_p6ju8myv
- modelid: TS0215A
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7312
=> DDF, add a clone for Woox Smart Remote Control R7054

devices/tuya/_TZ3000_TS0203_door_sensor.json
- Manufacture name : _TZ3000_yxqnffam
- Model id : TS0203
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7318
=> DDF clone for Tuya window sensor (_TZ3000_yxqnffam)

devices/tuya/_TS0012_2gangs_wired_no_neutral_not_locked.json
Product name : Zemismart Tuya 2 gang no neutral switch
Manufacturer : _TZ3000_lupfd8zu
Model identifier : TS0012
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7301
Nothing special, just an unlocked version.
=> DDF for Zemismart Tuya 2-gang no neutral switch (_TZ3000_lupfd8zu)

bindings.cpp, database.cpp, de_web_plugin.cpp, devices/xiaomi/xiaomi_mccgq12lm_t1_openclose_sensor.json, power_configuration.cpp
Adds support for the device via DDF. The associated legacy code has been removed, as it was non-functional, so the T1 should have never worked (wrong model identifier).
=> DDF for Xiaomi Aqara T1 open/close sensor MCCGQ12LM

devices/ikea/vindstyrka_air_quality_sensor.json, devices/philips/sml001_motion_sensor.json, devices/philips/sml002_motion_sensor.json, devices/philips/sml003_motion_sensor.json, devices/philips/sml004_motion_sensor.json
As the title says, `config/offset` should be added to the temperature or humidity (`measured value`), not subtracted.
=> Bug fix: wrong sign applying `config/offset` to `state/measured_value`

device_descriptions.cpp, device_descriptions.h, ui/ddf_itemeditor.cpp, ui/ddf_itemeditor.h
This PR finally adds the possibility to view/set write functions in the DDF editor. Set parameters in the DDF are displayed correctly and newly set parameters appear as expected in the preview tab.
Additionally, the split of the previously available `zcl` function into `zcl:attr` and `zcl:cmd` should be completed. Both functions are now available to have better distinction.
=> Enable setting/viewing write functions in DDF editor

devices/tuya/_TZ3210_dse8ogfy_fingerbot.json
There is 2 versions for this device. This DDF is for the version that use the on/off cluster (0x0006).
- Model ID : TS0001
- Manufacture Name : _TZ3210_dse8ogfy, _TZ3210_j4pdtz9v
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7303 
and https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7094
=> DDF for Tuya Fingerbot

devices/tuya/_TZ3000_TS0011_1gang_switch_module.json
To support [https://www.ikuu.com.au/product/switch-mechanism/](Mercator 1 gang switch mechanism), add additional new manufacturername to the existing DDF for tuya 1 gang TS0011 switches.
This resolves #7363.
=> DDF clone for Tuya Mercator 1-gang switch module (_TZ3000_7jsk6lxz)

button_maps.json, devices/wiser/dimmer_switch_1Gang.json, devices/wiser/dimmer_switch_2Gang.json, devices/wiser/switch_1Gang.json
With @jensflorian
- Product name : MEG5116-0300 Taster with MEG5171-0000 Inset
- Manufacturer : Schneider Electric
- Model identifier : 1GANG/DIMMER/1
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7340
The only switch version
- Product name :  MEG5161-0000 Relais-Schalt-Einsatz with 5113-0300 Taster
- Manufacturer : Schneider Electric
- Model identifier : 1GANG/SWITCH/1
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7344
The 2 gangs dimmer version
And the only switch version
- Product name :  MEG5126-0300 Taster with MEG5172-0000 dual Insel
- Manufacturer : Schneider Electric
- Model identifier : 2GANG/DIMMER/2
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7342
All DDF are on the same PR because all devices are using the …
=> DDF for various Merten / Schneider dimmer and simple switch

devices/philips/light_zb3_C.json, devices/philips/light_zb3_C_gradient.json, devices/philips/light_zb3_white.json, devices/philips/light_zb3_white_ambiance.json, devices/philips/light_zll_A.json, devices/philips/light_zll_B.json, devices/philips/light_zll_C.json, devices/philips/lom007_smart_plug.json, devices/philips/sml001_motion_sensor.json, devices/philips/sml002_motion_sensor.json, devices/philips/sml003_motion_sensor.json, devices/philips/sml004_motion_sensor.json
Stumbled upon that accidentally while the sniffer was running. Due to an unfortunate DDF amendment, many devices were queried for their modelID as fast as possible. Especially for battery powered devices, this could lead to a more rapid battery drain and eventually have some impact on network resposiveness.
The PR adds either throttling (one query per day) or removes the attribute read requests completely, where appropriate.
=> Stop unnecessary attribute read requests for many Philips/Signify devices

devices/generic/items/attr_manufacturername_item.json, devices/generic/items/attr_modelid_item.json
As discussed in Discord (**general** channel).  `parse` functions were removed in #6878.  This causes issues paring devices, as DDFs are matched an `manufacturername` and `modelid`.  The corresponding Zigbee attribites are read from C++ code alright, so a `read` function isn't needed.  But the resource items were no longer populated, due to the `parse` function missing.
=> Restore `parse` functions for `maufacturername` and `modelid`

de_web_plugin.cpp, device.cpp
Usually the first load via DDF takes a while until Basic cluster is queried. It should be faster with PR #7405 but actually we don't need to query manufacturer name and modelid if we already have the data from legacy DB entries which also match a DDF (and aren't made up).
=> Speed up first time loading of DDF for former legacy lights

devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
There is no such file named `xiaomi_firmware.js`. I suppose it's `xiaomi_swversion.js` used by other DDF.
=> Fix path of xiaomi_firmware.js for xiaomi_sp-euc01_smart_plug.json

devices/xiaomi/xiaomi_zncz12lm_smart_plug.json
There is no such file named `xiaomi_firmware.js`. I suppose it's `xiaomi_swversion.js` used by other DDF.
See #7437 too
=> Fix path for xiaomi_firmware.js for xiaomi_zncz12lm_smart_plug.json

devices/tuya/_TZ3000_TS011F_PowerStrip.json
Removed _TZ3000_bppxj3sf
About `TZ3000_air9m6af` maybe it's `_TZ3000_air9m6af` ?
PS : Who indent with 3 spaces ^^'
=> Remove duplicate device identifier for _TZ3000_TS011F_PowerStrip.json

rest_lights.cpp
Ok, it's a long story, first Legrand firmware don't support set level request, and it need to be blocked.
Medium version don't support it too and are reversed.
New firmware now support it, so the hack can be removed, but somes users still using old firmware.
And as it's covering, not possible to do with DDF
Old firmware have as SwBuild 0xXX and new one 0xXXXXXXXX so the fonction .toUInt() just fail on the check.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7390
Here the full code
```
else if (taskRef.lightNode->modelId() == QLatin1String("Shutter switch with neutral") ||
taskRef.lightNode->modelId() == QLatin1String("Shutter SW with level control"))
{
// Legrand invert bri and don't support other value than 0
bool bStatus = false;
uint nHex = …
```
=> C++ Add support for set Level for Legrand covering

devices/ikea/parasoll_open_close_sensor.json
Mostly standard device. However, it still needs to be verified if it can work with groups, as mentioned in the respective issue.
=> DDF for Ikea Parasoll open/close sensor

devices/danfoss/danfoss_errorcode.js, devices/danfoss/etrv0100_thermostat.json
- On-device schedules will be queried on an hourly bases (update other devices with that capabilitiy will get subsequently) to catch (silent) changes
- Error codes are presented slightly differently (primarily because multiple errors can occur simultaneously)
=> DDF optimizations for Danfoss Ally

devices/ubisys/h1.json, general.xml
Device support is provided based on firmware 1.4.0. A few observations made during testing:
- **Time seems to be asynchronous wherever it can be set or checked.**
On zigbee level, it seems the thermostat queries the coordinator for its time. The respective coordinator response does neither update the time on the thermostat display nor attribute 0x0000 (utc) of the time server cluster.
Similarly, setting the time via the device display, does not have any impact on the attribute 0x0000 (utc) of the time server cluster.
Also, writing the coordinators utc time to the attribute 0x0000 (utc) of the time server cluster does not touch the time on the device display. Overall, this might need some more polishing by ubisys.
- **Sending a direct attribute report from a temperature sensor to the …
=> DDF for ubisys H1 thermostat

device_access_fn.cpp, zcl/zcl.h
The `"any"` wildcard allows forwarding any ZCL command ID on a cluster to the same Javascript handler in `"zcl:cmd"`. Note the command is still filtered for ClusterID. This can be useful for switch button handlers until a more lightweight solution without Javascript will be available.
Warning: This should **not** be used as a default  way to parse different commands leading to large Javascript blobs.
=> DDF support "cmd": "any" wildcard

devices/generic/items/attr_mode_item.json, resource.cpp, resource.h, rest_sensors.cpp, sensor.cpp, sensor.h
It's a legacy thing for switches which was hard wired to Sensor class. Having it as ResourceItem exposes it to DDF to convert legacy switches without breaking changes.
=> Make sensors attr/mode a ResourceItem

devices/legrand/wireless_scenes_command.json
IDK what happen, but on last version the DDF work with unsigned value and previsouly with signed.
The code is now compatible with both.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7463
=> Fix a problem for the Legrand Wireless Scenes command

device_access_fn.cpp, devices/generic/items/state_direction_item.json, devices/tuya/_TZE204_ac0fhfiq_energy_meter.json
With the @decrouxtom help, See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7151
-    Product name: Tuya BiDirectional ZigBee Energy Meter with 150A Clamp Current Sensor
-    Manufacturer: _TZE204_ac0fhfiq
-    Model identifier: TS0601
We have added an item state/direction, can be used later by covering.
=> DDF for Tuya bidirectional energy meter (_TZE204_ac0fhfiq)

device.cpp
The core shows a DDF label on a UI node when a device is running via DDF.
This allows to quickly see which devices aren't handled yet via DDF.
=> Forward device has DDF info to core for UI

devices/sonoff/ck-bl702-swp-01(7020)_plug.json
Product name : WOOLLEY Zigbee Smart Plug
Manufacturer : eWeLink
Model identifier : CK-BL702-SWP-01(7020)
With the help of @larskoenig see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7473
This device use a special cluster, with native report/bind, no consumption.
=> DDF add support for WOOLLEY/eWeLink SmartPlug CK-BL702-SWP-01(7020)

zdp/zdp_handlers.cpp
This mainly affects ConBee III but could also affect ConBee II when the setup is downgraded from ConBee III.
Force old school Zigbee join/re-join without APS level per device link keys for now via Node Descriptor server mask. Since the random generated per device link keys aren't stored or backuped anywhere, this caused problems for rejoining devices of some brands and perhaps battery drain. For proper support of per device APS link keys we need further code to store them in database and forward to firmware.
=> Force classic join/re-join for devices

devices/bosch/thermostat2.json, general.xml
Apparently, this is attribute 0x4040 🙂
=> Add resource item for external temp measurement for Bosch Thermostat II

devices/dresden_elektronik/scene_switch.json, devices/dresden_elektronik/scene_switch_bri.js, devices/dresden_elektronik/scene_switch_on.js, devices/dresden_elektronik/scene_switch_scenes.js
Regression from v2.25.0-beta which removed the button_maps.json entries for the switch.
=> Fix button handlers for dresden elektronik Scene Switch

devices/heiman/hs1rc_keyfob.json
A "3 in 1" this time. Should catch all of those supported keyfobs. Respective legacy code can be removed later.
=> DDF for Heiman Keyfobs HS1RC/HS1RC-M//HS1RC-E

devices/ikea/0400_lightlevel.js, devices/ikea/vallhorn_wireless_motion_sensor.json
Created a DDF file with a JS file,
My 9 year-old, bought one so I had to quickly make it work ;-)
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7454
=> IKEA Vallhorn motion sensor device request

devices/bosch/thermostat2.json
For `config/displayflipped`, I seem to have fat-fingered the data type. It needs to be 0x20 instead of 0x30. In case of `config/externalsensortemp`, the eval JS code was incorrect.
=> Fix setting `config/displayflipped` and `config/externalsensortemp` for Bosch thermostat II

devices/easyaccess/easyfingertouch_doorlock.json
- Product : Doorlock with keypad.
- Manufacturer : EasyAccess / Nimly
- Model identifier : EasyCodeTouch
`zigbeeModel: ['easyCodeTouch_v1', 'EasyCodeTouch', 'EasyFingerTouch', 'NimlyPRO', 'NimlyCode', 'NimlyTouch', 'NimlyIn'],`
All of thoses devices are able to work with the same DDF, haven't added the "easyCodeTouch_v1" because this one is managed by the legacy code, adn I don't want to break something (can't test the impact)
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7525
=> DDF Add support for Doorlock clone from Onesti Products AS

devices/xiaomi/xiaomi_dw-s03d_t1_openclose_sensor.json
Apparently, the sensor was in the wrong operational mode during the initial DDF implementation (worked based on the IAS Zone cluster). The expected way is, however, using the on/off cluster here. The PR fixes the used cluster and removes any unnecessary resource items.
=> Fix non-functioning Aqara T1 open/close sensor

devices/ikea/parasoll_open_close_sensor.json
The IAS Zone enrollment process did not necessarily take place upon pairing. To kickstart it, the read of the status attribute is forced, which should start the process. Open/close events are only reported if this procedure was successful.
=> Make Ikea Parasoll IAS Zone enrollment more robust

devices/tuya/_TZ3000_TS0207_water_leak_sensor.json
-    Product name: Tuya Zigbee Water Sensor
-    Manufacturer: _TZ3000_kstbkt6a
-    Model identifier: TS0207
-    Device type : Sensor
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7259#issuecomment-1910332767
=> DDF add Tuya water sensor clone (_TZ3000_kstbkt6a)

devices/tuya/_TZE200_TS0601_trv.json
Fixes #7333
Adds support for the following TRVs:
* Avatto TRV16 (`_TZE200_rxntag7i`): https://aliexpress.com/item/1005005850177778.html
* Avatto TRV06 (`_TZE200_p3dbf6qs`): https://aliexpress.com/item/1005006191834430.html
In addition, support for the `config/offset` property of the `_TZE200_TS0601` TRVs is added.
=> DDF for Avatto TRV16 and TRV06 TRVs + add support for offset (_TZE200_TS0601)

devices/philips/rdm001_wall_switch_module.json, devices/philips/rom001_smart_button.json
No changes to the devices themselves, just new _Model Identifier_ values.
See also https://hueblog.com/2024/01/12/philips-hue-wall-switch-module-new-revision-available/.
See #7490.
=> New `modelid` values for Hue smart button and Hue wall switch module

devices/centralite/motion_sensor-a.json
The device obviously requires attribute reporting of the IAS Zone status attribute to work properly.
=> Fix CentraLite Motion Sensor-A detection

bindings.cpp, de_web_plugin.cpp, de_web_plugin_private.h, rest_groups.cpp
The device is the old black one, not the white FLS-PP lp. Since the firmware didn't support XY color mode there was a loop in the idleTimer handler iterating over all lights to find out if this device is present. Since the device is likely not in use anymore we can get rid of this CPU cycle eater. If needed introduce a DDF later on.
=> Remove legacy FLS-PP (version 1)  color XY quirk

de_web_plugin.cpp
This functions loops over all lights on each NodeEvent, which is wasteful on the CPU since only in case of a simple descriptor response the body is executed. Therefore only do this if the NodeEvent actually matches and bail out early otherwise.
The function can likely be removed all together, but needs some testing due the `.rx()` call.
=> Optimize updatedLightNodeEndpoint()

bindings.cpp, de_web_plugin.cpp
The old code loops over all sensors and lights until one is found which needs to be queried. With more DDFs this code uses more CPU since almost nothing is to be done here. The PR skips some parts for DDF devices and also breaks up the loops to only process max. 5 sensors and 5 lights at a time, so it scales independent of network size.
=> Skip more legacy code for DDF devices

de_web_plugin.cpp, device.cpp, poll_manager.cpp
This part of the code is a mess and grown over time.
The PR tries to:
- Break up looping over all sensors and lights by only processing up to 5 from each per idle timer call.
- Fetch modelid/manufacturer name from parent Device instead of looping over sibling lights and sensors.
- Control pacing of legacy poll manager via DDF device tick to not schedule things in parallel.
Over time the legacy idle timer and poll manager code needs to go, it will take some iterations to do this and even break legacy devices in the process, which needs to be converted to DDF.
=> Optimize idle timer and legacy device polling

devices/mhcozy/ts0004.json
Bug fix: SyntaxError: unterminated statement
From log:
```
Feb  5 17:41:39 pi6 deCONZ[1500315]: 17:41:37:724 DDF failed to compile JS: /usr/share/deCONZ/devices/mhcozy/ts0004.json
Feb  5 17:41:39 pi6 deCONZ[1500315]: SyntaxError: unterminated statement (line 1)
```
Had to comment out the statement in each `eval`, and un-comment them one by one to identify the offending statement.  NodeJS seems happy with it, but Duktape doesn't like it.
=> Fix MHCOZY 4-Channel SyntaxError: unterminated statement (_TZ3000_u3oupgdy)

database.cpp, database.h, de_web_plugin.cpp, device_ddf_init.cpp, resource.cpp, resource.h
On weak systems like the Raspberry Pi 1 this could block for ~1 second, which is quite bad considering each command.
The PR marks changed ResourceItems to be stored later on if possible and restricts immediate stores more than before.
It's still far from perfect but before the remaining code base is cleaned up there isn't much that can be optimized further.
=> Prevent heavy database writes during APS indications

devices/tuya/_TZ3000_TS0041_1gang_bat.json
Corrected critical typo in _TZ3000_TS0041_1gang_bat.json preventing device detection
Solves the problem introduced in #7520 and referenced in #7364.
=> Corrected critical typo in _TZ3000_TS0041_1gang_bat.json

devices/danalock/danalock_v3.json
danalock battery percentage needs to be divided by 2 otherwise I didn't get any values via rest and values like 182 in deCONZ(VNC).
=> Correct battery percentage of Danalock V3

devices/tuya/_TZE200_ztvwu4nk_thermostat.json
Long story, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7135
It's a wall mounted Thermostat already managed by legacy code, but not the clones. Have finally found someone able to test the DDF.
- Product name: Moes Tuya Thermostat BTH-002
-    Manufacturer: TZE204_aoclfnxz
-    Model identifier: TS0601
-    Device type : Thermostat
=> DDf add support for Moes Thermostat

device_ddf_init.cpp
For items which don't specify a `refresh.interval` in the DDF or at least the generic item, relax to poll every 30 seconds instead of "always and as fast as possible".
This is not ideal and we should have a closer look at the items, also if they use a reasonable poll interval in combination with ZCL attribute reporting.
=> Relax polling of DDF devices without refresh.interval

devices/xiaomi/xiaomi_mfkzq12lm_t1_pro_cube.json, devices/xiaomi/xiaomi_wrs-r02_h1_switch.json
Some read functions were without `refresh.interval`, potentially resulting in excessive unwanted read requests.
=> Fix unnecessary read requests for some Xiaomi devices

device.cpp, device.h, device_descriptions.cpp, device_descriptions.h
There are some devices which support it but reading the binding table results in errors or crashes. If `supportsMgmtBind` is set to `false` no attempts are made to query the binding table.
If nothing is specified the usual auto detection mechanism is used.
Related: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7546#issuecomment-1944671941
=> DDF support disable binding table requests

devices/osram/classic_a60_rgbw.json
The light does crash when ZCL attribute reporting is configured and the binding table is queried. Likely resulting in a watchdog reboot after which the lights turns on in full brightness.
The fix here is to use polling instead of attribute reporting as well as to disable query of the binding table.
Related https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7546
=> Fix OSRAM Classic A60 RGBW crash

devices/osram/par16_50_tw.json
Similar to OSRAM Classic A60 RGBW this DDF doesn't use ZCL attribute reporting or binding table requests, to prevent the firmware crashing.
Related https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7546
=> DDF for OSRAM PAR16 50 TW (GU10)

devices/osram/classic_a60_fil_dim_t.json
Labeled as Filament Clssic A 52 (E27).
The light is likely using a newer chip / Zigbee stack, and seems to support ZCL attribute reporting and binding table requests just fine.
=> DDF for LEDVANCE A60 FIL DIM T

devices/osram/classic_a60_w_clear.json
Don't read binding table and use polling instead of attribute reporting.
Related https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7546
=> Fix OSRAM Classic A60 W clear crash

device.cpp, resource.cpp, resource.h
Some DDFs poll ZCL attributes which aren't present on the device. For example when the DDF was made for a newer firmware version.
The PR marks such items with unsupported attribute flag based on the first ZCL read attribute response and skips polling them from there on.
=> Don't poll unsupported ZCL attributes more than once

device_ddf_init.cpp, state_change.cpp
This happens rarely, but still. If no actual value is present but the DDF has a default value, use that instead.
=> Fix StateChange write with invalid values on boot

de_web_plugin.cpp
This skips reading the database for non existing data.
=> Prevent store ResourceItem item of RDevice resource in APS indication

devices/xiaomi/lumi_vibration_aq1.json
Untested, I haven't the device, but I don't thing It can cause issues.
```
{
"config": {
"battery": 100,
"duration": 65,
"on": true,
"reachable": true,
"sensitivity": -8,
"sensitivitymax": 2,
"temperature": 2600
},
"ep": 1,
"etag": "241c373ed0ac1b2e46c84b5985520189",
"lastseen": "2024-02-17T16:26Z",
"manufacturername": "LUMI",
"modelid": "lumi.vibration.aq1",
"name": "Vibration Chambre Devant",
"state": {
"lastupdated": "2024-02-17T16:26:25.934",
"orientation": [
-1,
79,
11
],
"tiltangle": 6,
"vibration": false,
"vibrationstrength": 4
},
"swversion": "0.0.0_0008",
"type": "ZHAVibration",
}
```
If user have set a value > 2 for sensitivity on the device before the DDF was used (autorised value could go up to 21), this one was stored on the device. And even it don't …
=> Fix negative value for sensitivity for Aqara/Xiaomi vibration sensor

device_js/device_js_duktape.cpp
- Move arena allocator implementation to deconz-lib.
- Add sentinel guards to memory allocations to verify tracking (just to be sure, there wasn't a bug).
- For realloc, reuse the allocated buffer if it is already large enough, which is a bit faster and safes resources.
In future the memory footprint can be reduced further by using a free list. The JS engine already only uses fixed 2048 kB of RAM which can likely be cut to ca. 300 KB for our use cases.
=> Refactor DuktapeJS memory management, use deCONZ library

devices/tuya/_TZ3000_2channel_module.json, devices/tuya/_TZ3000_TS0203_door_sensor.json
Product name : Tuya Door/Window Sensor
Manufacturer : _TZ3000_zgrffiwg
Model identifier : TS0203
Device type to add : Sensor
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7552
Nothing special, just one more clone.
=> DDF clone for Tuya contact sensor (_TZ3000_zgrffiwg)

devices/tuya/_TZ3000_2channel_module.json
- Manufacturer: _TZ3000_nuenzetq 
- Model identifier: TS0002
- Device type : 2 gang/ch Switch
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6446
=> DDF clone for Tuya 2 channel module (_TZ3000_nuenzetq)

devices/lidl/hg08673.json
I've create a PR for this issue, @FlatTV provided the fix in #7603.
I've used a little bit different approach, because the missing ";" seemed as an issue compare to a different DDF of a Tuya Device.
Seems like the ";" was missing and also the "Item" was written Lowercase.
resolves #7603 
old:
```
"eval": "item.val = 10 * Attr.val"
```
new: 
```
"eval": "Item.val = Attr.val * 10;"
```
=> Fix consumption reporting for Lidl SilverCrest (_TZ3000_j1v25l17)

device_js/device_js.h, device_js/device_js_duktape.cpp
`R.hasCluster(endpoint, clusterId [, side]) -> bool`
- endpoint : Number
- clusterId: Number
- side: Number  (optional;  0: server and 1: client cluster side; default: 0)
The numbers can be written as decimal or hexadecimal (but not strings).
In a `matchexpr` this function can be used to select a DDF if the device Simple Descriptors have (or have not) a specific cluster. This is useful since some devices add new clusters via OTA firmware updates, for which new DDFs might be required.
**Important:** This must only be used in DDF `matchexpr` it's not meant for "write" or "parse" functions!
Example: `{ matchexpr: "R.hasCluster(0x0b, 0xFC03)" }`
=> JS add R.hasCluster(ep,clusterId [,side])

device.cpp, resource.cpp, resource.h
Due to some issues in core in past versions the Simple Descriptors may have some clusters which aren't actually there.
For example when reading an attribute for a non existing cluster or attribute, due to the response the cluster would be appended. This is fixed in deCONZ versions > v2.26.1 but the Simple Descriptors need to be refreshed.
In older versions this can be done manually by selecting a node and pressing `7` and `8` or via node context menu.
This PR does it automatically once per session for non sleeping devices.
Proper Simple Descriptors and clusters are needed to match DDFs via `matchexpr: R:hasCluster(...)`.
The Simple Descriptors can also change after OTA updates, in future the refresh should be  done automatically after an update, for now the once per session is a ok'ish …
=> DEV refresh non sleeper endpoints and simple descriptors once per session

bindings.cpp, de_web_plugin.cpp
For legacy devices after scheduling the read of binding table, the flag was never cleared proper.
This was quite spammy and in some setups might have lead to slowness.
=> Fix non stop reading of binding table for legacy devices

devices/philips/light_zb3_C.json, devices/philips/light_zb3_C_festavia.json, devices/philips/light_zb3_C_gradient.json, devices/philips/light_zb3_white.json, devices/philips/light_zb3_white_ambiance.json, devices/philips/light_zll_A.json, devices/philips/light_zll_B.json, devices/philips/light_zll_C.json, devices/philips/light_zll_white_ambiance.json
The existing DDFs require that the lights have a recent firmware which provides the 0xFC03 cluster and otherwise won't function fully for polling and updating the light state.
The PR no longer matches DDFs for older firmware lights, and falls back to the legacy code for them.
Later on we can introduce DDFs which also handle the old firmware with standard clusters instead of 0xFC03 cluster.
~~Note this PR only affects the ZLL lights, I'm not sure if also ZB30 lights need this for older firmware?~~
=> Philips Hue ZLL/ZB3 match DDF only for newer firmware

database.cpp, database.h, de_otau.cpp, de_web_plugin.cpp, de_web_plugin_private.h, device.cpp, device.h, device_access_fn.cpp, device_ddf_init.cpp, device_descriptions.cpp, device_descriptions.h, devices/generic/items/attr_appversion_item.json, devices/generic/items/attr_otaversion_item.json, resource.cpp, resource.h
The PR introduces a new `ResourceItem` `attr/otaversion` which can be used to select DDFs. First example for it is the Ikea on/off switch which needs a DDF for newer and older firmware versions (will be added as separate PR).
**DDF 1)** The old firmware version DDF has following expression:
```json
{
"matchexpr": "var v = R.item('attr/otaversion').val; (v != 0 && v < 0x23079631);"
}
```
**DDF 2)** And the new one:
```json
{
"matchexpr": "var v = R.item('attr/otaversion').val; (v == 0 || v >= 0x23079631);"
}
```
- On first join and after deCONZ update from v2.26.0 to v2.26.1 the firmware version is **not** known yet, and is `0`.
- Therefore the new firmware version **DDF 2** is selected due the `(v == 0 || v >= 0x23079631)` condition!
- When the firmware version is queried via Read …
=> Expose OTA file version for matchexpr

devices/ikea/tradfri_on_off_switch_old_fw.json
The older firmware versions for the on/off switch require a group binding to stop spamming Zigbee group 0 with requests and by that controlling all devices.
Newer firmware versions don't support group bindings well or at all. Therefore two DDFs are needed.
They are selected based on the OTA file version in OTA cluster attribute 0x0002.
More details how it works: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7642
=> DDF for Ikea on/off switch version < 0x23079631

CMakeLists.txt, crypto/mmohash.cpp, crypto/scrypt.cpp
On macOS the system `libssl` and `libcrypto` libraries are not allowed to be used anymore and lead to a crash on `dlopen()`. Upcoming versions of deCONZ bundle OpenSSL version 3.x in `deCONZ.app/Contents/Frameworks/`.
=> Use bundled OpenSSL on macOS

CMakeLists.txt, de_web_plugin.cpp, de_web_plugin_private.h, electrical_measurement.cpp, hue.cpp, rest_api.cpp, rest_api.h, rest_configuration.cpp, rest_lights.cpp, rest_sensors.cpp, simple_metering.cpp, xiaomi.cpp, xmas.cpp, zcl_tasks.cpp
The `de_web_plugin_private.h` header is currently a sink hole for all kinds of unrelated code.
The PR moves parts which are only needed by REST API handling code into a new module `rest_api.h`.
REST API handling code doesn't need to know and depend on all what is in `de_web_plugin_private.h`. Headers like `math.h` and `tuya.h` which where also included are now only included in `.cpp` files which need them. Main goal here is to reduce coupling and also speed up compilation a bit as side effect.
=> Move REST API common code to rest_api.cpp/h

database.cpp, rest_rules.cpp, rest_sensors.cpp, rule.cpp, rule.h
- Only store rules than needed and on application exit.
- Fix store/reload `timestriggered` and `lasttriggered` which was always "none" previously.
=> Improve rules database handling

gateway.cpp, rest_schedules.cpp, sensor.cpp
`deCONZ::jsonStringFromMap()` is a old function in deCONZ library and about to be removed.
`Json::serialize()` is part of the plugin code, it also sucks but is only one entry point to be refactored later on.
=> Replace use of deCONZ::jsonStringFromMap() by Json::serialize()

devices/ubisys/s1_5501_s1r_5601.json
Currently, the light can only be switched on by push-button and can no longer be switched off if the S1(-R) sensor is configured to "mode": "momentary".
According to https://www.ubisys.de/wp-content/uploads/ubisys-s1-technical-reference.pdf, the values for "InputActions Attribute" are not correct. With the default values on page 29 for push-buttons (momentary), it works correctly again:
=> DDF for ubisys S1(-R) corrected

database.cpp
Partly roll back PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7672 (see comments there)
The main reason to have `lasttriggered` and `timestriggered` in the database is to be able to get some insights for if rules are actually used in user setups, when we debug mailed databases.
With the PR the values aren't loaded but are still stored in the database for the last session to aid in debugging.
=> Don't load rules lasttriggered and timestriggered from database

devices/sonoff/trvzb-thermostat.json
As discussed in #7334. Thank you @Smanar!
- Product name : TRVZB
- Manufacturer : SONOFF
- Model identifier : TRVZB
=> DDF for SONOFF TRVZB Thermostat

devices/sonoff/snzb-06p.json, general.xml
The DDF as discussed in Issue #7369 and the general.xml changes for the light sensor.
=> DDF for Sonoff SNZB-06P

devices/xiaomi/xiaomi_wxkg01lm_mini_switch
To a new one, sorry
Xiaomi Mijia Wireless Switch WXKG01LM:
Log:
=> DDF for Xiaomi Mijia Wireless Switch WXKG01LM

button_maps.json, devices/xiaomi/xiaomi_wb-r02d_t1_wireless_mini_switch.json
SW version and battery are assumed to be served via attribute 0x00F7 and would require confirmation. Functionality should be given regardless.
=> DDF for Aqara T1 wireless mini switch WB-R02D

devices/tuya/_TZ3210_up3pngle_TS0205_smoke_sensor.json
Product name Tuya Smoke Detector YG400A
Manufacturer : _TZ3210_up3pngle
Model identifier : TS0205
Nothing special, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7587
=> DDF for Tuya smoke sensor YG400A (_TZ3210_up3pngle)

devices/tuya/_TZE200_bjawzodf_humidity_temp.json
Product name : Tuya Smart Zigbee Thermometer
Manufacturer : _TZE200_zl1kmjqx
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7542
=> DDF Tuya multi sensor clone (_TZE200_zl1kmjqx)

button_maps.json, devices/bosch/bmct-slz_shutter_light_control2.json, general.xml
Interesting device. Making an educated guess here, especially on the switch resource and the button map. Would be great if it could be tested upfront.
Closes #7661
=> DDF for Bosch Light/shutter control II

devices/xiaomi/xiaomi_lumi.curtain.agl001.js, rest_lights.cpp
-    Product name: Aqara curtain driver E1 Rod Version
-    Manufacturer: LUMI
-    Model identifier: lumi.curtain.agl001
This device need a c++ edition because it use don't use the analog cluster but the classic one.
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6469
=> DDF add suppport for Xiaomi ZNCLBL01LM

devices/tuya/_TZ3000_2channel_module.json
Product name : AVATTO ZWSM16-2-Zigbee
Manufacturer : _TZ3000_mtnpt6ws
Model identifier : TS0002
Device type to add : Light
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7646
=> DDF clone for Tuya 2-gang switch (_TZ3000_mtnpt6ws)

devices/philips/fc03_state.js
Damn, #7652 is not working as intended.  Bloody operator precedence in Javascript.
I missed this during testing, since, apparently, my lights were configured with bindings and attribute reporting for _Color Control_.  Apparently, deCONZ won't remove old bindings no longer defined in the DDF?
=> Fix state of Hue lights not always updated correctly

devices/ikea/tradfri_driver_30w.json
It's the same as existing white opal lights, but not sure about the naming of the DDF files for IKEA.
=> Add support for IKEA TRADFRI Driver 30W

devices/xiaomi/xiaomi_ssm-u01_t1_switch.json
When the DDF was created, the resource item `config/temperature` apparently sneaked in, but without any function. Functionality was applied with PR #7650, however, this should not have happened. First of all, `temperature` is a `state` and not `config` item and secondly, it misleadingly exposes a device temperature.
This PR basically reverts back to the initial state while removing the item completely.
=> Removing erroneous temperature exposure for Aqara SSM-U01 switch

devices/generic/subdevices/dimmer_switch.json, devices/moes/Moes_ZM-105-M_1_gang_dimmer.json
adds DDF for Moes ZM-105-M 1 gang dimmer (_TZE204_dcnsggvz).
=> DDF for Moes ZM-105-M 1 gang dimmer (_TZE204_dcnsggvz)

devices/tuya/_TZ3000_TS0203_door_sensor.json
Added new version ZD08Y-ZTU-V1.1 2023-12-08
Manufacturername: "_TZ3000_1bwpjvlz"
Seller: https://de.aliexpress.com/item/1005006629101795.html
=> DDF clone for Tuya door sensor (_TZ3000_1bwpjvlz)

resource.cpp, resource.h, utils/stringcache.cpp, utils/stringcache.h
The atom table only holds at most one copy of any string. Each atom has a 32-bit handle. E.g. 100 lights with same manufacturer name point to the same atom.
This also makes comparisons very fast since only integers are compared.
=> Refactor string cache to use atom table

bindings.cpp
Prevents dynamic QString allocation.
=> Use modelid.toLatin1String() in sendConfigureReportingRequest()

devices/namron/4512737_thermostat.json
Reverts dresden-elektronik/deconz-rest-plugin#7731
Revert as this was not tested by user.
=> Revert "DDF clone for Namron Touch thermostat 16A (4512752)"

de_web_plugin.cpp
First PR closed by error https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7510
-------------------
See https://forum.phoscon.de/t/adding-profalux-zigbee-roller-shutters-via-legacy-code/4372
Ok So I m agree this device is "hacky", but without this code no way to support.
It just have no model id and no Manufacture Name, so the legacy code can support it with this hack
```
//Add missing values for Profalux device
if (existDevicesWithVendorCodeForMacPrefix(node->address(), VENDOR_PROFALUX))
{
//Shutter ?
if (i->deviceId() == DEV_ID_ZLL_COLOR_LIGHT)
{
lightNode.setManufacturerName(QLatin1String("Profalux"));
lightNode.setModelId(QLatin1String("PFLX Shutter"));
lightNode.setNeedSaveDatabase(true);
}
}
```
But this one is disabled whith the recent code.
PS : Profalux have only this …
=> Fix pairing Profalux roller shutter in legacy code

devices/tuya/_TZE200_myd45weu_soil_sensor.json
Product name : Luminea Home Control ZX-8588 (Pearl)
Manufacturer : _TZE200_9cqcpkgb
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7752
=> DDF add tuya clone for Soil sensor

devices/ikea/rodret_dimmer.json
There was a case described on Discord where the dimmer apparently did not fire any button events and there were also no traces of any button presses in the debug log. With the modifications of the DDF and a re-pair of the device, the device was brought to a working state.
Presumably, the added `meta` item was missing and required to actually make the bindings work. However, this is just a guess, as I'm not fully sure about its importance.
=> Fix Ikea Rodret group bindings/button events

.github/workflows/ci-ddf-store.yml
After all this is not the issue.
The 403 error is still here but not related to that permission setting in the workflow
=> Remove unnecessary permissions definition

CMakeLists.txt, database.cpp, database.h, de_web_plugin.cpp, device.cpp, device_ddf_bundle.cpp, device_ddf_bundle.h, device_ddf_init.cpp, device_descriptions.cpp, device_descriptions.h, devices/generic/items/attr_ddf_hash_item.json, devices/generic/items/attr_ddf_policy_item.json, resource.cpp, resource.h, rest_ddf.cpp, rest_ddf.h, rest_devices.cpp, rest_devices.h
**Important:** This larger PR is still work in progress. The PR is meant as tech preview to try out bundles and improve the possible rough edges asap. While the technical side in this PR is almost done, the user facing UI needs to be figured out still.
**Features:**
* Load DDFs from raw JSON files like it has been since DDF introduction.
* Load DDF bundles according to a DDF policy.
* Support multiple versions of a DDF bundle, e.g. to try out new beta of a DDF and revert back to former version if desired.
* Add / update bundles at runtime to a setup via [DDF REST-API](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/ddf/).
* Device support becomes independent from deCONZ releases.
* Install new bundles without restarting deCONZ, aka hot-reload.
A bundle is just a single file …
=> Support for DDF bundles

devices/lidl/hg08673.json
Got a few of these devices and noticed that power was reading fine but consumption was always 0. Noticed a stray ";" in the DDF. After removing it the consumption reading is working.
And maybe a small request: I know this is not the homeassistant Community but i am sure someone can point me to the right place: I noticed that in the output of the REST call for this device is the voltage reading as well. That does not show up in HA. Where in this process is decided what part of the REST output is included in the HA Entitites ?
=> lidl/hg08673 / TS011F -  Removed stray ";" that stopped consumption from working 

database.cpp
On startup the modelid and manufacturername pairs are queried from the database of already paired devices to speedup DDF and bundle lookups.
Logging these is only for debugging purpose and on startup quickly shows which devices are present.
Needs `--dbg-ddf=1` debug switch set.
=> Log which modelid / manufacturer names lookup DDFs

rest_ddf.cpp
The SHA-256 file hash can be used by clients to check if a bundle needs to be updated when the immutable part has changed. E.g. signatures were appended.
Documentation is updated in:
https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/ddf/#get-all-ddf-bundle-descriptors
Example output:
```
{
"377955a530cb7b35917021a47aca7f7ee13fc4d89ecf969da29098f77ad75c1a": {
"uuid": "b5b20dff-da08-45f9-b9b6-4f430ccd9ed4",
"product": "Aqara Vibration Sensor DJT11LM",
"version_deconz": ">2.27.0",
"last_modified": "2023-02-02T13:35:59.000Z",
"device_identifiers": [
[
"LUMI",
"lumi.vibration.aq1"
]
],
"file_hash": "929df9c00f39bd01aea2278b624bfddac03b7dd5aa06ee1e97f9811cc2f6abc5"
}
}
```
=> REST API GET DDF bundle descriptor, return file hash

rest_ddf.cpp
It wasn't implemented and not needed due the preferred multiple descriptor request.
=> REST API remove single DDF descriptor request

rest_api.h, rest_ddf.cpp
Most errors in the returned JSON array were empty. The response now tells if there was invalid DDF bundle data or an internal error.
=> REST API improve DDF upload error reporting

device_descriptions.cpp, device_descriptions.h, rest_devices.cpp, ui/device_widget.cpp
Instead of reloading all raw JSON and bundle DDFs after each upload, wait 2 seconds if more is uploaded before reloading everything. The Phoscon App now supports uploading zipped bundles which may contain hundreds of `.ddf` files.
Further improve hotreload via DDF editor.
=> Improve bulk upload of DDF bundles and hotreload

device_ddf_init.cpp, device_descriptions.cpp
- Reduce noise in `--dbg-ddf` log output
- More error logging while loading DDFs
- Load raw JSON DDFs where manufacturer name constant can't be resolved
This is for the ongoing investigation of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7783
=> DDF loader improve logging; load DDFs where mfname constant is unknown

devices/wiser/room_thermostat_cctfr6400.json
Closes #7795
Unless the manufacturer specific cluster holds this functionality, it is not possible to remotely set any temperatures on the device itself. However, if you physically interact with it, you can apparently steer a thermostat remotely if client and server thermostat clusters are directly bound to each other.
=> Add DDF for Wiser room thermostat CCTFR6400

devices/wiser/itrv_thermostat.json
DDF is supposed to replace the legacy implementation. Although it is expected the device will be fully functional, somebody owning the thermostat should test in deconz GUI if there are any usable system mode settings. For now, it is statically set to auto, but can be changed if necessary.
Legacy code can be removed in a subsequent PR then.
Closes #4148
=> DDF for Drayton Wiser Radiator Thermostat iTRV

rest_ddf.cpp
Sometimes an invalid JSON response was returned.
Fixes: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7800
=> Fix DDF get descriptors request

utils/bufstring.h
No functional change, difference is that U_ASSERT halts right in the debugger.
=> BufString use U_ASSERT() instead of assert()

devices/tuya/_TZE200_myd45weu_soil_sensor.json
Product name : Tuya Soil Sensor
Manufacturer : _TZE204_myd45weu
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7799
=> DDF clone for Tuya Soil sensor (_TZE204_myd45weu)

device_descriptions.cpp, rest_ddf.cpp
Previously it was .ddf but confused users since in the UI raw JSON DDF are shown with DDF label and bundles with DDB label.
The code still supports loading .ddf. New uploaded bundles get .ddb file extension.
=> Change DDF bundle file extension to .ddb

device_descriptions.cpp
There are two bugs.
1) After a new DDF is loaded during pairing the DDF matching search must start from beginning of all loaded DDFs.
2) The actual crash happens when calling std::find_if with two end() iterators, but surprisingly only with Apple Clang, not with GCC on other platforms.
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7698
=> Fix crash on macOS

device_descriptions.cpp
If a system location DDF already existed the user location DDF wasn't picket up correctly.
The problem occurred only for raw JSON DDFs not bundles.
Part of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7845
=> Fix raw JSON DDF load order for user location

de_web_plugin.cpp
The index in `RStateEffectValues` wasn't protected.
Might be the cause to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7871
=> Fix potential SEGV in Mueller effects

devices/nedis/nedis_zbds10wt.json, devices/nedis/tuya_swversion.js
Product name : Nedis zigbee smoke detector zbds10wt
Manufacturer : _TYZB01_wqcac7lo
Model identifier : TS0205
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7812
The device support probably siren (warning device) but the user don't need it
=> DDF for Nedis smoke sensor (_TYZB01_wqcac7lo)

devices/tuya/_TZE200_kb5noeto_motion_sensor.json, devices/tuya/lux_to_lightlevel_50.js
Product name : ZG-204ZM
Manufacturer : _TZE200_kb5noeto
Device type to add : Sensor
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7836
This device is similar to https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/ZY-M100_human_breathing_presence.json but have some difference, like a lux convertion, a battery support , ....
=> DDF for Tuya PIR 24G radar sensor (ZG-204ZM)

device_js/device_js_duktape.cpp, resource.cpp, resource.h
The underlying std::vector<> can invalidate pointers into it when it gets resized  due dynamically added JSON items.
This has shown to cause SEGV.
By using indices instead of pointers we always get valid data.
=> Make ResourceItemDescriptors index based

de_web_plugin.cpp
Always return content length header, even if it is 0. Some clients like curl might hang overwise, waiting for data until the connection timeout hits.
Superseeds https://github.com/dresden-elektronik/deconz/pull/4
=> REST-API always return Content-Length header

de_otau.cpp
The bug/crash not actually happened because all devices have this item (for now), but tidy up anyway to make static analyzer happy.
=> Fix RAttrOtaVersion item null pointer check

devices/legrand/Contactor.json
This device is already supported by legacy core, but miss a feature to enable/disable the "Auto" mode using the API.
Manufacture Name : Legrand
Model ID : Contactor
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3040#issuecomment-2115759508
=> DDF for Legrand Contactor

devices/tuya/_TZ3000_TS0207_water_leak_sensor.json
Product name : Water Leak Sensor ZW06
Manufacturer : _TZ3000_wuep9zng
Model identifier : TS0207
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7805
=> DDF for Tuya water leak clone (_TZ3000_wuep9zng)

devices/tuya/_TZ3000_TS0207_water_leak_sensor.json
Product name : Woox R7050
Manufacturer : _TZ3000_arw23zcs
Model identifier : TS0207
Just one more clone, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7872
=> DDF for Woox water leak sensor R7050 (_TZ3000_arw23zcs)

devices/sonoff/snzb-05p.json
Working version for the SNZB-05P sensor. Tested that when introduced to water shows state in Phoscon and HomeAssistant. Battery level is also visible.
=> DDF for Sonoff Zigbee Water Leak Sensor(SNZB-05P)

devices/xiaomi/xiaomi_wp-p01d_h2_wall_outlet.json
Fully working DDF for the device at hand. However, if the device was paired prior to availability of this DDF, the weird side effect of duplicate power and consumption sensors may occur. This is primarily an issue how deconz treats available legacy sensors.
=> DDF for Aqara wall outlet H2 EU (WP-P01D)

rest_lights.cpp
Suppress non-public items from being displayed in a `lights` resource.  Needed for #7653.
This has been a long-standing omission on my side, refactoring `lightToMap()`.
=> Don't show non-public items in `lights` resources

ui/device_widget.cpp
There is an ongoing issue that the DDF Editor can't be closed due the window title bar is out of screen.
This PR adds the File -> Close action as menu entry with Shortcut Ctrl-W as an workaround.
Forum: https://forum.phoscon.de/t/new-deconz-gui-windows-control-dwm-issues/5097
=> DDF Editor add File -> Close menu entry

devices/tuya/_TZ3210_ncw88jfq_temp-hum-sensor.json
>   "manufacturername": "_TZ3210_ncw88jfq",
>   "modelid": "TS0201",
>   "vendor": "Tuya",
>   "product": "Temperature and humidity sensor",
This device need a *10 correction for humidity, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7884#issuecomment-2321513992
=> DDF for Tuya temperature and humidity sensor (_TZ3210_ncw88jfq)

devices/generic/items/config_detectionrange_item.json, devices/generic/items/state_distance_item.json, devices/xiaomi/lumi_sensor_occupy.agl1.json, general.xml, resource.cpp, resource.h, rest_sensors.cpp
See #7885.
Changes:
- Add new attributes to `general.xml`;
- Add new DDF;
- Re-use `config/resetpresence` to set AI Learning (see issue);
- Create new item `config/detectionrange`.  Unfortunately making that updatable from the API requires some trivial C++ changes;
- Create new read-only item `state/distance`.
=> DDF for Aqara Presence Sensor FP1E

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json
Product name : Tuya Smart Zigbee Temp and Humidity Sensor
Manufacturer : _TZ3000_bjawzodf
Model identifier : TS0201
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7884
=> DDF clone for Tuya temperature and humidity sensor (_TZ3000_bjawzodf)

devices/xiaomi/xiaomi_dcm-k01_t2_dual_relay.json
Apparently, the consumption values are 1000 times too high, so the device already sends Wh.
=> Fix Aqara Dual Relay Module T2 (DCM-K01) consumption values

devices/third_reality/3RSB22BZ_smart_button.json
=> DDF for Third Reality, Inc smart button 3RSB22BZ

devices/bosch/bosch_battery.js, devices/bosch/rfdl-zb-ms_motion_sensor.json
Assumption is here that batteries are depleted with 2.6V and that all attribute reports wake up the device.
=> DDF for Bosch RADION TriTech ZB Wireless Motion Detector RFDL-ZB-MS

devices/xiaomi/xiaomi_lywsd03mmc.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7906
It's probably a variant, but IDK the difference.
=> DDF add a clone for the LYWSD03MMC , Xiaomi  multi sensor

devices/sonoff/snzb-02-multisensor.json
I came across an eWeLink branded model with model number SNZB-02P in a batch of Sonoff branded sensors - this was not catered for in the DDF and was not recognized when added. This DDF fixes it to include the (peculiar) combination of brand and model number.
=> DDF clone for eWeLink SNZB-02P temperature and humidity sensor

devices/tuya/_TZB000_42ha4rsc_window_blinds.json
Product name : LIVARNO home Automatik-Verdunkelungsrollo, »Zigbee Smart Home«
Manufacturer : _TZB000_yqjaollc
Model identifier : TS030F
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7912
=> DDF clone for the Livarno covering (_TZB000_yqjaollc)

de_web_plugin.cpp, de_web_plugin_private.h, devices/philips/fc03_state.js, devices/philips/light_zb3_C.json, devices/philips/light_zb3_C_festavia.json, devices/philips/light_zb3_C_gradient.json, devices/philips/light_zb3_white.json, devices/philips/light_zb3_white_ambiance.json, devices/philips/light_zll_C.json, devices/philips/light_zll_white_ambiance.json, general.xml, hue.cpp, light_node.cpp, resource.h, rest_lights.cpp, xmas.cpp
With the 1.116.3 / 67.116.3 firmware upgrade from May 2024, most Hue lights get additional special effects (see https://www.philips-hue.com/en-us/support/release-notes/lamps).  There's also a new (undocumented) "sunset" effect, which basically is the reverse of the "sunrise" effect.
Most of these changes should be reflected by the API automatically when, the attributes from the _Hue Effects_ cluster are re-read after the firmware update.
This PR adds support for the new "sunset" effect.  It also brings the GUI up to date with the API ("opal" and "glisten" were missing and "prism" was still called "loop").  It enables the Hue-specific _Startup Current X_ and _Startup Current Y_ attributes, now that the GUI bug handling attributes with the same ID but different manufacturer codes has been …
=> Additional special effects for Hue lights

devices/paulmann/501_34_battery_switch.json
Nothing special, just a new model with a space in the Manufacture Name
see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6102#issuecomment-2382377532
=> DDF clone for Paulmann 501.34 light

database.cpp
The title already say is. Imho, the DDF should fully define the device exposure and not blindly revive what has been used/saved as sensor in pre DDF-era.
The current state check would have let the blow to be loaded, which is incorrect, non-existent or non-functional (because of the item count being 0, 2nd last line) and also not part of the respective DDF. This has good potental to confuse end users and is very hard to explain. I wouldn't consider just an item count greater 0 to be enough justification for a legacy sensor to be loaded.
I acknowledge that it eventually could get a bit bumpy with the change, however, DDFs should be correctly defined anyway. It corrects the course a bit going forward and supports in creation of better quality DDFs.
```20:48:50:941 Sqlite sensors: sid = 220 …
```
=> Give DDF content precedence over legacy sensor load

devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json
Manufacturer : _TZ3000_bjawzodf
Model identifier : TY0201
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7684
It add a clone, and help for battery report that can be missing.
=> DDF clone for Tuya multi sensor (_TZ3000_bjawzod); add battery polling

devices/namron/5401395_heater.json
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6792
It add other model, and correct some data convertion.
=> DDF clones for various model of Namrom Panel heater; data conversion correction

devices/sonoff/snzb-04_open_close_sensor.json
Product name : SNZB-04P
Manufacturer : Sonoff
Model identifier : SNZB-04P
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7857
=> DDF clones for Sonoff SNZB-04P

devices/iluminize/led_controller_multi_5.cct.json, devices/iluminize/led_controller_multi_5.dim.json, devices/iluminize/led_controller_multi_5.rgbcct.json, devices/iluminize/led_controller_multi_5.rgbw.json
Controller by iluminize, which can emulate multiple controllers (Dimmer, CCT, RGBW, RGBCCT). 
Will solve #7985
<details><summary>Dimmer</summary>
<p>
</p>
</details> 
<details><summary>CCT</summary>
<p>
</p>
</details> 
<details><summary>RGBW</summary>
<p>
</p>
</details> 
<details><summary>RGBWCCT</summary>
<p>
</p>
</details>
=> DDF for iluminize Multi 5 (4A)

devices/fireangel/0001_battery_voltage.js
Bug fix: values > 3.0V not reported correctly.  Bloody brackets...
See #7941.
=> Fix battery percentage for FireAngel Zigbee module

devices/tuya/_TZE200_TS0601_humidity_temperature.json
This model don't use the same DPID for the battery
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7999
=> DDF solve battery issue for a tuya sensor (_TZE200_9yapgbuv)

general.xml
With the recent change in deconz core, manufacturer specific commands are now only presented upon matching manufacturer code. For Danfoss thermostats, the following commands will be added.
=> Add Danfoss manufacturer specific commands to general.xml

general.xml
With the recent change in deconz core, manufacturer specific commands are now only presented upon matching manufacturer code. The PR adds some for Develco/frient smart plugs.
=> Add Develco manufacturer specific commands to general.xml

devices/philips/light_zb3_C.json
Master is broken since #7961 , caused by commit [9da501cb1e6b4b2b74248837f29212d7ac55d69e](https://github.com/dresden-elektronik/deconz-rest-plugin/commit/9da501cb1e6b4b2b74248837f29212d7ac55d69e), which was not passing / running DDF checks.
=> hotfix wrong manufacturer count vs model count

device_descriptions.cpp
Problem in the issue was reproduced by joining a device without DDF, existing devices stopped processing some of the resource items. The main issue was that when loading new DDFs during a session the per item load counter got updated for all items in all DDFs, but the device items in memory still pointed to former load counter.
TLTR the load counter should only be incremented for the actually new DDF which is loaded into memory.
Fixes: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7935
=> Fix ResourceItems no longer processed when loading additional DDFs

devices/bosch/room_thermostat2.json
Try again #7681
It looks like this in Home Assistant:
Changes:
-  Add `config/coolsetpoint`
-  Add `config/preset`
-  Add `state/on` from #8084
-  Change `vendor`
-  Change `config/mode`
=> Add cooling mode to Bosch room thermostat II (BTH-RM)

devices/neo/NAS-WR01B_TS011F.json
Nothing special see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8070
Manufacturer : _TZ3000_5f43h46b
Model identifier : TS011F
and
Manufacturer : _TZ3000_ww6drja5
Model identifier : TS011F
=> DDF clones for Tuya Smart plug 16A with power monitoring (_TZ3000_5f43h46b, _TZ3000_ww6drja5)

devices/philips/light_zb3_C_festavia.json
I just bought a new set of philips hue festavia lights. They reported a modelid of lcx015 instead of lcx012 which seems to be expected by deconz.
After adding lcx015 to the file, effects like "candle" start working.
=> DDF for Signify LCX015 (Philips Hue Festavia)

devices/tuya/_TZE284_aao3yzhs_soil_sensor.json
Based on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7902
Add support for additional tuya soil sensor.
Similar to https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZE200_myd45weu_soil_sensor.json but needs different temperature handling, therefore additional DDF created.
Other references: https://github.com/Koenkk/zigbee2mqtt/issues/23455
=> DDF for Tuya soil sensor (_TZE284_aao3yzhs)

de_web_plugin.cpp, rest_sensors.cpp
First of all, huge thanks to everyone (especially @mdolnik) involved in adding the initial support for this switch back in 2020. I've had one sitting in a bin and I finally got it working today thanks to PR #3285 !
I knew from previous experiments with this switch, that in addition to the 4 buttons already implemented, the switch also supports undocumented button "chords", through which additional automations can be assigned. See the stellar research user `rkjnsn` did here: https://www.reddit.com/r/Hue/comments/8s85g7/experience_with_illumra_rocker_switch_and_hue/
Using the additional codes listed there, I added support for 4 additional "virtual" buttons on the Illumra Dual Rocker switch, which are accessed by pushing two of the other buttons simultaneously:
- Button 5 == Button 1 (left …
=> DDF improvement for button chords on Illumra Dual Rocker Switch (PTM215ZE Friends of Hue)

devices/third_reality/3RDS17BZ_contact_sensor.json
Add a DDF for the [Third Reality contact sensor](https://zigbee.blakadder.com/Third_Reality_3RDS17BZ.html). The DDF is based on the Ikea Parasoll DDF, as this device also uses the IAS (alarm system) cluster to report opening/closing events.
The device doesn't seem to support reporting for the Battery Percentage Remaining, giving an Unreportable Attribute error when trying to configure it, so this DDF does not configure reporting.
There is an attribute for `config/delay`, which uses a manufacturer-specific cluster to set the delay before an opening event is reported. The cluster is defined by @3reality-support in [zigbee-herdsman-converters PR #7967](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7967) and the [readme for door sensors in …
=> DDF for Third Reality contact sensor (3RDS17BZ)

devices/tuya/_TZ3000_TS0203_door_sensor.json
Product name : Door Contact Avatto?
Manufacturer : _TZ3000_wut53hfm
Model identifier : TS0203
Device type to add: Sensor
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8103
=> DDF clone of Tuya door sensor (_TZ3000_wut53hfm)

devices/ikea/tradfri_bulb_e14_ws_candle_opal_470lm.json, devices/ikea/tradfri_bulb_e27_ws_candle_opal_1055lm.json
Change:
- tradfribulbe14wscandleopal470lm.json -> tradfri_bulb_e14_ws_candle_opal_470lm.json
- tradfribulbe27wsglobeopal1055lm.json -> tradfri_bulb_e27_ws_candle_opal_1055lm.json
=> IKEA light bulbs rename and intervals adjusted

devices/ikea/tradfri_bulb_e14_ws_470lm.json
Reopened #7591
IKEA bulb E14 WS 470lm:
=> DDF for IKEA bulb E14 WS 470lm - intervals extended

de_web_plugin.cpp, de_web_plugin_private.h, device.cpp, device_tick.cpp, ias_zone.cpp, permitJoin.cpp, poll_manager.cpp, resource.cpp, resource.h
This PR is part of a series to get problems with joining and keeping devices working fixed.
Basically we have multiple sub systems fighting each other. Which often works but puts stress on the queues. This PR puts the DeviceTick scheduler in charge to also drive the legacy PollManager so that they don't block each other randomly.
The command to "poll a device" shouldn't come from random places in the code, but from one schedeuler — the DeviceTick.
One improvement on the DeviceTick itself is that it now not just queries the next device at a fixed interval but also actually waits until query is done or signaled that the device can't be queried right now. This speeds up processing and also prevents filling the queues.
Further the legacy `delayedFastEnddeviceProbe()` function for joining …
=> Refactor poll scheduler legacy code vs. Device code

devices/tuya/_TZ3000_TS0203_door_sensor.json
- Product name: Tuya Door Window Sensor
- Manufacturer: _TZ3000_n2egfsli
- Model identifier: SNZB-04
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6598#issuecomment-2646363347
Remark:
It's not a typo, this device realy use an existing manufacture name from tuya but the "SNZB-04" model Id.
And from the link from Ali Express, it have nothing to see with sonoff, it's a pure Tuya device.
=> DDF add a clone for a Tuya door sensor

devices/Jasco-GE/dimmable_light_43080.json, devices/Jasco-GE/onoff_light_43076.json, devices/Jasco-GE/onoff_light_43100.json, devices/Jasco-GE/onoff_light_43102.json
Currently only the light endpoint is handled. But these devices also provide a switch endpoint which we maybe could add later on.
Related forum post: https://forum.phoscon.de/t/all-zigbee-devices-not-working/6100/20
=> DDF for GE Jasco on/off and dimmable lights (43076, 43080, 43100, 43102)

devices/xiaomi/lumi_vibration_aq1.json, general.xml
**Part I** Remove duplicate for Basic cluster Xiaomi manufacturer specific attributes in `general.xml`
The duplicate in `general.xml`  caused the GUI never updating the attributes listed in the proper attribute set. But only the attributes which were placed wrongly in the "Basic Device Information" attribute set.
**Part II** Aqara vibration sensor sensitivity fix.
The REST-API values (0: low, 1: medium, 2: high) map to on device values (3, 2, 1). By default the DDF sets high sensitivity (API value: 2) which will be configured automatically.
When setting low sensitivity `{"sensitivity": 0}` via API the correct value 3 was written to the device. However the bug was: reading back value 3 wasn't parsed right and reverted to default value 2 (high). The fix ensures that only correct on devices …
=> Fix Aqara vibration sensor sensitivity configuration

devices/frient/smszb-120_smoke_detector.json
Fix https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8040
=> Fix siren of Frient Intelligent smoke alarm (SMSZB-120) #8040

device_descriptions.cpp
When Daylight sensor doesn't have a uniqueid yet, and is loaded from database the assert would trigger.
=> Prevent initial setup crash in debug build

devices/third_reality/3RSM0147Z_moisture_sensor.json
Product name : Smart Soil Moisture Sensor
Manufacturer : Third Reality, Inc
Model identifier : 3RSM0147Z
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8138#issuecomment-2734415388
=> DDF for Third Reality Smart Soil Moisture Sensor (3RSM0147Z)

devices/wiser/switch_module_1gang.json
"manufacturername": "Schneider Electric",
"modelid": "PUCK/SWITCH/1",
See https://forum.phoscon.de/t/error-on-the-zigbee-blakadder-site/6255
=> DDF for Schneider Wiser CCT5011-0002

devices/frient/sirzb-111_siren.json
Another mains-powered _IAS WD_ device with battery backup.  It doesn't have a strobe light, but the siren is pretty loud.
```json
{
"capabilities": {
"alerts": [
"none",
"select",
"lselect"
],
"otau": {
"file_version": 131076,
"image_type": 914,
"manufacturer_code": 4117
},
"sleeper": false
},
"ddf_hash": null,
"ddf_policy": "latest_prefer_stable",
"etag": "46911ba4cb0e3be3ea46bf557973762c",
"hascolor": false,
"lastseen": "2025-03-31T08:48Z",
"manufacturername": "frient A/S",
"modelid": "SIRZB-111",
"name": "Siren",
"nwkaddress": 60998,
"state": {
},
"swversion": "2.0.4",
"type": "Warning device",
"uniqueid": "00:15:bc:00:41:00:79:72-2b",
"zonetype": 549
}
```
```json
{
"capabilities": {
"otau": {
"file_version": 131076, …
```
=> DDF for frient Smart Siren (SIRZB-111)

device_descriptions.cpp, device_descriptions.h, rest_devices.cpp
We already have a few DDFs which describe buttons and events. This PR exposes these to the introspect API.
WIP: Currently generic button names are returned in the API, will be fixed soon to return the actual names given in the DDF.
=> Expose button events from DDF

device.cpp
Observed on my Xiaomi vibration sensor. The StateChange tick should only run while the device is awake/reachable.
=> Fix StateChange requests while end device is sleeping

devices/xiaomi/lumi_curtain_acn002.json, devices/xiaomi/xiaomi_lumi.relay.c2acn01.json, devices/xiaomi/xiaomi_qbkg03lm_switch.json, devices/xiaomi/xiaomi_qbkg04lm_switch.json, devices/xiaomi/xiaomi_sp-euc01_smart_plug.json, devices/xiaomi/xiaomi_wsdcgq01lm_temp_hum_sensor.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug.json, devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json, devices/xiaomi/xiaomi_zncz12lm_smart_plug.json
This PR is a continuation of #7827 and now `config/temperature` should be removed from all Xiaomi devices.
=> Removal of `config/temperature` from more Xiaomi devices (part 2)

aps_controller_wrapper.cpp
This prevents battery drain and network traffic and helps to reduce queue blocking. The core does enable APS ACKs again if the device is in error state, see: https://github.com/dresden-elektronik/deconz/commit/c92b978ea1008f77ab28c6361a558388759d483f
=> Disable ZCL Default Response APS ACKs by default

device.cpp
Prevents more useless ZDP requests.
=> Fix don't query binding table for routers with no DDF bindings

device_ddf_init.cpp
The database can contain reachable = true entries but for older timestamps. Fix this on load to prevent early requests to these devices.
TODO: The core should also now about this to adapt Zombie state.
=> Fix loading Device reachable = true, set to false if older than 24h

device.cpp
E.g before this PR `SwBuildId` and similar attributes would be queried even if they already have been queried during the DDF `refreshInterval`.
This reduces traffic after startup.
=> Fix to prevent poll attributes after startup if value timestamp is fresh enough

database.cpp, device_ddf_init.cpp
Not the best approach but right now it's better to have fresh timestamps on startup. Add various `item->clearNeedStore()` to items that were loaded from database too.
=> Fix database not storing / fresh values of strings

devices/aeotec/water_sensor.json, devices/bosch/bwa-1_water_sensor.json
```
"manufacturername": "Samjin",
"modelid": "water",
"vendor": "Samjin, Aeotec",
"product": "Water alarm with temperature",
```
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8160#issuecomment-2797824575
This device is managed by legacy core, but recent version have problem.
=> DDf adds support for Aeotec (Samjin) water leak sensor's

devices/blitzwolf/bw_shp13_smart_plug.json
Product name : BlitzWolf BW-SHP-13
Manufacturer : TZ3210_amdymr7l
Model identifier : TS011F 
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8166#issuecomment-2816688067
=> DDF for BlitzWolf BW-SHP-13 plug clone

devices/centralite/motion_sensor-a.json
The sensor does send motion on/off events correctly. The `config/duration` parameter must not be used here since it does reset the motion state to false after 40 seconds, while the sensor still has motion: true and only reports false after the fact.
Forum: https://forum.phoscon.de/t/diff-behaviour-of-osram-smart-motion-sensor-alexa-phoscon/6295/13
=> OSRAM/Centralite Motion Sensor-A fix wrong presence = false auto reset

CMakeLists.txt, sqlite3/CMakeLists.txt
FetchContent_Populate() with single argument is deprecated.
=> Fix CMake FetchContent_Populate() deprecated warnings

button_maps.json, de_web_plugin.cpp, devices/xiaomi/xiaomi_wxkg11lm_2018_switch.json
Was supported already via legacy code. The DDF also exposes the buttons via introspection. Note that the previous button map also applied for `lumi.remote.b1acn02` which has the extra treble press 1005 event.
The `lumi.remote.b1acn01` only supports double press that's why 1005 isn't exposed.
=> DDF for Xiaomi WXKG11LM 2018 switch

de_web_plugin_private.h, rest_sensors.cpp
After the refactor of `sensorToMap()` when an event arrived in `handleSensorEvent()` not only the respective parent object like `attr/`, `state/`, `config/`, etc. was emitted on Websocket but sometimes other event objects too.
The PR prevents this to filter out any item that doesn't match the events item suffix.
Related forum posts:
https://forum.phoscon.de/t/ghost-button-events-with-deconz-2-29-5-and-aqara-smart-button/6300/14
https://forum.phoscon.de/t/lumi-vibration-aq1-sensor-with-phantom-triggers-since-deconz-2-29-5/6305/6
=> Fix ghost events for sensors

general.xml
Add user interface configuration for temperature/humidity sensor MHO-C401-Z, as mentioned in issue #8069 
```
Attr: 0x0100, INT16 (id:0x29), Temperature offset, in 0.01° steps, range: -32767 (-327.67°)..32767(+327.67°). Default 0.
Attr: 0x0101, INT16 (id:0x29), Humidity offset, in 0.01% steps, range: -32767 (-327.67%)..32767(+327.67%). Default 0.
Attr: 0x0102, INT16 (id:0x29), Comfort temperature minimum, in 0.01° steps, range -32767..+32767 (-327.67° ..+327.67°). Default 2000 (20.00°C).
Attr: 0x0103, INT16 (id:0x29), Comfort temperature maximum, in 0.01° steps, range -32767..+32767 (-327.67° ..+327.67°). Default 2500 (25.00°C).
Attr: 0x0104, UINT16 (id:0x21), Comfort humidity minimum, in 1% steps, range 0..9999 (0..99.99%). Default 4000 (40.00%).
Attr: 0x0105, UINT16 (id:0x21), Comfort …
```
=> Add support for C401N user interface configuration

resource.cpp, resource.h, rest_groups.cpp
Issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8187
When a scene with `on=false` is recalled, we send a *Off With Effect Command* to Ikea lights since they otherwise won't turn off physically. There is also a `StateChange` added to ensure this works, which is usually a good thing.
However if a scene is then called with `on=true`, the `StateChange` *might* still be alive and turn the light off again. This can be seen in the issue.
The PR clears the `state/on` `StateChange` for Ikea lights when a scene is recalled preventing old state to be applied on a newer one.
=> Fix Ikea scenes with on/off going wild

rest_lights.cpp, rest_sensors.cpp
This could have been empty / null after startup and a device not having received events yet.
=> Ensure lights and sensors always have valid Etag

resource.cpp
This is mainly called when loading items from database. The previous implementation didn't handle non UTC timestamps well. Causing items like `attr/lastannounced` to be `null`.
Instead of `QDateTime` the PR uses the `U_TimeFromISO8601()` function of the library which parses all formats. Some items have missing Z in their UTC timestamp for historical reasons. We can't change the database format for these to stay backward compatible, but append the Z for parsing correctly.
=> Fix ResourceItem set (UTC) timestamps from string

database.cpp, database.h, de_web_plugin.cpp, device.cpp, device.h
The database already contains the timestamp when a device was created for DDF and legacy devices. This PR loads the timestamp from the database when the Device instance is created.
Will be used in a further PR.
=> Make Device creation time available

rest_lights.cpp, rest_sensors.cpp
PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8213 already fixes many instances when the problem occurs, but there are valid timestamps for DDF devices in 'resource_items' table.
However that's not always the case. To cleanup old invalid null entries, this PR takes the device creation time as initial value.
=> Fix attr/lastannounced and attr/lastseen sometimes being null

device.cpp
The item is usefull internally to setup the IAS cluster. It is automatically added by the Device class if a IAS cluster is detected. Since `sensorToMap()` also exports Device items it should be non public.
Also prevents showing this attribute as `null` if no data is available for it.
=> Fix don't expose internal attr/zonetype to REST-API

database.cpp, de_web_plugin.cpp, device.cpp
- Device class introduce `DEV_ZgpStateHandler()` which hides `attr/nwkaddress` and sets `capabilitiess/sleeper` to `true`.
- Remove `attr/lastannounced` because ZGP devices don't do this and hence attribute was always `null`.
- Always set `attr/lastseen` when ZGP button event is received.
- When pairing a ZGP device make sure its parent is set to respective Device.
=> Improve ZGP device representation

device.cpp, light_node.cpp
The item doesn't make sense for coordinator.
Also update the NWK address for legacy devices (incl. coordinator) if needed.
=> Fix don't expose Configuration tool (coordinator) lastannounced

rest_lights.cpp, rest_sensors.cpp
For legacy devices this affected items like `cap/sleeper`.
=> Fix don't expose null values from Device for sensors and lights

rest_devices.cpp
`QDateTime::setOffesetFromUtc(0)` isn't enough.
=> Fix /devices endpoint not having UTC timestamps for "value"

devices/lidl/hg06875.json
add support for the Parkside Smart Watering Timer (_TZE200_htnnfasr) by adding the necessary tuya  “magic spell” sequence to enable status updates. 
The device now correctly reports its state when toggled via software or manually.  Tested with deCONZ version 2.30.2 — works reliably after initial pairing.
=> Enable status reporting for Parkside Smart Watering Timer (_TZE200_htnnfasr)

general.xml
Update general.xml file to use more data from LiXee device
=> Update general.xml file to use more data from LiXee device

devices/tuya/_TZE200_TS0601_smoke_detector.json
Product name: Tuya Smoke Fire Alarm Detector
Manufacturer: _TZE283_rccxox8p
Model identifier: TS0601
See #8224
=> DDF clone for Tuya smoke detector (_TZE284_rccxox8p)

devices/tuya/_TZE200_TS0601_humidity_temp.json
Product name: Nous E6
Manufacturer: _TZE284_wtikaxzs
Model identifier: TS0601
See #8225
=> DDF clone for Tuya temperature/humidity sensor (_TZE284_wtikaxzs)

button_maps.json, devices/xiaomi/xiaomi_wxkg16lm_e1_switch.json
Support for Aqara E1 single rocker wireless switch WXKG16LM
"manufacturername": "LUMI"
"modelid": "lumi.remote.acn003"
"product": "Aqara E1 single rocker wireless switch WXKG16LM"
=> DDF for Aqara E1 single rocker wireless switch WXKG16LM

product_match.cpp
I've tried to add an alias for a device clone and edited `product_match.cpp` because I found similar vendor IDs in it.
@Smanar [pointed out](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8261#issuecomment-3024667211), that this file is no longer in use.
A deprecation notice may be useful if this file is indeed deprecated.
=> Deprecate product_match.cpp

devices/tuya/_TZE200_myd45weu_soil_sensor.json
**Purchased at:** https://www.aliexpress.com/item/1005009047166414.html
**Vendor:** [Scimagic](https://scimagic.com.cn/)
=> DDF clone for Scimagic Soil Moisture Sensor (_TZE284_oitavov2)

devices/sonoff/swv_smart_water_valve.json
It seem this device don't use attribute 0x0021 but 0x0020 for battery report.
See [Sonoff SWV-BSP](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8229#issuecomment-2967952385)
=> Fix battery reading of Sonoff water valve SWV-BSP

CMakeLists.txt, database.cpp, de_web_plugin.cpp, event_queue.cpp, plugin_am.cpp
The PR adds an actor model (AM) entry point which lets the GUI and other actors query resources in the plugin by sending small *asynchronous* messages. For now this supports read-only queries against resources and sub-resources of the `Device` class.
There is a virtual file system (VFS) protocol layered on top of AM messages to read virtual directories and files.
In the upcoming deCONZ version the VFS is visualized in a debug widget which can be accessed via menu:
*Help &rarr;  Data view*
**Note:** The widget doesn't know anything about devices or resource items, it only shows directories and entries.
The PR generically presents a path like `/devices/00:15:8d:00:01:a2:4a:ff/subdevices/00:15:8d:00:01:a2:4a:ff-01-0406/state/presence` as tree. Items like `state/presence` represent a …
=> Add actor model to query device resources and resource items as VFS

devices/xiaomi/xiaomi_th-s02d_t1_temp_hum_sensor.json
The sensor sometimes indicates a value of 10 while the atmospheric pressure is always around 1000 hPa. The calculation is not correct. I corrected it and it works in my tests.
=> Fix Xiaomi TH-S02D sensor pressure value calculation

devices/third_reality/3RSMR01067Z_R1_motion_sensor
I added the DDF to support the R1 Motion Sensor, copying the DDF for 3RMS16BZ and adjusting the device id.
=> DDF for Third Reality Motion Sensor R1 (3RSMR01067Z)

devices/tuya/_TZ3000_8uxxzz4b_light_sensor.json
"manufacturername": ["_TZ3000_8uxxzz4b", "_TZ3000_hy6ncvmw", "_TZ3000_9kbbfeho", "_TZ3000_l6rsaipj"],
"modelid": ["TS0222", "TS0222", "TS0222", "TS0222"],
"vendor": "Tuya",
"product": "Tuya Luminance sensor",
See https://forum.phoscon.de/t/light-sensor-zss-qy-ls-c-ts0222-tz3000-8uxxzz4b-unknown/6397
=> DDF for Tuya light sensor (_TZ3000_9kbbfeho)

button_maps.json, devices/ikea/rodret_dimmer.json
New IKEA RODRET models have a different model identifier. Added that to the DDF of the RODRET dimmer and to the button map.
The image in phoscon has to be adjusted accordingly.
=> Fix for new IKEA RODRET model identifier

devices/philips/lom007_smart_plug.json
Adding the modelid: **LOM006** in the DDF file
=> DDF for Philips Hue smart plug LOM006

device_descriptions.h
Seen on macOS somehow clang did not init all fields of the binding to zero when creating an object via `DDF_Binding result = {}`. The `u64 dstExtAddress` wasn't initialized only the `u16 dstGroup` in the union. The ext address was some random stuff from memory.
The fix ensures all fields including `dstExtAdress` are zero. And the unicast destination address is filled with the actual coordinator mac address.
Note: Invalid bindings from previous releases are automatically cleaned up and repaired by the `Device` state machine.
=> Fix creation of invalid Unicast Bindings

devices/namron/140279X_stove_guard.json, general.xml
Product name : Namron Zigbee Stove Guard
Manufacturer : NAMRON AS
Model identifier : 140279X
Device type to add : Stove Guard
Product documentation: https://www.elektroimportoren.no/namron-zigbee-komfyrvakt-veggsensor-hvit-for-ettermontering/1402790/Product.html
=> DDF for Namron Zigbee Stove Guard 140279X

de_web_plugin.cpp, device.cpp, zdp/zdp_handlers.cpp
After deCONZ startup it takes a while until the actual state is propagated. The PR helps to restore the state quicker.
=> Fix state/reachable and config/reachable not stored in database

devices/sengled/e1c-nb7.json
The power was below consumption and below `TYPE_POWER SENSOR`.
=> Removing the double `state/power` from Sengled E1C-NB7

devices/blitzwolf/bw_shp13_smart_plug.json, devices/blitzwolf/bw_shp15_smart_plug.json
I have inserted the BSEED wall socket into `_TZ3000_TS011F_smart_plug` and this PR is only for the intervals.
=> DDF for BlitzWolf BW-SHP-13/15 - intervals extended
